### ISSUE TITLE
Merge packages in Tier IV's AutowareArchitectureProposal repository

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#1]
Merge packages in https://github.com/tier4/AutowareArchitectureProposal.iv

**Comment by kenji-miyake** [comment]
This is the directory structure that @mitsudome-r has discussed and agreed with AWF core members in [this meeting](https://gitlab.com/autowarefoundation/autoware-foundation/-/issues/184#directory-structure-of-universe).
![image](https://user-images.githubusercontent.com/31987104/143979273-ad90f34d-bc20-43c6-ad4d-3906b2f8f618.png)

If it gets messy, we can consider a new structure.
However basically, we should refactor, write design documents with rationales, and move core packages to https://github.com/autowarefoundation/autoware.core.

**Comment by kenji-miyake** [comment]
Although there are DCO errors, we'll ignore them for `tier4/proposal` branch.
https://github.com/autowarefoundation/autoware.universe/pull/3#issuecomment-982235871

When we merge it to `main` branch, @mitsudome-r will sign the squashed commits.

**Comment by kenji-miyake** [comment]
The commit hash we started porting is this.
https://github.com/tier4/AutowareArchitectureProposal.iv/commit/c23d3e1ee46e0dfd9db194949b6c599b477f814f

**Comment by kenji-miyake** [comment]
@tkimura4 @taikitanaka3 @1222-takeshi Could you explain the remaining tasks, please? Nothing?

**Comment by taikitanaka3** [comment]
@kenji-miyake 
I think this issue can be closed.

**Comment by kenji-miyake** [comment]
Cool! After @mitsudome-r checks it, let's close!.

**Comment by kenji-miyake** [comment]
I believe we can close this.
