### ISSUE TITLE
Motion_velocity_smoother should depend the steering_rate_limit

### ISSUE THREAD

**Issue by brkay54** [autowarefoundation/autoware.universe#1023]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Discussion [here](https://github.com/orgs/autowarefoundation/discussions/381)!
Related: #567 

Hello everyone, 

I realized that planning module in Autoware do not depend the steering angle rate. In lateral controller, we can set steering_rate_limit ([here](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_control_launch/config/trajectory_follower/lateral_controller.param.yaml#L49)). When I set lower steering_rate_limit, the states that are calculated by lateral_controller are seem good. But longitudinal controller can not handle, It should slow down the vehicle because of low steering_angle_rate but it is not. vehicle could not turn over the high curvature paths.

### Purpose

As mentioned in discussion, new function which change the velocities w.r.t. steering_rate_limit will be added to motion_velocity_smoother.

### Possible approaches

![image](https://user-images.githubusercontent.com/45468306/171392633-e09c78bd-8650-469e-b529-f71fd0dbdc97.png)
New step will be added after `apply lateral acceleration limit` to decrease velocities where steering_rate > steering_rate_limit.

### Definition of done

- [x] Design algorithm
- [x] Create function and implement it

**Comment by TakaHoribe** [comment]
Nice work. Thank you!
