### ISSUE TITLE
behavior_path_planner crashes when it is launched in .launch.py for the scenario UC-PB-002-0001-Hsinchu

### ISSUE THREAD

**Issue by mehmetdogru** [autowarefoundation/autoware.universe#1049]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

**This issue is a part of https://github.com/autowarefoundation/autoware.universe/issues/566**

`behavior_path_planner` crashes when it is launched using `behavior_planning.launch.py` which it is running along with other launch files once `UC-PB-002-0001-Hsinchu` is run with `scenario_test_runner` 

```bash
[openscenario_interpreter_node-3] [component_container_mt-13] terminate called after throwing an instance of 'std::bad_alloc'
[openscenario_interpreter_node-3] [component_container_mt-13]   what():  std::bad_alloc
[openscenario_interpreter_node-3] [ERROR] [component_container_mt-13]: process has died [pid 6215, exit code -6, cmd '/opt/ros/galactic/lib/rclcpp_components/component_container_mt --ros-args -r __node:=behavior_planning_container -r __ns:=/planning/scenario_planning/lane_driving/behavior_planning --params-file /tmp/launch_params_mep7xn71'].
```
Full log file is here ([bpp_bad_alloc.txt](https://github.com/autowarefoundation/autoware.universe/files/8845104/bpp_bad_alloc.txt))
Video is [here](https://youtu.be/fqMHIWCp4LA).

Here you can observe that `behavior_planning_container`  is died and it is because `behavior_path_planner` crashes. 

So if one would  launch `scenario_test_runner` after disabling the line `behavior_path_planner_component` [in the launch file](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py#:~:text=composable_node_descriptions%3D%5B-,behavior_path_planner_component,-%2C) and then run `behavior_path_planner` with the following code ; it doesn't crash.

```bash
source ~/autoware/install/setup.bash && \
ros2 run behavior_path_planner behavior_path_planner \
--ros-args \
-r __ns:=/planning/scenario_planning/lane_driving/behavior_planning \
-r __node:=behavior_path_planner \
-r behavior_path_planner/input/route:=/planning/mission_planning/route \
-r behavior_path_planner/input/vector_map:=/map/vector_map \
-r behavior_path_planner/input/perception:=/perception/object_recognition/objects \
-r behavior_path_planner/input/odometry:=/localization/kinematic_state \
-r behavior_path_planner/input/scenario:=/planning/scenario_planning/scenario \
-r behavior_path_planner/input/external_approval:=/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/path_change_approval \
-r behavior_path_planner/input/force_approval:=/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/path_change_force \
-r behavior_path_planner/output/path:=path_with_lane_id \
-r behavior_path_planner/output/ready:=/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/ready_module \
-r behavior_path_planner/output/running:=/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/running_modules \
-r behavior_path_planner/output/force_available:=/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/force_available \
-r behavior_path_planner/output/turn_indicators_cmd:=/planning/turn_indicators_cmd \
-r behavior_path_planner/output/hazard_lights_cmd:=/planning/hazard_lights_cmd \
-p bt_tree_config_path:=$HOME/autoware/src/universe/autoware.universe/planning/behavior_path_planner/config/behavior_path_planner_tree.xml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml \
--params-file $HOME/autoware/src/universe/autoware.universe/vehicle/vehicle_info_util/config/vehicle_info.param.yaml
```

**!!! Please give the right file paths if your autoware repo is now at $HOME !!!** 

### Expected behavior

`behavior_path_planner` shouldn't crash.

### Actual behavior

`behavior_path_planner` crashes for a certain scenario.

### Steps to reproduce

1. Download [map_data](https://gitlab.com/autowarefoundation/operational-design-domains/-/tree/master/public_road_bus/maps/hsinchu).
2. Download the [scenario file](https://gitlab.com/autowarefoundation/operational-design-domains/-/blob/master/public_road_bus/UC-PB-002-0001-Hsinchu.yaml).
3. Launch the `scenario_test_runner` with the following code after setting the right file paths:
```bash
source ~/autoware/install/setup.bash && \
ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle \
scenario:=$HOME/operational-design-domains/public_road_bus/UC-PB-002-0001-Hsinchu.yaml \
architecture_type:=awf/universe launch_rviz:=true launch_autoware:=true
```

### Versions

- OS: Ubuntu 20.04
- ROS2 Galactic
- https://github.com/autowarefoundation/autoware/commit/5e76cfd1a0359d6c275accadfa5dc2dff9f0d861
- autoware.universe: https://github.com/autowarefoundation/autoware.universe/commit/932ff58be7f51a8461def4bd57876f3bd766e2aa
- https://github.com/tier4/scenario_simulator_v2/commit/7318ece6d59bed4b7a82d648af34113a2e8faf39
- [Operational Design Domains](https://gitlab.com/autowarefoundation/operational-design-domains): [`c589c2`](https://gitlab.com/autowarefoundation/operational-design-domains/-/commit/c589c27fe5768ffb46c8dc8c2243485c99edf9cf) 

### Possible causes

It might be related to the container structure and the memory allocation related to it.

**Comment by mehmetdogru** [comment]
I would appreciate if someone else also can produce the error.

**Comment by JianKangEgon** [comment]
Well, I was also confused about this kind of issue. Sometimes lateral controller or even the whole control module was not able to be launched successfully either, and the info displayed was just like above "process has died" without any other helpful description. I had to relaunch the module or node individually.

**Comment by mehmetdogru** [comment]
@JianKangEgon 

Thank you for the input, It might be related to the container structure and the memory allocation related to it I guess.

**Comment by maxime-clem** [comment]
### Investigation

I reproduced the issue by following the **Steps to reproduce**.
The only way (as far as I know) to debug a `ComposableNode` is with a core dump.
```bash
# enable core dump of unlimited size
ulimit -c unlimited
# add pid to file name
echo -n 1 | sudo tee /proc/sys/kernel/core_uses_pid
```
After reproducing the error, it generates a core file that can be replayed with `gdb`.
- :warning: Usually this file goes in the current folder but with the `scenario_test_runner` I am not able to find the location of the file.
- Alternative: a crash file `/var/crash/_opt_ros_galactic_lib_rclcpp_components_component_container_mt.1000.crash` was generated.
  - The crash file needs to be unpacked `apport-unpack /var/crash/_opt_ros_galactic_lib_rclcpp_components_component_container_mt.1000.crash crash_folder`.
  - The `crash_folder` then contains the `CoreDump` and other information (e.g., `ExecutablePath` with the path to the executable that crashed).
  - Now we can debug with ``gdb `cat ExecutablePath` CoreDump``.

After checking the [backtrace](https://github.com/autowarefoundation/autoware.universe/files/8866347/gdb.txt), the only issues I could find are vectors within `autoware_auto_perception_msgs::msg::PredictedPath` objects that have a larger length than capacity (`std::vector of length 2497072894800, capacity 2497072894629`) and negative length (`std::vector of length -22769416, capacity 60`).

### Solution

The [PredictedPath message definition](https://github.com/tier4/autoware_auto_msgs/blob/tier4/main/autoware_auto_perception_msgs/msg/PredictedPath.idl#L7) is currently written in IDL format with a capacity limit of `100` to its `path` field. **Removing this capacity limit and rebuilding Autoware solves the issue** and I was able to run the complete scenario without any crash.

I opened a PR to remove this capacity: https://github.com/tier4/autoware_auto_msgs/pull/32
Please test it and confirm that this fixes the issue.

**Comment by mehmetdogru** [comment]
@maxime-clem 
Thank you for the solution you proposed however that didn't work for me even though I deleted build/install/log just to be sure and checked out your branch (fix-PredictedPath-remove_capacity_limit) and re-build whole autoware repo. Yet the same issue is still there.

**Comment by maxime-clem** [comment]
Sorry for my previous post. I was too quick to claim that the issue was solved.

I have found two problems so far that cause crashes of the `behavior_path_planner`.
- `std::bad_alloc` happens when copying some messages.
   - I have not found the root cause yet but some messages seem to have impossible sizes (e.g., `std::vector of length -17545788653642, capacity -17545788653637` as reported by `gdb`).
   - Avoiding unnecessary copies help with this issue but they still sometimes occur (https://github.com/maxime-clem/autoware.universe/commit/6fe4bf7de76792fa21c36d941c66f0fffa79db2d).
   - The capacity of IDL messages may be related to this issue but I need to experiment more to confirm that.
- `vector::_M_range_check` happens when accessing pre-calculated indexes that somehow becomes out of bound.
   - For example: https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/scene_module/lane_change/util.cpp#L373-L383  
      - Indexes for elements inside `PredictedObjects::ConstSharedPtr dynamic_objects` are precalculated.
      - By the time the elements are accessed using these indexes, they can become out of bound.
   - The only explanation I can find is that the pointer is updated while the function is running, changing to a message with less elements such that some of the calculated indexes are out of bound.
   - Passing the `PredictedObjects::ConstSharedPtr` by value rather than by reference seems to solve the issue (https://github.com/maxime-clem/autoware.universe/commit/ca3b9afaf6dc0c9aafb4a0e9217c599a61d478dd) but I need to confirm that this works correctly.

These issues do not happen consistently and with my current test branch (https://github.com/maxime-clem/autoware.universe/tree/fix-issue1049-behavior_path_planner_crashes) I am sometimes able to run the full scenario without any crash.

I will keep investigating but any help or suggestion would be welcome.

**Comment by mehmetdogru** [comment]
@maxime-clem happens the same when I test [UC-PB-009-0001_Db20-Shalun](https://gitlab.com/autowarefoundation/operational-design-domains/-/blob/master/public_road_bus/UC-PB-009-0001_Db20-Shalun.yaml) as well. For the versions that I test please check [here](https://docs.google.com/spreadsheets/d/1uWpaJw68MwdCS_wysQsbG8YyG9UaYK8V00AFTd7HiVs/edit#gid=0&range=A48:L48).

**Comment by maxime-clem** [comment]
@mehmetdogru Thank you for reporting another scenario where the issue occurs.
I made a fix that should solve the issue for both scenarios: https://github.com/autowarefoundation/autoware.universe/pull/1091
