### ISSUE TITLE
Error in obstacle avoidance direction when using extended lane to avoid obstacles

### ISSUE THREAD

**Issue by shulanbushangshu** [autowarefoundation/autoware.universe#1076]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The default .yaml configuration for the extended lane in the obstacle avoidance module is shown below:
![2022-06-10 17-50-24屏幕截图](https://user-images.githubusercontent.com/102840938/173040401-eaf9ad5c-e282-4d0d-b7bb-a8b3cc2ebd45.png)
Wrong direction for obstacle avoidance when placing an obstacle in the left lane.As shown below：
![2022-06-10 17-19-17屏幕截图](https://user-images.githubusercontent.com/102840938/173040863-3aa34d46-aa8c-4bd7-a115-86cb778e0cfb.png)

When I change the default configuration：detection_area_left_expand_dist:1-->0,The above phenomena will not occur.

I think there is a problem with the code when using the extended lane for obstacle avoidance.

This phenomenon also occurs when we use relatively wide lanes (non-standard lanes) in reality

### Expected behavior

Whether extended lanes or wide lanes are used for obstacle avoidance, the direction of obstacle avoidance shall not be different.

### Actual behavior

Wrong direction for obstacle avoidance when placing an obstacle in the left lane by using default .yaml configuration for the extended lane in the obstacle avoidance module
![2022-06-10 17-19-17屏幕截图](https://user-images.githubusercontent.com/102840938/173042555-d865c130-707a-40f6-9c39-0f6722469424.png)

### Steps to reproduce

1.Start autoware planning simulator using default;
2. Set initial position and gobal position;
3.Place an obstacle vehicle in the left lane

### Versions

1.OS: Ubuntun 20.04
2.ROS2: Galactic
3.Autoware: Autoware.universe:main

### Possible causes

First, confirm whether the code supports wide lane obstacle avoidance and extended Lane obstacle avoidance.
If it is not supported for design purposes, you need to change the default configuration file:detection_area_left_expand_dist:1-->0(Or delete relevant codes).

If the design needs support, I think there is a problem in the calculation of the obstacle avoidance module.

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu 
Yes, this indeed seems like a bug on the shift point computation.
I'll investigate them and let you know once I get the results.

**Comment by shulanbushangshu** [comment]
As  show below：
![2022-06-16 15-22-27屏幕截图](https://user-images.githubusercontent.com/102840938/174016262-703714bc-6947-4835-ba7d-d336747ddce4.png)
The current obstacle avoidance strategy only considers whether the obstacle intersects with the lane boundary line; Instead of considering whether the boundary lines of obstacles and path intersect.
In my opinion, if the extended lane or wide lane is to be considered, whether the current strategy needs to be changed.

In order to adapt to the extended lane, the calculation method of obstacle avoidance offset distance may need to be changed too.
The current offset distance method is as follows:
![2022-06-16 15-44-46屏幕截图](https://user-images.githubusercontent.com/102840938/174019330-ddff41e9-15fd-415a-ad7f-cba957b35bb8.png)

@zulfaqar-azmi-t4 @taikitanaka3 
have any ideas

**Comment by zulfaqar-azmi-t4** [comment]
As the mitigation, I was thinking of querying the whether the object overlaps with the object and if it not overlapping, the the object was ignore.

Currently the collision check might be a bit off. So I am investigating the proper solution to it.

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu
Hi, currently I'm using the following logic as the mitigation, but I am interested in knowing in case you have any concerns. Basically if the shift is shorter that the distance to the object, then we can safely ignore them.

![ignoring_shift_point drawio](https://user-images.githubusercontent.com/93502286/174160489-a56ce78d-54f4-4dc6-aabe-fef64b0c4721.png)
