### ISSUE TITLE
Describe the origin of pre-trained models

### ISSUE THREAD

**Issue by miursh** [autowarefoundation/autoware.universe#1087]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

As mentioned [here](https://github.com/autowarefoundation/autoware/discussions/2653), TIER IV member should describe the details of provided ML models.

### Purpose

Clarify what kind of dataset was used for training. 

### Possible approaches

Write the following information.

* If trained on a private dataset, at least some information on the nature of the data (e.g. camera images from Japanese traffic lights, lidar data from urban traffic in Europe...)
* training/testing set size, number of objects by types, etc
* test accuracy

### Definition of done

Complete the description of the following 5 nodes
- [x] https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_apollo_instance_segmentation
- [x] https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_centerpoint
- [x] https://github.com/autowarefoundation/autoware.universe/tree/main/perception/traffic_light_ssd_fine_detector
- [x] https://github.com/autowarefoundation/autoware.universe/tree/main/perception/tensorrt_yolo
- [x] https://github.com/autowarefoundation/autoware.universe/tree/main/perception/traffic_light_classifier

**Comment by miursh** [comment]
Update for tensorrt_yolo https://github.com/autowarefoundation/autoware.universe/pull/1339

**Comment by ktro2828** [comment]
For lidar_appllo_instance_segmentation, there is already description of model in README.md

**Comment by yukke42** [comment]
The document of centerpoint has updated in <https://github.com/autowarefoundation/autoware.universe/pull/2553>.

**Comment by yukke42** [comment]
All of the task has completed.
