### ISSUE TITLE
`<arg>` is overwritten when including multiple launch files because `<include>` does not scope

### ISSUE THREAD

**Issue by h-ohta** [autowarefoundation/autoware.universe#1160]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

We probably have same issue as https://github.com/ros2/launch/issues/620.

### Purpose

We have to fix above issue to avoid unexpected error in the future.

### Possible approaches

add `<group>` tag around `<include>` tag is better.

### Definition of done

Now, I only confirm and fix in tier4_xxx_launch directory.
- [x] tier4_autoware_api_launch
- [ ] tier4_control_launch
- [x] tier4_integration_launch
- [x] tier4_localization_launch
- [x] tier4_perception_launch
- [x] tier4_planning_launch
- [ ] tier4_sensing_launch
- [ ] tier4_simulator_launch
- [x] tier4_system_launch
- [ ] tier4_vehicle_launch

**Comment by angry-crab** [comment]
If there is only one `include` in a launch file, is `group` tag still necessary?

**Comment by angry-crab** [comment]
Recreated PRs
https://github.com/autowarefoundation/autoware.universe/pull/1235
https://github.com/autowarefoundation/autoware.universe/pull/1236
https://github.com/autowarefoundation/autoware.universe/pull/1237
https://github.com/autowarefoundation/autoware.universe/pull/1238
https://github.com/autowarefoundation/autoware.universe/pull/1239
https://github.com/autowarefoundation/autoware.universe/pull/1240

**Comment by h-ohta** [comment]
> If there is only one include in a launch file, is group tag still necessary?

Sorry for late reply. It would be better.

**Comment by angry-crab** [comment]
All related PRs are merged. I think we can close this issue. The unchecked packages are good.

**Comment by h-ohta** [comment]
I've confirmed. LGTM

**Comment by h-ohta** [comment]
@angry-crab Thank you for your cooperation!
