### ISSUE TITLE
In planning simulation, panel cannot send engage signal to vehicle

### ISSUE THREAD

**Issue by brian841102** [autowarefoundation/autoware.universe#1168]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In the planner simulation, only using terminal command to send engage signal can start the vehicle.
The AutowareStatePanel Button is malfunctioning.

### Expected behavior

When **Engage** Button was pressed, the vehicle started to move.

### Actual behavior

When **Engage** Button was pressed, the vehicle do not move.
AutowareStatePanel shows WAITING_FOR_ROUTE.
ad_service_state_monitor shows “MAP msg is not ready yet”
<img width="1475" alt="截圖 2022-06-25 16 36 25" src="https://user-images.githubusercontent.com/30545391/175778483-f8ff69ae-7819-447e-b28f-a07e160fc0ee.png">

<img width="901" alt="截圖 2022-06-25 16 50 02" src="https://user-images.githubusercontent.com/30545391/175778489-775eae86-7596-4311-b017-218d6f283e0c.png">

### Steps to reproduce

1. `ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/Downloads/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit
`
2. add AutowareStatePanel
3. set initial pose & set goal pose
4. Press engage button on the panel

### Possible causes

ad_service_state_monitor cannot subscribe to the vector_map.

**Comment by shmpwk** [comment]
This issue came from my commit. 
https://github.com/autowarefoundation/autoware.universe/pull/1153/files#diff-f092ba8cc68e325209a916a7446c37e3efb13e03313408d4461d05287542367eR462-R464

Thank you for notifying me.

**Comment by brian841102** [comment]
> This issue came from my commit. https://github.com/autowarefoundation/autoware.universe/pull/1153/files#diff-f092ba8cc68e325209a916a7446c37e3efb13e03313408d4461d05287542367eR462-R464
> 
> I apologize my lacking of check and thank you for your contribution.

Not a big deal, don't mind.
I am new to the community and autoware.universe.
Although this is a small fix, this is also my first contribution.
I am pleased to do so and look forward to engaging more in the future.

**Comment by kenji-miyake** [comment]
@brian841102 Thank you for your first contribution! :smile: 
And thank you @shmpwk @wep21 @maxime-clem for your quick support. :heart: 
I feel the Autoware community is getting better. :blush:
