### ISSUE TITLE
How much should we adjust "Autoware.auto packages" to the "Tier4" acceptance criteria?

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#117]
So far some packages area back porting from autoware.auto so we should change as minimal as possible, so we don't apply these changes.

- [ ] pre-commit (ignore for temporary)
- [ ] add sample launch file (each packages should have sample launch file)
- [x] pass Gtest
- [x] readme.md

below should be added?
- [ ] add sample launch file (each packages should have sample launch file)

**Comment by kenji-miyake** [comment]
IMO, finally pre-commit and sample launch file are applied, but it can be ignored in the porting stage and will do it later.
