### ISSUE TITLE
Is it OK to have TODO comment in PR code?

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#118]
as PR title description.

**Comment by kenji-miyake** [comment]
I think it's okay, but it should be reviewed as much as possible.

**Comment by maxime-clem** [comment]
The template for merge requests in .Auto has checkboxes for:
>  Review any // TODO item added in the MR that can be addressed without the reviewer's help

and
>  Any added source-code comment about future work refers to a follow-up GitLab issue explicitly; e.g., // TODO #551 refactor code below

I think this is a good practice.
