### ISSUE TITLE
Fix legacy timer creation

### ISSUE THREAD

**Issue by wep21** [autowarefoundation/autoware.universe#120]
https://github.com/tier4/autoware.iv/pull/2302

![image](https://user-images.githubusercontent.com/31987104/144793686-41f20758-75f0-4c4d-9175-4676a8e56b5e.png)

**Comment by kenji-miyake** [comment]
@wep21 Please let me assign this issue to you. :pray:

**Comment by kenji-miyake** [comment]
@wep21 Will you work on this?

**Comment by wep21** [comment]
@kenji-miyake I finished the work on the PR above. I appreciate it if you could review it.
