### ISSUE TITLE
Wrong Drivable Area might be created for behavior path planner

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#1207]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

 - cv::fillpoly sometimes does not cover area where there is an overlapping polygon
https://github.com/autowarefoundation/autoware.universe/blob/791fd51ea0d43df2796fac8d00df770c67ffd5be/planning/behavior_path_planner/src/utilities.cpp#L1161

see ref)
https://github.com/taikitanaka3/cpp_snippets/issues/1

![image](https://user-images.githubusercontent.com/65527974/176820152-4c4ec719-3091-46ad-9759-ddf296ce3296.png)

### Expected behavior

fill poly can fill the area which has overlapping area 

### Actual behavior

However sometimes cv::fillpoly can't cover overlapping area

### Steps to reproduce

tbd.

**Comment by shmpwk** [comment]
It seems Open CV cannot avoid even-odd rule, and thus some people seems SVG [polyline](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline).
https://github.com/opencv/opencv/issues/5256#issuecomment-954321603

**Comment by taikitanaka3** [comment]
I am going to close this issue because this case is already handled in avoidance module
