### ISSUE TITLE
Problem in merging obstacle avoidance points under the distribution of some obstacles

### ISSUE THREAD

**Issue by shulanbushangshu** [autowarefoundation/autoware.universe#1258]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

There are problems in merging obstacle avoidance points under the distribution of some obstacles.
As shown in the figure below, the debug information shows the merged obstacle avoidance offset points. The original obstacle avoidance points have 6 points, which have been merged into 5 points, but the return point (length=0) is between two obstacles (the interval between these two obstacles is very small).
![obstacle](https://user-images.githubusercontent.com/102840938/177527838-792bf8bc-fa3f-4a4d-8242-cfb1fe2ee2e1.png)
![zero_shift_obstacle](https://user-images.githubusercontent.com/102840938/177528518-3a2b04d7-69cd-477c-b29c-9106786abf02.png)

### Expected behavior

The return point (length=0) between two obstacles should not exist and should be merged

### Actual behavior

The original obstacle avoidance points have 6 points, which have been merged into 5 points, but the return point (length=0) is between two obstacles (the interval between these two obstacles is very small).

### Steps to reproduce

1.Start autoware planning simulator using default;
2. Set initial position and gobal position;
3.Set two obstacles(like car)(Two obstacles are close to each other) 

### Versions

1.OS: Ubuntun 20.04
2.ROS2: Galactic
3.Autoware: Autoware.universe:main

**Comment by taikitanaka3** [comment]
@shulanbushangshu 
Could you explain expected behavior in this case?
avoidance module uses path shifter which is common in path change module.
and if obstacle is close length  can be zero.

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu 
Just curious, why does this issue is set as closed/completed?
Appreciate it if you could add some notes so that if other users stumble across similar issue, then the notes will be very helpful for them.

**Comment by shulanbushangshu** [comment]
The current issue cannot be reproduced.I will continue to confirm it.In the above picture, there is indeed a problem with the merging of offset points
