### ISSUE TITLE
image_projection_based_fusion fails to build on machines without CUDA.

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#1304]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

image_projection_based_fusion fails to build on machines without CUDA.

### Expected behavior

The package build successfully.

### Actual behavior

Build fails with the following error:
```
CUDA_TOOLKIT_ROOT_DIR not found or specified
CUDA NOT FOUND
TensorRT is NOT Available
CUDNN is NOT Available
CMake Error at /opt/ros/galactic/share/ament_cmake_export_dependencies/cmake/ament_export_dependencies.cmake:29 (message):
  ament_export_dependencies() must be called before ament_package()
Call Stack (most recent call first):
  /opt/ros/galactic/share/ament_cmake_auto/cmake/ament_auto_package.cmake:58 (ament_export_dependencies)
  CMakeLists.txt:177 (ament_auto_package)
```

### Steps to reproduce

1. Run installation steps on machines without GPU. https://autowarefoundation.github.io/autoware-documentation/main/installation/

(You can still reproduce the error with CUDA installed machines by changing the `if` conditions in the CMakeLists.txt to `FALSE`)

### Versions

- OS: Ubuntu 22.04
- ROS: Humble
- Autoware: https://github.com/autowarefoundation/autoware/tree/humble

### Possible causes

I have checked the CMakeLists.txt and noticed that if you don't have CUDA:
* `ament_auto_package()` is called twice (in [L161](https://github.com/autowarefoundation/autoware.universe/blob/e7f09a8fc1a5a3fd49aa5c27164a0324a6f84e9a/perception/image_projection_based_fusion/CMakeLists.txt#L161) and [L177](https://github.com/autowarefoundation/autoware.universe/blob/e7f09a8fc1a5a3fd49aa5c27164a0324a6f84e9a/perception/image_projection_based_fusion/CMakeLists.txt#L177))
* some [nodes](https://github.com/autowarefoundation/autoware.universe/blob/e7f09a8fc1a5a3fd49aa5c27164a0324a6f84e9a/perception/image_projection_based_fusion/CMakeLists.txt#L167) tries to refer to the [library](https://github.com/autowarefoundation/autoware.universe/blob/e7f09a8fc1a5a3fd49aa5c27164a0324a6f84e9a/perception/image_projection_based_fusion/CMakeLists.txt#L125) that is only built when CUDA is available
* pointpainting_fusion_node, which relies on CUDA, is registered outside `if` condition

**Comment by kenji-miyake** [comment]
@mitsudome-r Resolved by #1306? If so, as you might know, it's good to write like `Resolves #1304` in the PR.
