### ISSUE TITLE
CMOS battery monitoring

### ISSUE THREAD

**Issue by nobuotakamasa** [autowarefoundation/autoware.universe#1452]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

I would like to add a function to raise the soundness of CMOS batteries to diagnostics.

### Purpose

PC have a CMOS battery to store the state of the BIOS and to run the RTC. When the battery is exhausted, the contents of the BIOS will be erased and the RTC will be reset.
If it happens, the BIOS will be initialized at each boot.
The following problems occur.
- The BIOS settings are erased.
- It takes time to start the PC.
- The RTC time is incorrect.
To avoid the above problems, provide a function to raise the CMOS battery status to diagnostics.

### Possible approaches

The default policy is to get the result of "cat /proc/driver/rtc".
As an optional is to get the result of lm-sensors.
Depending on the PC, lm-sensors can be used to monitor the voltage of CMOS batteries.
The default operation is OK, but monitoring with lm-sensors allows you to replace the battery before it runs out completely. 
It is recommended because you can avoid the risk of sudden battery exhaustion.

### Definition of done

Being able to reflect the battery status in diagnostics.

**Comment by ito-san** [comment]
This issue was fixed in https://github.com/autowarefoundation/autoware.universe/pull/1989. I'm closing this issue.
