### ISSUE TITLE
Bus ODD specific features

### ISSUE THREAD

**Issue by BonoloAWF** [autowarefoundation/autoware.universe#1468]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

As part of the Bus ODD, the vehicle is required to approach a bus stop, stop within the designated area whilst passengers embark/disembark, and then continue along the route. 

This functionality needs to be added to Autoware.Universe. 

### Purpose

To discuss the scope of Bus ODD specific features for both of the upcoming demos

### Possible approaches

Possible approaches are summarised in this discussion: https://github.com/orgs/autowarefoundation/discussions/2651
and the comments below.

### Definition of done

The bus can handle bus stops, passengers entering/exiting the bus and there is a suitable user interface.

**Comment by BonoloAWF** [comment]
cc: @mitsudome-r @MertClk @hueirutseng @xmfcx @HaoruXue 
Meeting minutes from AWF/ITIR/LeoDrive meeting held on 10 August 2022:
1. Timelines for bus ODD
- ITRI bus will be tested on campus in September, post vehicle integration 
- LeoDrive internal project final tests and demo are in September. The LeoDrive bus will be available for the AWF demo until 31 December 2022
- AWF - the bus ODD demos will start in early December 

2. Handling bus stops
- Route scheduling and bus stops will be handled on the server side - each bus stop will have a unique pose associated with it, each new goal is set via this external service (no modifications to the planner)
- Ryohsuke will investigate whether the existing TierIV tool can be used for the demo
- If the TierIV tool is not available for use, a similar tool will be implemented by AWF
- The bus will stop at every bus stop along the route 
- 
4. Handling passenger embarking/disembarking
5. Bus user interfaces

**Comment by MertClk** [comment]
**ISUZU Bus Displays**

Below, I'm sharing displays and panel existing on our bus. We can use them to inform environment and passengers. 

1. Front Destination Display  
![20220810_125838](https://user-images.githubusercontent.com/15357471/183883543-c83965ac-a8e7-4038-849d-4edf0cbb2763.jpg)

2. Right Side Destination Display
![WhatsApp Image 2022-08-10 at 1 45 50 PM](https://user-images.githubusercontent.com/15357471/183883711-bc93ba95-033f-4062-80b9-bb02381504c3.jpeg)

3. Interior Destination Display 
![20220810_130043](https://user-images.githubusercontent.com/15357471/183883803-dd9aa6c1-a51c-4aca-bc43-fb5c03e204fd.jpg)

4. Driver Control Panel
![20220810_125950](https://user-images.githubusercontent.com/15357471/183884415-358f7151-4f02-4af4-9277-114ffb217f0a.jpg)

**Comment by hueirutseng** [comment]
ITRI Bus Display 
1. Front display will show "Autonomous Bus" 
    
![image](https://user-images.githubusercontent.com/101175763/184047232-9f4fe411-28cc-48ea-adf7-bb5266aa037e.png)

2. Interior display for passengers

![image](https://user-images.githubusercontent.com/101175763/184047625-b7ed6168-20ee-438b-b41a-5920e8fc3010.png)

3. Interior display for test driver

![image](https://user-images.githubusercontent.com/101175763/184047919-eb159f88-c79f-4d2b-af6b-162018379f5b.png)

You might also refer to a demo video showing the idea that ITRI autonomous bus operated on public roads.
[https://drive.google.com/file/d/1ngEqr8b8FmQi4Xb1Ri4C52ffHogG2Slf/view?usp=sharing]

**Comment by BonoloAWF** [comment]
All information has been provided. Closing.
