### ISSUE TITLE
Create a new common package for TensorRT

### ISSUE THREAD

**Issue by yukke42** [autowarefoundation/autoware.universe#1505]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Since some perception packages implement TensorRT libraries independently, new updates or features are implement for each package. I want to create a new package of TensorRT for the easy managements.

### Purpose

for the easy managements

### Possible approaches

create a new common package

### Definition of done

Complete the description of the following 5 nodes

- [ ]  https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_apollo_instance_segmentation
- [ ]  https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_centerpoint
- [ ]  https://github.com/autowarefoundation/autoware.universe/tree/main/perception/traffic_light_ssd_fine_detector
- [ ]  https://github.com/autowarefoundation/autoware.universe/tree/main/perception/tensorrt_yolo
- [ ]  https://github.com/autowarefoundation/autoware.universe/tree/main/perception/traffic_light_classifier

**Comment by miursh** [comment]
@yukke42 Are there any tasks left to do for this?

**Comment by yukke42** [comment]
I will close this issue, since I don't have time for it.
