### ISSUE TITLE
Add safety slow down feature for specific crosswalks

### ISSUE THREAD

**Issue by mehmetdogru** [autowarefoundation/autoware.universe#1523]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Related discussion: https://github.com/orgs/autowarefoundation/discussions/2767

With the current implementation of crosswalk module, ego vehicle doesn't slow down for crosswalks unless there are target objects around it. However for some use cases as stated below slowing down for some crosswalks where there are **no traffic lights either for pedestrians or vehicles**, makes sense:

- Streets near school exists or campus areas where extra precaution needs to be taken since unpredictable and sudden pedestrian behaviors can be observed 

- Narrow roads and occluded perception output ( Even though there is `occlusion_spot`  module in `behavior_velocity_planner`, I guess it is still experimental) 

### Purpose

Slowing down for some user specified crosswalks for safety reasons.

### Possible approaches

An implementation which would affect only user-selected crosswalk's behavior can be done by adding some tags in crosswalk annotation in lanelet2_map and making necessary changes in `crosswalk` module:

```xml
<relation id='34378' visible='true' version='1'>
    <member type='way' ref='34374' role='left' />
    <member type='way' ref='34377' role='right' />
    <tag k='subtype' v='crosswalk' />
    <tag k='safety_slow_down_speed' v='3.0' />
    <tag k='safety_slow_down_distance' v='2.0' />
    <tag k='type' v='lanelet' />
</relation>
```

_safety_slow_down_speed_ in `[m/s]`
_safety_slow_down_distance_ in `[m]`

### Definition of done

- [x] Read related crosswalk tags from lanelet2_map
- [x] Implement slow down behavior so that ego would drive at a constant speed on specified crosswalks
- [x] Test the feature with different maps and crosswalks
- [ ] Update readme
- [ ] Update lanelet2_extension doc

**Comment by mitsudome-r** [comment]
Could you create PR for additional tags supported by Autoware? https://github.com/autowarefoundation/autoware_common/blob/main/tmp/lanelet2_extension/docs/lanelet2_format_extension.md
