### ISSUE TITLE
bug scenario_test_runner speed limit doesn't work

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1524]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I created several scenarios with the scenario editor. these scenarios had speed limit iterations. I tried to ensure that the speed of the vehicle is fixed at 10, 20 and 30 km / h. However, I could not achieve this. Even though I ran the same scenario without changing anything, the vehicle sometimes stayed true to the speed limit I set, but in some cases it did not. I tried the scenarios from  [ODD Repository](https://gitlab.com/autowarefoundation/operational-design-domains/-/tree/master/public_road_bus) as I thought I might have created the scenarios that I created incorrectly. but still faced the same problems. 

### Expected behavior

```
   ControllerAction:
     AssignControllerAction:
       Controller:
         name: ''
         Properties:
            Property:
             - name: maxSpeed
                value: $vel
```
The above section belongs to the file of the scenario. ` value: $vel `  represents the maximum speed of the EGO. EGO must stick to the specified speed limit.

### Actual behavior

EGO does not stick to the specified speed limit. If there is a speed limit specified on the lanelet map, EGO accomplish it, otherwise it goes up to 72 km/h.

### Steps to reproduce

1. Edit this command according to you and run 
```
ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle \
scenario:=path/your/scenario \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true
```
2. Observe vehicle velocity.

### Versions

- OS: Ubuntu20.04
- autoware.universe
- ROS2

### Additional context

As you can see I run same senario several times but  the speed limit was different every time.

![Screenshot from 2022-08-01 11-43-26](https://user-images.githubusercontent.com/32412808/182966444-0e0963cf-8797-40b7-8c43-8014fc9f3707.png)

![Screenshot from 2022-08-01 11-44-00](https://user-images.githubusercontent.com/32412808/182966555-f5af5892-e2fa-4ddc-845b-dc5791724bb6.png)

And also I added a senario file. You can try this one. 

**I converted yaml file to text so I can upload.  Before run this scenario you have to change file extension to .yaml**

[UC-PB-001-0006-Hsinchu.txt](https://github.com/autowarefoundation/autoware.universe/files/9267043/UC-PB-001-0006-Hsinchu.txt)

**Comment by beyzanurkaya** [comment]
setting  speed limit works commit 970f5172929b9bd25e6d34103965a65753ee1245.

**Comment by beyzanurkaya** [comment]
This problem is caused by scenario_simulator_v2. I created this issue in scenario_simulator_v2. You can check [here](https://github.com/tier4/scenario_simulator_v2/issues/856)

**Comment by xmfcx** [comment]
This issue belongs to https://github.com/tier4/scenario_simulator_v2/issues/856 so, closing it here.
