### ISSUE TITLE
the implementation of sigmoid()  in lidar_centerpoint package is not right

### ISSUE THREAD

**Issue by WfHit** [autowarefoundation/autoware.universe#1545]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The implementation of sigmoid()  in lidar_centerpoint package is not right. The current implementation will return value greater than 1, and cause a lot of false positives.

### Expected behavior

__device__ inline float sigmoid(float x) { return 1.0f / (1.0f + expf(-x)); }

### Actual behavior

__device__ inline float sigmoid(float x) { return 1.0f / expf(-x); }

### Steps to reproduce

sigmoid() is defined at 50 line in postprocess_kernel.cu

**Comment by miursh** [comment]
@yukke42 Could you please confirm this?

**Comment by yukke42** [comment]
@WfHit Thank you for your kind feedback. Cloud you make a PR to fix this bug?

**Comment by WfHit** [comment]
OK, I will fix it as soon as possible
