### ISSUE TITLE
Some .md files have preview problems

### ISSUE THREAD

**Issue by mehmetdogru** [autowarefoundation/autoware.universe#1568]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Usage of `<figure markdown>` and `<figcaption>` tags in some .md files like shown below causes visual problems since it is not parsed correctly.

```html
<figure markdown>
  ![example](docs/crosswalk/example.png){width=1000}
  <figcaption>crosswalk module</figcaption>
</figure>
```

![md_tag_issue](https://user-images.githubusercontent.com/48479081/183919444-8584f7a5-ee84-40e4-a542-f8217c984e43.png)

The files have this problems are:

- [crosswalk-design.md](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/crosswalk-design.md)
- [stop-line-design.md](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/stop-line-design.md)
- [detection-area-design.md](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/detection-area-design.md)
- [virtual-traffic-light-design.md](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/virtual-traffic-light-design.md)
- [obstacle_stop_planner/README.md](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/obstacle_stop_planner/README.md)

### Expected behavior

The pictures should be visible

### Actual behavior

The pictures are not visible.

### Steps to reproduce

1. Go to any page addressed in the description [e.g.](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/crosswalk-design.md)
2. Observe that there are some pictures are not visualized. (Check raw code [e.g.](https://raw.githubusercontent.com/autowarefoundation/autoware.universe/main/planning/behavior_velocity_planner/crosswalk-design.md))

### Possible causes

Usage of  `<figure markdown>` and `<figcaption>` tags in md files

**Comment by mehmetdogru** [comment]
@xmfcx @kenji-miyake Could you take a look at this?

**Comment by kenji-miyake** [comment]
@mehmetdogru The docs aren't for GitHub preview but MkDocs Material.
They use this feature: https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions

For now, could you see https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_velocity_planner/crosswalk-design/ instead?
![image](https://user-images.githubusercontent.com/31987104/184048657-6e5487ba-dc04-4966-be68-c1c4282831d1.png)

However, we can consider improving the notations to support both GitHub and MkDocs Material.

**Comment by kenji-miyake** [comment]
cc @satoshi-ota Please comment on this if you have any ideas. :pray:

**Comment by satoshi-ota** [comment]
[background]

Previously, I tried to align center by using html tags as follows, but it is not able to shown in [github.io pages](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_velocity_planner/crosswalk-design/) because of incorrect converting of the relative image path. As far as I know, if we use html tags as follows, the absolute paths parse like `/autoware.universe/planning/behavior_velocity_planner/crosswalk-design/docs/crosswalk/hoge.svg` and includes unnecessary directory `crosswalk-design`. So, I use Mkdocs Material.

```md
<div align="center">
  <img src="docs/crosswalk/hoge.svg">
</div>
```

**Comment by xmfcx** [comment]
Is it possible to have link in the universe .md pages to the corresponding universe documentation? Maybe created by the tool that creates documentation?

**Comment by kenji-miyake** [comment]
@xmfcx I think it's possible with `mkdocs-macros`. Just write `{{ page }}` and add some conversion.
https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/

![image](https://user-images.githubusercontent.com/31987104/184846665-2aa0dc0c-76ba-4ca1-9b8c-1990e1a9e530.png)

**Comment by kenji-miyake** [comment]
Ah, no. We can't write it in Markdown files. lol
Sorry, forget about it.

**Comment by kenji-miyake** [comment]
So, I think the only way is to write the documentation URL manually, but it takes some effort.

**Comment by mitsudome-r** [comment]
@mehmetdogru Are there any issues remaining in this issue? If not, I will close this issue.

**Comment by xmfcx** [comment]
Using https://autowarefoundation.github.io/autoware.universe/main/ it should be ok, I will close this issue.
