### ISSUE TITLE
Checking only 4 corners in the drivable area

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1716]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

When checking whether the footprint of EGO is within the drivable area in `obstacle_avoidance_planner`, only the 4 corners of EGO checked. However, it was observed that although these 4 corners were within the drivable area, footprint of EGO was outside the drivable area.

![Screenshot from 2022-08-31 16-27-41](https://user-images.githubusercontent.com/32412808/187690744-0b811849-7e23-4411-93b1-2d9af9b9d97c.png)

### Steps to reproduce

1. Download [1716.zip](https://github.com/autowarefoundation/autoware.universe/files/9469628/1716.zip)
2. Download isuzu_vehicle_launch in [here]( https://drive.google.com/drive/folders/1bkxamrkKsbP3J5339GVf5yKhJL0iii4l)
3. Put isuzu_vehicle_launch in autoware.universe/vehicle directory and compile this package with `colcon build`
4. Change pcd and lanelet2 maps file path in yaml file
5. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=isuzu_vehicle \
scenario:=/scenario/path/1716.yaml \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

6. Add ` /planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/marker` topic and check mpt_footprint in rviz

7. When you run the scenario, you'll see 4 corners are inside drivable area but body of footprint is outside drivable area.

### Purpose

Making sure that the entire footprint of vehicle is in the drivable area.

### Possible approaches

Calculating the intersection of the drivable area and footprint of EGO with boost.intersection

### Definition of done

- [ ] Calculate the intersection of the drivable area and  footprint of EGO.
- [ ] Implemented in the `isOutsideDrivableAreaFromRectangleFootprint` function.
- [ ] Test

**Comment by takayuki5168** [comment]
@beyzanurkaya Right. We have to fix two packages.
- 1. obstacle avoidance planner
    - calculates the path (where the path does not start from the ego pose as shown in your figure)
    - and check if the calculated path is within the road or not.
- 2. lane departure checker
    - subscribes the predicted path from the lateral controller
    - and check if the predicted path (which starts from the ego pose) is within the road or not.

In your figure, the issue comes from 2. The planned path is within the road, but the predicted path, which was not shown in your figure though, is outside the road.

**Comment by beyzanurkaya** [comment]
You're right. I updated description and figure.

**Comment by mitsudome-r** [comment]
@mehmetdogru @beyzanurkaya Do you have any updates? If you are busy with bus integration, that's okay. I just want to know the status :)

**Comment by beyzanurkaya** [comment]
I actually started working on this. I tried to create a boost polyon by finding the contours of the drivable area.  Then I used boost intersection. But the result was not what I expected. Intersection output was empty.

**Comment by takayuki5168** [comment]
@beyzanurkaya 
Just in case, let me comment that
Obstacle avoidance planner, which is in motion planner, can read not lanelet but drivable area as an image. Therefore, do you mean you create boost polygon from an image (drivable area)? I'm worrying a bit about the calculation cost to create boost polygon from an image and calculate intersection via boost.

> But the result was not what I expected. Intersection output was empty.

Please be careful about the rule of boost polygon if you don't know. The order of points of polygon (clockwise or counterclockwise) is determined, and if you create polygon with points in the opposite order, the intersection calculation may fail.

**Comment by mitsudome-r** [comment]
@beyzanurkaya Do you have any blockers for this issue/PR?

**Comment by beyzanurkaya** [comment]
No, there is no blocker. I did the things in my head and pushed but the intersection result is zero for some reason. I compared the data of the footprint and the drivable area and they contain numerically similar points. 

Here's what I did:
- I converted the OccupancyGrid to grid map and then cv_image
- I found the contour in cv_image and assigned it to a boost polygon
- I assigned the footprint to a boost polygon
- I found their intersection with boost intersection.
At this point, the intersection result is zero.

**Comment by takayuki5168** [comment]
boost polygon's points has order (clockwise or anti-clockwise), and if the order is the opposite, the intersection calculation will fail.
This implementation may be helpful.
https://github.com/autowarefoundation/autoware.universe/blob/main/common/tier4_autoware_utils/src/geometry/boost_polygon_utils.cpp

**Comment by mitsudome-r** [comment]
@takayuki5168 The [PR](https://github.com/autowarefoundation/autoware.universe/pull/1999) seems to be ready for review. Could you review it or assign someone who's capable of reviewing it?
