### ISSUE TITLE
some packages use only vehicle_width/2

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1734]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

When calculating the corners of the vehicle, half the width of the vehicle is used as the y point.. This will only work correctly when `left_overhang` and `right_overhang` are equal. Using this formula on non-symmetrical vehicles can lead to many miscalculations.

### Purpose

Correct calculation of the vehicle's points on the y-axis

### Possible approaches

When finding the vehicle's position on the y-axis; `vehicle_width = track_widht + left_overhang + right_overhang`. 
`y = vehicle_width/2` formula is used. but when calculating its position on the y-axis; 
`y = -(right_overhang + (track_width/2))` and `y = left_overhang + (track_width/2)` formulas should be used.

### Definition of done

- [ ] Change y position calculation in ` cv_utils.cpp`
- [ ] Change y position calculation in `run_out/scene.cpp`
- [ ] Change y position calculation in `occlusion_spot/occlusion_spot_utils.cpp`
- [ ] Test

**Comment by mehmetdogru** [comment]
assign @hasanzfdn

**Comment by mehmetdogru** [comment]
assigned to [@hasanzfdn](https://github.com/hasanzfdn)

**Comment by hasanzfdn** [comment]
I would like to work on this issue
