### ISSUE TITLE
Duplicate topic names used for different message types

### ISSUE THREAD

**Issue by NorahXiong** [autowarefoundation/autoware.universe#1927]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I failed to echo topic "/planning/mission_planning/route" with the latest code. The hint is as below.
![image](https://user-images.githubusercontent.com/103234047/191481703-110bf93c-595f-4ad3-bb69-17e5270b02c3.png)

### Expected behavior

Topic can be normally echoed.

### Actual behavior

A topic can not be echoed.

### Steps to reproduce

1. Update code(I'm at 47c77c705a405f7ea89ee6ec79ba5eae8da17b8f).
2. Start autoware planning simulator.
3. Echo topic "/planning/mission_planning/route"

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: Autoware.universe:main

### Possible causes

As the hint indicates, there are more than one topic use the name "/planning/mission_planning/route".

**Comment by kenji-miyake** [comment]
@NorahXiong Thank you for reporting this issue. It was due to the intermediate state of Autoware AD API tasks. We're sorry about that.
Takagi-san has applied a temporary patch for this: https://github.com/autowarefoundation/autoware.universe/pull/1928
