### ISSUE TITLE
`obstacle_avoidance_planner` sometimes crash when the vehicle goes beyond goal point

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#1930]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Several times today, the obstacle_avoidance_planner crashed in my vehicle. With GDB, I identified that `full_traj_points` trajectory below is sometimes empty:
https://github.com/autowarefoundation/autoware.universe/blob/e2c5eda7524ff11bab791f9c6ac19c884a3c314d/planning/obstacle_avoidance_planner/src/node.cpp#L1355

I modified the code like so, and the node stopped crashing:
```c++
  const auto full_traj_points =
    points_utils::concatTrajectory(optimized_traj_points, extended_traj_points);

  if (full_traj_points.empty()) {
    trajectory_points = points_utils::convertToTrajectoryPoints(path_points);
    return trajectory_points;
  }

  // NOTE: fine_traj_points has no velocity information
  const auto fine_traj_points = generateFineTrajectoryPoints(path_points, full_traj_points);
```

(however I have no idea if it is the correct way to handle that.)

### Expected behavior

No crash

### Actual behavior

Crash

### Steps to reproduce

Seems to happen when the vehicle goes beyond goal point (in manual driving)

**Comment by takayuki5168** [comment]
@VRichardJP Thank you so much for your bug report and suggestion for bug fix.
I agree with your suggestion. Could you make a PR?

**Comment by VRichardJP** [comment]
I would be happy to contribute. But is this workaround the good way to handle that situation?

For example a special case for empty trajectories could be added to `generateFineTrajectoryPoints()` instead.

**Comment by takayuki5168** [comment]
@VRichardJP Hmm, I'm not 100% sure, but check-and-validate as follows looks better to me.

```cpp
 const auto full_traj_points =
    points_utils::concatTrajectory(optimized_traj_points, extended_traj_points);

  if (full_traj_points.empty()) {
    trajectory_points = points_utils::convertToTrajectoryPoints(path_points);
    return trajectory_points;
  }
```

**Comment by xmfcx** [comment]
@VRichardJP could you create a PR for this with your changes? So we can try to address your problems there.

**Comment by VRichardJP** [comment]
The vehicle I had the problem with has been updated with a newer version of the code since then. Even though I did not keep my change after the update, I have never faced the problem again. So I guess it has been fixed somehow?
