### ISSUE TITLE
Rename package name for messages for AutowareArchitectureProposal packages

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#2]
Currently, names of the messages used for Autoware Architecture Proposal packages could overlap with AutowareAuto msgs.
We will replace the package name with unique packages name (e.g. t4_planning_msgs) after all the merging of packages are done.

**Comment by tkimura4** [comment]
https://github.com/autowarefoundation/autoware.universe/blob/a330c08a9e3e20748bf36d488bd3a70a7c142ab4/messages/README.md
Readme may need to be changed according to this change.

**Comment by tkimura4** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/150

**Comment by tkimura4** [comment]
PR merged.
