### ISSUE TITLE
Support Docker development environment

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware.universe#204]
To provide an easy-to-develop environment, we should support Docker.

The base of Dockerfile is introduced here.
https://github.com/tier4/AutowareArchitectureProposal.proj/tree/main/docker

Also, Autoware.Auto has Dockerfile for `ade`.
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/tools/ade_image/Dockerfile

**Comment by kenji-miyake** [comment]
To be able to build not only `autoware.universe` but also the entire workspace including drivers, tools, and etc., I think it's better to put Dockerfile into the meta-repository.

So I'll wait for we'll set up https://github.com/autowarefoundation/autoware.

For example, we need CUDA, TensorRT, and PyTorch for Universe for now, even though they might be replaced by TVM in the future.
https://github.com/tier4/AutowareArchitectureProposal.proj/tree/main/ansible/roles

**Comment by kenji-miyake** [comment]
This Docker image can be used in the CI of `autoware.universe`. Currently, it uses `ros:galactic`, but since it doesn't have CUDA, the Perception packages are not built.

**Comment by kenji-miyake** [comment]
Implemented the first version in https://github.com/autowarefoundation/autoware/pull/14.

**Comment by IshitaTakeshi** [comment]
I'd suggest some features to add:
* The execution procedure. How to launch autoware and play rosbag
* Mount files to the host environment. It should be easier to modify files on the host environment rather than on a container

**Comment by kenji-miyake** [comment]
> The execution procedure. How to launch autoware and play rosbag

Will be covered by https://github.com/autowarefoundation/autoware-documentation/issues/8.

> Mount files to the host environment. It should be easier to modify files on the host environment rather than on a container

I wrote a document in this PR.
https://github.com/autowarefoundation/autoware/pull/14

**Comment by IshitaTakeshi** [comment]
Thank you!
