### ISSUE TITLE
Trajectory follower: Memory leak

### ISSUE THREAD

**Issue by smorita-esol** [autowarefoundation/autoware.universe#2047]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Trajectory follower seems to have memory leaks when it runs as a node of The Planning Simulator Demo below.  
```
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/  
```

### Expected behavior

Memory consumption(RSS) of the process to which trajectory follower node belongs falls within a certain amount.

### Actual behavior

Memory consumption(RSS) of the process to which trajectory follower node belongs falls within a certain amount.
Actual behavior:
The memory consumption of the process continuously increases up to over 1GBytes as below.  
![chart](https://user-images.githubusercontent.com/32567894/195046671-f30b33ec-cb1f-43bd-b3eb-8d39d981a0a1.png)

### Steps to reproduce

1. Follow the instructions of the Planning Simulator Demo above, using the docker image below.
    ```
    humble-20220915-amd64:           00e518e86ad3f9a38378f6ab28db48fecce69b75
    ```  
    To measure the memory consumption only of the process to which the trajectory follower belongs, you should modify the launch file to contain the trajectory follower node independently in a component container.
2. Launch the Planning simulator demo.
3. Proceed the steps till "4. Set a goal pose for the ego vehicle"    
    Set the vehicle on an arbitrary position as below.
  
![posed_vehicle](https://user-images.githubusercontent.com/32567894/195046764-658e7103-2af7-4b48-beaf-a53faaa6035f.png)

 
4. Monitor the memory consumption of the separated component container.

### Versions

OS: Ubuntu 22.04 + Docker environment  
ROS2: Humble included in the docker image   humble-20220915-amd64  
Autoware: the one in the docker image above.  

### Possible causes

It seems to be caused by some C++ code of the trajectory follower.  

### Additional context

None

**Comment by VRichardJP** [comment]
Sorry to jump in.
By looking at [`csc_matrix` implementation](https://github.com/osqp/osqp/blob/master/src/cs.c#L12), the memory leak seems simple to explain from your valgrind logs:
- `csc_matrix()` allocate new memory, which should be freed by the user
- in [`initializeProblem()`](https://github.com/autowarefoundation/autoware.universe/blob/f234a7d9ae044e0f53a3679060dad08aab5ec90e/common/osqp_interface/src/osqp_interface.cpp#L264), the `csc_matrix()` function is called twice to overwrite `m_data->P` and `m_data->A` pointers, so any old data that was previously held by those pointers is now lost.

**Comment by maxime-clem** [comment]
Thanks a lot @VRichardJP for finding the cause of the issue.
I will prepare a PR with the fix you suggested.
