### ISSUE TITLE
[map_height_fitter] Improve height estimation logic

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2048]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

With the current implementation of [`get_ground_height`](https://github.com/autowarefoundation/autoware.universe/blob/4e080d2c05da5b1a0356c1ec16ae3c77676914f7/localization/pose_initializer/src/map_height_fitter/map_height_fitter_core.cpp#L46) , when the user sets the initial pose using Rviz, if the initial pose is not within 1 meter of any map point, the `map_height_fitter` node will fail to estimate its height. Most likely, the initial localization will be wrong.

That situation typically occurs when the vehicle is located in some garage or building, whose inside has not mapped. Like here:
 
![IMG_20221011_163404](https://user-images.githubusercontent.com/18645627/195047251-551a5319-2b88-4203-8007-e96aba93fbca.jpg)

![IMG_20221011_163505](https://user-images.githubusercontent.com/18645627/195047264-656b73a8-3414-4917-91e0-85c00e81f067.jpg)

Likely, the issue would also occur if the 3D map has no ground (I don't know if it is a thing)

### Purpose

Improve the reliability of the height estimator.

### Possible approaches

Obviously, the hardcoded 1.0 meter radius search makes the implementation not very flexible. 

I think that simply increasing the radius search would have some undesirable side effects.

One simple improvement would be to consider all point within r+1.0 radius, where r is the distance to the closest point. This way we make sure we always find a bunch of points, yet we don't look unecessarily far.

The only downside I see is that it takes slightly more time, since we explore the map twice (once to find the closest point, another time to find min height within radius r+1.0)

Any other suggestion?

### Definition of done

Pose height estimation give a "decent" estimation even when there is no map point very close.

**Comment by YamatoAndo** [comment]
> One simple improvement would be to consider all point within r+1.0 radius, where r is the distance to the closest point. This way we make sure we always find a bunch of points, yet we don't look unecessarily far.

I think it is a good idea!

**Comment by YamatoAndo** [comment]
> The only downside I see is that it takes slightly more time, since we explore the map twice (once to find the closest point, another time to find min height within radius r+1.0)

I think it is not problem if we explore the map twice, since dynamic map loading will be implemented soon and the area where the map is loaded will be smaller than before.
https://github.com/orgs/autowarefoundation/discussions/2812

**Comment by isamu-takagi** [comment]
@YamatoAndo @VRichardJP 
I think it is unreliable if there is no ground under the vehicle area. Here is an example. If the ground is sloped or stepped, the radius calculated from the closest point is not helpful. Moreover, the inside of the garage given as an example will give erroneous results if there is a ceiling when measured from the outside. Therefore, initialization results cannot be guaranteed at locations where the ground is not measured.

![map-height-fit](https://user-images.githubusercontent.com/43976882/195343919-46b4936b-64c4-4f43-a215-300752a09ca8.png)

**Comment by VRichardJP** [comment]
I totally understand the proposed change is not perfect, but I still think it is better than the current implementation. 

In particular, I don't think there is a case where it perform worse than the current implementation. Typically, for both examples you provided, there is no point within a 1 meter radius, so the returned height would be whatever Z value is currently stored in the input pose (most likely wrong?)

**Comment by isamu-takagi** [comment]
Ah, I see. Both the old and new logic fail in these cases, but the new one improves some cases.
