### ISSUE TITLE
gnss_poser does not parse MGRS zone correctly

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2085]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In [GNSSStat](https://github.com/autowarefoundation/autoware.universe/blob/main/sensing/gnss_poser/include/gnss_poser/gnss_stat.hpp), there is no support for MGRS zone (e.g. "53SPU"). There is a `int zone` which can be used for utm zone, but MGRS would need a string.

Yet, in the `UTM2MGRS` function, the MGRS zone (e.g. "53SPU") is converted to `int` using `stod`:
https://github.com/autowarefoundation/autoware.universe/blob/d5db3ac254529f4fdd92847c836e9de147fa1f96/sensing/gnss_poser/include/gnss_poser/convert.hpp#L146

There are 2 problems with this piece of code:
1. since zone is a int, it is strange to use `stod` instead not `stoi`
2. `std::stod("53SPU")` returns `53.0`, which looses the second part of the code `SPU`

Although the value `mgrs.zone` is not used elsewhere in gnss_poser, it could cause some issue in the future.

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to reproduce

N/A

**Comment by YamatoAndo** [comment]
@VRichardJP Thank you for the report.
You are right, there are problems with this code.
Can you please issue a PR?
