### ISSUE TITLE
planning sometimes fails when using RRT* for parking

### ISSUE THREAD

**Issue by TakaHoribe** [autowarefoundation/autoware.universe#2099]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

planning fails when driving in parking lots with `rrtstar` algorithm in the `freespace_planner`.

The solved trajectory by the `freespace_planner` is visualized as in the picture below, but the output from the `motion_velocity_smoother` is not visualized.

![image](https://user-images.githubusercontent.com/21360593/196435704-8819eaa1-c1f3-4914-9caf-71e77db45dc9.png)

Attach the terminal output for further information.
![image](https://user-images.githubusercontent.com/21360593/196436347-bcb24afb-4a6e-4572-983f-0d71147c0d30.png)

### Expected behavior

arrive at a goal with `rrtstar` algorithm in parking scenario.

### Actual behavior

planning fails and it won't arrive at a goal

### Steps to reproduce

1. change the default param in freespace_planner from `astar` to `rrtstar`
2. set a goal to in the parking lot and run in the parking scenario

**Comment by TakaHoribe** [comment]
no one is assigned now

**Comment by shulanbushangshu** [comment]
I test the "rrtstar" in the parking.The  path display planning is successful, but the trajectory of motion_velocity_smoother display wrong is in the process of control. Simulation of the video as follows:

![Screenshot from 2022-11-10 16-57-02](https://user-images.githubusercontent.com/102840938/201046553-a0f333fd-edf5-4f62-852b-73c9f0508141.png)



https://user-images.githubusercontent.com/102840938/201040744-436d0277-f2e3-4782-9256-b000b19c9f85.mp4
