### ISSUE TITLE
Remove unnecessary messages from Tier IV's proposal messages

### ISSUE THREAD

**Issue by 1222-takeshi** [autowarefoundation/autoware.universe#21]
Check the dependency and remove unnecessary messages that are replaced by autoware_auto_msgs from messages.

- [x] autoware_control_msgs
- [x] autoware_vehicle_msgs
- [x] autoware_perception_msgs
- [x] autoware_planning_msgs
- [x] autoware_system_msgs
- [x] autoware_lanelet2_msgs

**Comment by kenji-miyake** [comment]
Also, the naming should be refined. For example, to `t4_planning_msgs`, `tier4_*_msgs` or so.

**Comment by 1222-takeshi** [comment]
message type that may still be used.
To be removed.

- [ ] autoware_perception_msgs/object_recognition/DynamicObject.msg
- [ ] autoware_perception_msgs/object_recognition/DynamicObjectArray.msg
- [ ] autoware_perception_msgs/object_recognition/PredictedPath.msg
- [ ] autoware_perception_msgs/object_recognition/Semantic.msg
- [ ] autoware_perception_msgs/object_recognition/Shape.msg
- [ ] autoware_perception_msgs/object_recognition/State.msg
- [ ] autoware_planning_msgs/LaneChangeCommand.msg (maybe unnecessary)
- [ ] autoware_planning_msgs/LaneChangeStatus.msg (maybe unnecessary)
- [ ] autoware_vehicle_msgs/BatteryStatus.msg
