### ISSUE TITLE
Enable OpenCL Backend for TVM

### ISSUE THREAD

**Issue by angry-crab** [autowarefoundation/autoware.universe#2186]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Currently, we don't have a working opencl pipeline with tvm. As discussed in #1898, vulkan backend cannot be used because of an unknown accuracy issue and llvm does not provide enough performance for deep learning inference. Either cuda or opencl has to be enabled. 

### Purpose

We need to enable opencl backend so that tvm packages could be actually used. 

### Possible approaches

- [x] Compile the models for opencl. In theory it is only a matter of adding opencl here: https://github.com/autowarefoundation/modelzoo/blob/9529c71e73df637448f6fceb203fa793f3a3b064/scripts/tvm_cli/validation/tvm_cli_test.py#L19, then it gets picked up by the CI.
- [x] Enable opencl in the runtime package by modifying this file: https://github.com/autowarefoundation/tvm_vendor/blob/main/config.cmake.gpu.patch, and then waiting for the package to be tagged and released.
- [x] Making sure the correct opencl dependencies are installed in the Autoware docker image / that they can be installed easily for source installs.

### Definition of done

Being able to run tvm packages using opencl.

**Comment by angry-crab** [comment]
Related TVM issues/PR:
#1988 #2185 
#908 #1898

**Comment by angry-crab** [comment]
A simple verification of compiled opencl models indicates accuracy issues exist with output channel `heatmap` and `vel` of `pts_backbone_neck_head_centerpoint.onnx`.
```
# heatmap
(1, 3, 560, 560)
(1, 3, 560, 560)
[0.0001049  0.00010109 0.0001297  ... 0.00014496 0.000103   0.00011253]
1375

# vel
(1, 2, 560, 560)
(1, 2, 560, 560)
[0.00010395 0.0001142  0.00010109 0.00011301]
4
```

**Comment by ambroise-arm** [comment]
Are you still using the same setup as in https://github.com/autowarefoundation/autoware.universe/pull/1898#issuecomment-1293085900? Using it for the backbone outputs, with `np.ones((40000,32,9), dtype=np.float32)` as an input, I don't see any difference delta above 0.0001 with opencl (or vulkan). Changing the threshold to 0.00001 there are differences, but then I also see differences with an llvm backend.

**Comment by angry-crab** [comment]
> Are you still using the same setup as in [#1898 (comment)](https://github.com/autowarefoundation/autoware.universe/pull/1898#issuecomment-1293085900)? Using it for the backbone outputs, with `np.ones((40000,32,9), dtype=np.float32)` as an input, I don't see any difference delta above 0.0001 with opencl (or vulkan). Changing the threshold to 0.00001 there are differences, but then I also see differences with an llvm backend.

For backbone network, the input shape has to be changed. It's (1, 32, 560, 560) I think. 
![backbone](https://user-images.githubusercontent.com/93699235/200222540-4d6f1e0b-f93e-43eb-8f32-f15ef749ea55.png)

**Comment by angry-crab** [comment]
[add opencl backend to ci](https://github.com/autowarefoundation/modelzoo/pull/79)

**Comment by ambroise-arm** [comment]
@angry-crab Yes, sorry I had copied and pasted the wrong line here, but I was using the correct input shape in my script.
I confirm that I don't see deltas when using `np.ones`, but I do when using `np.zeros`. Although only on `vel`. Both vulkan and opencl give me:
```
[0.0001049  0.00011146 0.00014421 0.00010443 0.0001049  0.0001266 0.00011784 0.00010717 0.00010872 0.00011826 0.00012851 0.00014114 0.00012398]
13
```
And llvm gives me:
```
[0.00010467]
1
```

Is there a reason you are using ones as input to the encoder and zeros as input to the backbone?

**Comment by angry-crab** [comment]
> Is there a reason you are using ones as input to the encoder and zeros as input to the backbone?

Not really. It seems the accuracy is hardware dependent. Let's see how much it affects the detection.

**Comment by angry-crab** [comment]
@ambroise-arm
As for the third mark, since `tvm_vendor` depends on `opencl`, the image should be good if correct version of `tvm_vendor` is installed, isn't it?

**Comment by ambroise-arm** [comment]
Oh, absolutely! I hadn't thought about that.

**Comment by angry-crab** [comment]
![opencl](https://user-images.githubusercontent.com/93699235/201048163-e631a63b-a950-4a95-9133-055344a067c1.png)
Did a quick test on `opencl`, it seems to work.

**Comment by ambroise-arm** [comment]
Nice! Was that locally or inside of a docker image?
Because I think there are `.icd` files that will be missing inside a docker image. `mesa-opencl-icd` would need to be installed when using an AMD GPU, and `echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd` would need to be issued for an NVIDIA GPU. Probably the same way we do here: https://github.com/autowarefoundation/autoware/blob/5fba5a1e35921470d02711f19bec19b29ab08139/docker/autoware-universe/Dockerfile#L45 for Vulkan.

**Comment by angry-crab** [comment]
> Nice! Was that locally or inside of a docker image? Because I think there are `.icd` files that will be missing inside a docker image. `mesa-opencl-icd` would need to be installed when using an AMD GPU, and `echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd` would need to be issued for an NVIDIA GPU. Probably the same way we do here: https://github.com/autowarefoundation/autoware/blob/5fba5a1e35921470d02711f19bec19b29ab08139/docker/autoware-universe/Dockerfile#L45 for Vulkan.

Yes! I was using a docker image and `echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd` is required.

**Comment by angry-crab** [comment]
It seems that `tvm_vendor` will be released on November 21, 2022 (Chicago) for humble. 
[Humble Release](https://discourse.ros.org/t/preparing-for-humble-sync-and-patch-release-2022-11-21/28234)

**Comment by angry-crab** [comment]
Humble packages are still being held. Not sure why.

**Comment by angry-crab** [comment]
Humble package is merged! [tvm_vendor](https://github.com/ros/rosdistro/pull/35276)

**Comment by angry-crab** [comment]
The only issue left is that tvm_vendor in the existing docker images are not update to date.

**Comment by angry-crab** [comment]
@ambroise-arm 
As a follow-up issue of GPU backend, shall we enable cuda as well? According to a performance comparison survey. opencl is 13% ~ 67% slower than cuda.

**Comment by ambroise-arm** [comment]
There is an issue with doing that in practice. The way the TVM runtime works, it expects all the dependencies it was built with to be available when used. So if we compile [tvm_vendor](https://github.com/autowarefoundation/tvm_vendor) with `set(USE_CUDA ON)`, the user will need to have the nvidia cuda library available in order for the inference to work, even if the user just wants to do non-cuda inference.
At least that is the way it was about a year ago, last time I looked at it.

It is not a problem for vulkan and opencl backends because there are mesa packages available that provide the corresponding libraries.

**Comment by angry-crab** [comment]
> It is not a problem for vulkan and opencl backends because there are mesa packages available that provide the corresponding libraries.

I see. But if cuda is installed then we can safely add `set(USE_CUDA ON)` and compile tvm runtime. I think maybe we should provide a different cmake setting for cuda.

**Comment by angry-crab** [comment]
OpenCL is correctly setup in the latest cuda docker image. We can close this issue.
