### ISSUE TITLE
Diagnostics with no corresponding node

### ISSUE THREAD

**Issue by 0x126** [autowarefoundation/autoware.universe#221]
There are no nodes that output these diagnostics in this repository or in any other public repository.
Don't these need to be removed or commented out?

https://github.com/autowarefoundation/autoware.universe/blob/tier4/proposal/system/system_error_monitor/config/diagnostic_aggregator/control.param.yaml#L69-L81

https://github.com/autowarefoundation/autoware.universe/blob/tier4/proposal/system/system_error_monitor/config/diagnostic_aggregator/map.param.yaml#L17-L25

**Comment by kenji-miyake** [comment]
Generally, regarding diagnostic_aggregator configs, I think no need to remove them because we can adjust whether to watch them in `autoware_error_monitor.param.yaml`.

But since we don't use `map_version` for now, we can remove it now and re-consider the name when it's added.

**Comment by 0x126** [comment]
Thank you for your comment, I created a PR.
