### ISSUE TITLE
add configurable lateral_distance for different target objects

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#2222]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

The ego vehicle uses a single `lateral margin` when avoiding obstacles, but this is sufficient when avoiding vehicles, but the ego may drive very close to pedestrians.

https://user-images.githubusercontent.com/32412808/200497034-a211ea32-3685-48f0-b185-223a7f27c156.mp4

https://user-images.githubusercontent.com/32412808/200245269-b84c0708-7dde-4c34-82d4-e1b548c2e22c.mp4

### Purpose

to provide driving safer while obstacle avoidance of ego vehicle

### Possible approaches

using different lateral margins for each obstacle type

### Definition of done

- [ ] Try and check obstacle_cruise_planner as an alternative
- [ ] Provide the ego vehicle to avoid different types of obstacles with different lateral margins.

**Comment by mitsudome-r** [comment]
@beyzanurkaya started working on PR this week.
