### ISSUE TITLE
Refactor conditional ROS_DISTRO_GALACTIC include with __has_include

### ISSUE THREAD

**Issue by ralwing** [autowarefoundation/autoware.universe#2235]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Replace 
```
#ifdef ROS_DISTRO_GALACTIC
```
with
```
#if __has_include
```
where applicable

### Purpose

This will release code from environmentall variables and also make it more readable and easier to configure, and still galactic/humble compatible.

### Possible approaches

Refactor code

### Definition of done

All conditional includes replaced with suggested change.

**Comment by kenji-miyake** [comment]
Wrote my concerns here: https://github.com/autowarefoundation/autoware.universe/pull/2236#issuecomment-1305785887

> This will release code from environmentall variables and also make it more readable and easier to configure,

@ralwing Could you explain the reason why you felt so? I feel it's not clear.
