### ISSUE TITLE
Autoware does not check for collision on the vehicle actual trajectory

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2252]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Today, I observed autoware does not want to stop for an obstacle right in front of the ego vehicle if everything happens outside the path.

I guess a screenshot is worth a thousand words (situation reproduced with the planning simulator):
![Screenshot from 2022-11-08 20-22-23](https://user-images.githubusercontent.com/18645627/200577835-b38e284a-a802-4f4d-9f48-19fc43de3935.png)

R.I.P
![Screenshot from 2022-11-08 20-26-36](https://user-images.githubusercontent.com/18645627/200577825-639a9ce0-dc08-46d1-b9dd-4a1547e584c5.png)

### Expected behavior

Autoware should not hit obstacles on its trajectory

### Actual behavior

Better not be a human in a simulation.

### Steps to reproduce

See the screenshot

**Comment by brkay54** [comment]
You can enable [obstacle_collision_checker](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/launch/planning_simulator.launch.xml#L13) to check collision on `predicted_trajectory`. It should solve your problem.

**Comment by VRichardJP** [comment]
Wow! That's life saving!

I'll try it.

**Comment by VRichardJP** [comment]
If I understand correctly, the node should create a diagnostic error if there is something on the predicted trajectory? Then with the right configuration, autoware should trigger emergency when this happens, correct?

I have backported the latest `control.launch.py` to my tree to add the `obstacle_collision_checker`. When I start autoware, I can see the module is running and is generating diagnostics. 

I have reproduced my first screenshot scenario with a golf cart and traffic cones. However, in that situation, the diagnostic is always "OK". Even when the cone is right in front of the car (and detected as obstacle) the collision checker still generates "OK" diagnostics.

**Comment by brkay54** [comment]
Hmm I see, I tried too but module created "ERROR" diagnostic if there is an object in braking distance. But after vehicle stops, you will see "OK" because object is not in braking distance of vehicle (because velocity of vehicle is 0). 

https://user-images.githubusercontent.com/45468306/201379224-7a4f2a7b-325e-4587-8135-231810bdb6a5.mp4

Btw, it will not trigger the emergency, to do this, we should add it in `diagnostic_aggregator` and system_error_monitor.param.yaml to be taken into account by `emergency_handler`. Because it is optional, we did not add it.

**Comment by VRichardJP** [comment]
If the speed is taken into account, isn't there a risk the module will say "OK" when the vehicle is stopped right in front of the obstacle? then even with the emergency handling, autoware would restart, then stop, then restart, etc?

**Comment by brkay54** [comment]
To avoid this, you can enable [emergency_holding](https://github.com/autowarefoundation/autoware.universe/blob/b6f68a5b9f79fe09f38293e6622d92fd8bcbd73b/launch/tier4_system_launch/launch/system.launch.xml#L59). If there is a problem, emergency will be true until you clear the emergency. 

But you are right, `obstacle_collision_checker` is just for emergency situations. Planning should also check the `predicted_trajectory` for obstacle stop. I am going to work on this if it is okey for you as well.

**Comment by satoshi-ota** [comment]
@brkay54 @VRichardJP There's another similar discussion, so could you check [this](https://github.com/autowarefoundation/autoware/discussions/2859), and continue the discussion in there if necessary?

**Comment by xmfcx** [comment]
Yes, this issue is being tracked in https://github.com/autowarefoundation/autoware/discussions/2859

Please continue there.
