### ISSUE TITLE
Add new lateral margin to `obstacle_stop_planner` to handle cut-in scenario in adaptive cruise control 

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2262]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Currently, the lateral margin of the stop planner (or slow down planner if enabled) is used to define the detection range of the adaptive cruise control module. 

Since the lateral margin of stop planner is meant to be quite small (0.0 by default), the ACC can't see what is going on outside our lane. As a consequence, the ego vehicle brakes strongly every single time a new vehicle cuts into our lane.

It seems that this problem could be solved by using a bigger margin for ACC (something like ~5 meters). In the current state, there is no choice but to increase the stop planner or slow down planner lateral margin, which of course would have some undesirable side effects.

However, I have tested the following trick:
- enable slow down planner
- set slow down planner lateral margin to 5.0
- set slow down velocity to very high value, like 20m/s (so that there is no slow down)

With this settings, the ACC seems to adapt nicely to other vehicles, even when they first enter our lane. Of course, the consequence is that I cannot use the slow down planner as it is originally intended.

### Purpose

For ACC to handle other vehicle changing lane.

### Possible approaches

Add new lateral margin parameter to configure ACC obstacle detection range.

### Definition of done

- When another vehicle moves to our lane, the ACC kicks in immediately and no hard braking occurs (like for static obstacles)

**Comment by satoshi-ota** [comment]
Hi @VRichardJP Thanks for your idea :+1: 
As you know, the current `obstacle_stop_planner` does not have rich features for cut-in scenarios.

On the other hand, we TIER IV working on developping new planner `obstacle_cruise_planner` that is richer than the old one and supports cut-in scenario. If you want to try it, you have to set the following parameter `cruise_planner` as `obstacle_cruise_planner`.

Note: the obstacle_cruise_planner based on not pointcloud but object recognition result. ([docs](https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_cruise_planner/))

https://github.com/autowarefoundation/autoware.universe/blob/1940b876700a7fe414603a8659387db72ce72b1e/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py#L337-L339

**Comment by xmfcx** [comment]
@VRichardJP would you like to try `obstacle_cruise_planner` or prefer to contribute to `obstacle_stop_planner`?

**Comment by VRichardJP** [comment]
The current hack I have been using so far is good enough for me. So if everyone plans to use `obstacle_cruise_planner` in a near future I don't see the point into updating the `obstacle_stop_planner`.
