### ISSUE TITLE
[CI] build-and-test-differential only tests CUDA

### ISSUE THREAD

**Issue by ambroise-arm** [autowarefoundation/autoware.universe#2409]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The `build-and-test-differential` workflow only starts a runner with cuda enabled: https://github.com/autowarefoundation/autoware.universe/blob/03de605b0998e9a9ee623f9a74a7002f4d2b61a4/.github/workflows/build-and-test-differential.yaml#L17
This prevents catching issues on systems that don't have cuda enabled.
For example https://github.com/autowarefoundation/autoware.universe/pull/2370 successfully passed CI, but failed once merged: https://github.com/autowarefoundation/autoware.universe/actions/runs/3583250712/jobs/6028456850

### Expected behavior

CUDA shouldn't be required to build Autoware

### Actual behavior

The CI for PRs doesn't check that.

### Steps to reproduce

Build current tip of main (03de605b0998e9a9ee623f9a74a7002f4d2b61a4) on a system without cuda.

**Comment by ambroise-arm** [comment]
cc @kenji-miyake

**Comment by kenji-miyake** [comment]
@ambroise-arm Actually, it was intentionally removed temporarily.
https://github.com/autowarefoundation/autoware.universe/pull/1669

After we move to Humble and remove Galactic CI workflows by https://github.com/autowarefoundation/autoware.universe/pull/2408, I believe we can re-enable no-cuda checks.

**Comment by kenji-miyake** [comment]
Ah, sorry. I misunderstand your problem. Will fix my comment above.

**Comment by kenji-miyake** [comment]
Okay, I think my comment wasn't so wrong.

> CUDA shouldn't be required to build Autoware

I believe it's not true. We need CUDA for now because `autoware.universe` depends on CUDA yet.
But the no-cuda environment should also be tested.

@ambroise-arm What do you think?

**Comment by ambroise-arm** [comment]
I believe your comment gives valuable information as it is.
Is the re-enablement of the no-cuda checks tracked somewhere? If not we could keep this open until it is done.

**Comment by kenji-miyake** [comment]
I'll create a revert PR and relate this issue.

**Comment by ambroise-arm** [comment]
> > CUDA shouldn't be required to build Autoware

> I believe it's not true.

I understand that cuda is necessary to have the runtime functionality of Autoware. But I strongly believe that it should be possible to built without it.
For example https://github.com/autowarefoundation/autoware.universe/blob/03de605b0998e9a9ee623f9a74a7002f4d2b61a4/perception/lidar_apollo_instance_segmentation/CMakeLists.txt#L12 has a different behavior whether cuda is present on the system or not, and doesn't fail if it's not.

> I'll create a revert PR and relate this issue.

What about the problems from https://github.com/autowarefoundation/autoware.universe/pull/1669, won't that just get us back to that?
