### ISSUE TITLE
Change traffic signal interface to support V2X/V2I

### ISSUE THREAD

**Issue by isamu-takagi** [autowarefoundation/autoware.universe#2567]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Hi, I'm thinking about V2X support in traffic signal interface. Currently, the planning component (traffic_light module in behavior_velocity_planner) has two traffic signal inputs, `perception` and `external`. It looks like we can input V2X information into `external`, but it was actually created for the purpose of overriding vehicle behavior by the operator. So this interface means the operator's decision such as pass and stop rather than the traffic signal color such as green or red, and the pass throuh logic described [here](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_velocity_planner/traffic-light-design/#limitations) is not performed.

![traffic-signal-discuss-old](https://user-images.githubusercontent.com/43976882/209082189-7cca5098-5f42-4fcf-95cf-0abeca4b8c56.png)

### Purpose

For the planning component, it doesn't matter if the input is image recognition results or V2X. Therefore, I'll unify the input so that V2X can be handled in the same way as image recognition results.

### Possible approaches

The new architecture is as follows. Merge the image recognition results and V2X before inputting into the planning component. Typically the merge node will use V2X if it is available, otherwise it will use the most confident image recognition result. Also, as described later, light bulbs and traffic signals are treated separately.

The messages LightBulbsArray (or NewTrafficLightArray) and NewTrafficSignalArray (temporary name) are almost the same as TrafficSignalArray, except for the use of light bulbs ID and regulatory element ID. Or NewTrafficSignalArray could be changed to more semantic information such as `{straight: green, turn_right: red}`.

![traffic-signal-discuss-new](https://user-images.githubusercontent.com/43976882/209082209-57159f1f-f71b-40f9-b4ce-32c50a2d3e75.png)

### Map primitive IDs

There are multiple signals (as equipment) at one intersection, and image recognition targets them. On the other hand, V2X and the planning component only need one traffic signal (as information) in each direction of the intersection. This is defined in lanelet as light_blubs way ID and regulatory_element relation ID. See [here](https://github.com/autowarefoundation/autoware_common/blob/main/tmp/lanelet2_extension/docs/lanelet2_format_extension.md#trafficlights) for details of lanelet format.

![traffic-signal-lanelet](https://user-images.githubusercontent.com/43976882/209090070-04015bbd-5897-468d-b49a-418453a29607.png)

### Definition of done

- [x] Add new interface message.
- [x] Change the perception output interface.
- [ ] Change the planning input interface.
- [x] Create the V2X output interface.
- [x] Create the merge node from perception to planning.

**Comment by TakaHoribe** [comment]
>For the planning component, it doesn't matter if the input is image recognition results or V2X. Therefore, I'll unify the input so that V2X can be handled in the same way as image recognition results.

I totally agree. The approach looks good to me as well.

**Comment by isamu-takagi** [comment]
@TakaHoribe Thank you. I would like to proceed with this proposal.

As a first step, create the autoware_perception_msgs package in [autoware_msgs](https://github.com/autowarefoundation/autoware_msgs) and define a message type as follows. Note that I changed the definition of traffic signal and traffic light. If there are other good words to distinguish between these, please let me know.

| Type | Current implementation | Related lanelet ID |
| ---- | ---- | ---- |
| TrafficSignal.msg | none | Relation ID (type: regulatory_element) |
| TrafficLight.msg | TrafficSignal.idl | Way ID (type: traffic_light)  |
| TrafficLightElement.msg | TrafficLight.idl | Node ID if possible |

**Comment by isamu-takagi** [comment]
I've created a PR to add messages.
https://github.com/autowarefoundation/autoware_msgs/pull/48

**Comment by yukkysaito** [comment]
cc @Mingyu1991 @miursh

**Comment by isamu-takagi** [comment]
The migration steps are as follows.

![traffic-signal-migration](https://user-images.githubusercontent.com/43976882/224015438-2a6ce263-d6b9-4202-9315-bc1d4c5fc1e5.png)

**Comment by yukkysaito** [comment]
@isamu-takagi The diagram above is a bit old, so the actual roles and such will be different.
@Mingyu1991 @miursh Could you share the updated figure?

**Comment by Mingyu1991** [comment]
@yukkysaito 
Do you mean this figure?
![image](https://user-images.githubusercontent.com/115005477/224590027-286bdc66-2196-4cca-bfa7-7416aefcbad2.png)

@isamu-takagi 
There would be two merge nodes within perception.
The "traffic_light_merger" would merge the results of the same traffic light from different cameras.
The "traffic_signal_arbitrator" would merge the results of traffic lights from the same group.

**Comment by isamu-takagi** [comment]
Thank you. Updated the diagram.

**Comment by isamu-takagi** [comment]
Step 1 is done. https://github.com/autowarefoundation/autoware.universe/pull/2903

**Comment by KhalilSelyan** [comment]
@isamu-takagi Any updates ?

**Comment by isamu-takagi** [comment]
@KhalilSelyan 
I asked the maintainers of each package to implement it. I hear they are working on it now.
- @TomohitoAndo  for planning (step 2)
- @TomohitoAndo @Mingyu1991 for perception (step 3, 4)

**Comment by isamu-takagi** [comment]
Update the step 4 diagram to split merge step by targets. An implementation can perform multiple merge steps on the same node.
![traffic-signal-step4](https://github.com/autowarefoundation/autoware.universe/assets/43976882/3003f82d-ee5b-4430-a58d-63426205b2f2)

**Comment by isamu-takagi** [comment]
I noticed that `TrafficLight.msg` is converted to `TrafficSignal.msg` in perception, and only `TrafficSignal.msg` is used for interface between components. So I will remove `TrafficLight.msg`.

**Comment by miursh** [comment]
Merged perception update https://github.com/autowarefoundation/autoware.universe/pull/4050 https://github.com/autowarefoundation/autoware.universe/pull/4125 https://github.com/autowarefoundation/autoware.universe/pull/4176

This is the latest perception node diagaram.

![traffic_light_node_diagram drawio](https://github.com/autowarefoundation/autoware.universe/assets/37187849/118b4da7-7d11-4795-91b7-b0e641e7b04e)

**Comment by miursh** [comment]
@TakaHoribe @TomohitoAndo @isamu-takagi 
Let me just check one thing. Are all works in this issue already done?

**Comment by isamu-takagi** [comment]
@miursh I think so.
@TakaHoribe @TomohitoAndo @Mingyu1991 Are there any remaining tasks?

**Comment by TomohitoAndo** [comment]
@isamu-takagi @miursh 
The changes for the planning modules haven't been merged yet. ([This PR](https://github.com/autowarefoundation/autoware.universe/pull/4133))
The review for this PR is already done, but scenario simulator doesn't support the new interface yet, so we are waiting for it.
It's scheduled to be done by next week.

**Comment by TomohitoAndo** [comment]
Support for V2X in the scenario simulator has been delayed until early September. Thus, the PR for the planning modules is on hold until then.

**Comment by miursh** [comment]
Changing the node order of crosswalk_estimator
https://github.com/autowarefoundation/autoware.universe/pull/4734

**Comment by TomohitoAndo** [comment]
@isamu-takagi @miursh @TakaHoribe 
The changes for the planning modules have been merged, so I close this issue.
https://github.com/autowarefoundation/autoware.universe/pull/4133
