### ISSUE TITLE
Anonymizing faces and license plates for privacy-preserving

### ISSUE THREAD

**Issue by batuhanbeytekin** [autowarefoundation/autoware.universe#2569]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

In autoware.universe, faces and license plates are not anonymized for privacy-preserving.

### Purpose

Anonymization of faces and license plates to ensure data privacy

### Possible approaches

Read all topics from the bag file and then blur the only image topics. After that write a new bag file that changed new blurred image topics and has the same topics as the previous bag.

### Definition of done

- [ ] Reading bag file with sequential reader
- [ ] Update image topics in bag file with blurred

**Comment by xmfcx** [comment]
Thanks a lot for working on this tool, it's going to help us a lot for collecting and sharing data! ૮ ˶ᵔ ᵕ ᵔ˶ ა

It's better to create this kind of tool in its own separate repository. And we can link it in the documentation.

We can put it under the https://github.com/autowarefoundation organization too.

Please contact me over discord for more details.

**Comment by miursh** [comment]
@batuhanbeytekin @xmfcx 
I have been working on kind of anonymizing tool for human's faces and license plates.
Please let me know if there is any discussion about this.

**Comment by batuhanbeytekin** [comment]
Hi @miursh,
Thanks for your reply, you can find the [discussion](https://github.com/orgs/autowarefoundation/discussions/3169) under the autowarefoundation
