### ISSUE TITLE
occlusion spot: remaining TODOs

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#258]
below is remaing TODOs
1. better interpolation using original path behind ego #290
2. consider using lanelet info to filter unnecessary possible collision.
3. fix velocity of spline interpolation #290
4. consider safe margin before collision point https://github.com/autowarefoundation/autoware.universe/pull/344
5. consider detection area of passable/impassable collisiopn. https://github.com/autowarefoundation/autoware.universe/pull/354

below is bug fix
https://github.com/autowarefoundation/autoware.universe/pull/351

**Comment by mitsudome-r** [comment]
@taikitanaka3 Do you still have any remaining issues? If not, please close the issue.

**Comment by taikitanaka3** [comment]
feature implementation is done so i can close this
