### ISSUE TITLE
Add a validation node for the planning trajectory

### ISSUE THREAD

**Issue by TakaHoribe** [autowarefoundation/autoware.universe#2605]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Sometimes, a faulty path is published due to the poor quality of the planning. This can cause the vehicle to behave abnormally in terms of steering, acceleration, and braking. It is important to continually improve the quality of the planning, but we also need to implement a validation system to ensure the quality of the paths being published.

### Purpose

To avoid publishing abnormal paths.

### Possible approaches

A planning validator node is introduced at the final stage of the planning process. The node validates the trajectory and stops publishing if it is invalid.

The planning node diagram would be like below:
`planning_modules` -> `planning_validator` -> `control`.

![image](https://user-images.githubusercontent.com/21360593/210234510-00bc5aa7-69a5-47ec-b058-afd251332b40.png)

### Definition of done

A validation mechanism of the planning is in the autoware.

**Comment by TakaHoribe** [comment]
Related:

- https://github.com/autowarefoundation/autoware.universe/pull/1947
- https://github.com/autowarefoundation/autoware.universe/pull/2604
- https://github.com/tier4/autoware_launch/pull/675

**Comment by TakaHoribe** [comment]
cc. @yukkysaito

**Comment by yukkysaito** [comment]
I think it's a good idea to add one.
However, I would like to separate what is verified online and what is verified offline (like CI)
Otherwise, it would be inefficient to run a huge verification online.

**Comment by TakaHoribe** [comment]
> to separate what is verified online and what is verified offline (like CI)

Ok. In the first phase, the validator node focus only on the online checks (curvature, acceleration, etc). The offline validation item could be something regarding the map, kinematics parameters, etc. We should discuss this further.

**Comment by mehmetdogru** [comment]
@TakaHoribe I guess this issue can be closed?

**Comment by TakaHoribe** [comment]
This can be closed with these PRs.
https://github.com/autowarefoundation/autoware.universe/issues/2605#issuecomment-1368926141
