### ISSUE TITLE
The node of behavior_path_planner dies in some conditions

### ISSUE THREAD

**Issue by shulanbushangshu** [autowarefoundation/autoware.universe#2607]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The node of behavior_path_planner dies  when I set target in change lane.The simulation is shown as below:
![Screenshot from 2023-01-03 15-28-51](https://user-images.githubusercontent.com/102840938/210315520-4a8479d0-940b-435b-92dd-3e80f23aa358.png)

![Screenshot from 2023-01-03 15-30-06](https://user-images.githubusercontent.com/102840938/210315555-ca2fdf9b-3deb-4702-ba25-3d728ec7b531.png)

![Screenshot from 2022-12-29 14-46-47](https://user-images.githubusercontent.com/102840938/210305625-74e88449-e1a3-4898-93ed-d0e53c56c27e.png)

note:

![lane_change](https://user-images.githubusercontent.com/102840938/210330830-481cc38d-8d39-4b71-b2e6-8a51448ce4bd.png)

Lane change is not allowed in the area within the red border.
I print out information of path  and the size of points of path is zero in lane_following.
### Expected behavior

The node of behavior_path_planner shall not die  in any conditions of lanes and target.

### Actual behavior

The node of behavior_path_planner dies  in some conditions of lanes and target.

### Steps to reproduce

1.Start autoware planning simulator;
2. Set initial position
3. Set target in the change lane(there are more than two lanes and the distance of lane change shall is not enough)

### Versions

1.OS: Ubuntun 20.04
2.ROS2: Galactic
3.Autoware: Autoware.universe:main

**Comment by zulfaqar-azmi-t4** [comment]
Hi @shulanbushangshu 
Thank you very much for the report.
The bug probably is related to the https://github.com/autowarefoundation/autoware.universe/issues/2473

There is a bit delay due to some circumstances, but I'll try fix it as soon as possible.

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu 
Can you help to confirm whether #2615 solve this issue ?
thank you very much in advance.

**Comment by shulanbushangshu** [comment]
@zulfaqar-azmi-t4 
I  change the codes with https://github.com/autowarefoundation/autoware.universe/pull/2615 and finish the simulation.

case1:
![Screenshot from 2023-01-10 14-22-43](https://user-images.githubusercontent.com/102840938/211477834-88926333-6105-4b86-b809-d3333e275400.png)

case2:
I set the target in the third lane and the distance of lane change shall is not enough.
![Screenshot from 2023-01-10 14-22-59](https://user-images.githubusercontent.com/102840938/211477856-f48e23a1-54cd-4a92-b82a-4c58c9a9b1fe.png)

The  node of behavior_path_planner  still died.

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu 
Is this the latest commit in the upstream? I seems to me the lane change path is a bit weird.
I couldn't reproduce the error, therefore, could you share to me the lanelet map file?

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangsh
is there any update regarding this issue?
If not, I might close the thread.

**Comment by shulanbushangshu** [comment]
@zulfaqar-azmi-t4 
The lanelet2_map:
[lanelet2_map.zip](https://github.com/autowarefoundation/autoware.universe/files/11059967/lanelet2_map.zip)

The position of testing lane:
![Screenshot from 2023-03-24 16-25-17](https://user-images.githubusercontent.com/102840938/227466744-7aa1e90a-f53b-4009-8c5a-00e2a4f0e153.png)

**Comment by shulanbushangshu** [comment]
I test the issue in the autoware of humble.There is still problem and the test is as follows:
![Screenshot from 2023-04-07 13-32-17](https://user-images.githubusercontent.com/102840938/230549717-44c9a1ef-4b1a-4e15-aecd-858de03e1cef.png)
![Screenshot from 2023-04-07 13-32-03](https://user-images.githubusercontent.com/102840938/230549732-022b595a-b70b-4d81-ba8d-cd90b72fc325.png)
I have updated the pr

**Comment by shulanbushangshu** [comment]
It is fixed in the newest code. I close the issue
