### ISSUE TITLE
some of calcSignedArcLength function need to consider path index or pose

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#265]

**Comment by kenji-miyake** [comment]
Please write some descriptions.

**Comment by taikitanaka3** [comment]
currently calcSignedArclength is only consider position to the closest segment so the place where path or trajectory has it's own intersection segment then closest point is considered as target point.
![image](https://user-images.githubusercontent.com/65527974/149866661-1544523f-e5cd-4159-a34d-72cfa8ce6f24.png)

**Comment by taikitanaka3** [comment]
for other cases
![image](https://user-images.githubusercontent.com/65527974/154379713-4bf952a4-23aa-4b73-bfdd-681523d5c603.png)

**Comment by taikitanaka3** [comment]
use case
![image](https://user-images.githubusercontent.com/65527974/154380315-792e1529-5ab2-4c8a-b57e-6b5a437a87b9.png)

**Comment by taikitanaka3** [comment]
@takayuki5168 
Do you have any idea how to avoid segmentation fault if application side wants calculate longitudinal offset segment from last path index?
https://github.com/autowarefoundation/autoware.universe/blob/ca45e4aa3af8837fd1853f69d036ea9c1ec2d2a3/common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp#L128

**Comment by taikitanaka3** [comment]
closed for stop line module has this fix
