### ISSUE TITLE
DevOps Dojo: ROS Node Configuration (Phase 3)

### ISSUE THREAD

**Issue by kaspermeck-arm** [autowarefoundation/autoware.universe#2651]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

DevOps: Ros Node Configuration will address the topic of how ROS nodes are configured. Guidelines, documentation and changes to configuration files will be made, based on best-practices from cloud-native and software defined development methodologies.

Phase 1 - Motivation
- https://github.com/autowarefoundation/autoware.universe/issues/2631

Phase 2 - Definition
- https://github.com/autowarefoundation/autoware.universe/issues/2636

Phase 3 - Execution
- https://github.com/autowarefoundation/autoware.universe/issues/2651

Phase 4 - Integration
- https://github.com/autowarefoundation/autoware.universe/issues/2652

### Purpose

Phase 3 - Execution:
- learn new necessary skills
  - JSON Schema and YAML files
- implement and test
- evaluation
- iteration

### Possible approaches

Find guidelines here:
- https://github.com/orgs/autowarefoundation/discussions/3433

### Definition of done

Once Lidar Apollo Segmentation TVM Nodes has been approved and merged.

**Comment by kasperornmeck** [comment]
There is now consensus on how ROS nodes should be configured **(still TBD on April 6th)**, see:
- https://github.com/orgs/autowarefoundation/discussions/3371

The first actionable code change issue has been created, see:
- https://github.com/autowarefoundation/autoware.universe/issues/3239

This issue addresses:
- implement and test
- evaluation
- iteration 
  - (only if necessary)

**Comment by kasperornmeck** [comment]
Find implementation details here https://github.com/orgs/autowarefoundation/discussions/3371
First node to adapt the new is Lidar Apollo Segmentation TVM Nodes, see https://github.com/autowarefoundation/autoware.universe/issues/3239
