### ISSUE TITLE
Update camera lidar fusion based detection

### ISSUE THREAD

**Issue by kaancolak** [autowarefoundation/autoware.universe#2659]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

This task structured over this discussion : https://github.com/orgs/autowarefoundation/discussions/3195

### Purpose

Decrease computational cost of camera-lidar detection pipeline.

### Possible approaches

1. Add trust distance param to ROI-cluster fusion node, only fuse short-range objects given as a parameter
2. Remove object_range_splitter module from "camera_lidar_fusion_based_detection.launch.xml"
3. Remove one of the object_association_merger modules from "camera_lidar_fusion_based_detection.launch.xml"
4. Convert merging architecture to the given below;

![updated drawio](https://user-images.githubusercontent.com/12658936/212678705-35054bec-e3fe-45b1-8375-ecb5e0abc3b2.png)

### Definition of done

- [x] Update ROI fusion package : https://github.com/autowarefoundation/autoware.universe/pull/2844
- [x] Update ["camera_lidar_fusion_based_detection.launch.xml"] : https://github.com/autowarefoundation/autoware.universe/pull/2845(https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml)
- [x]  Update Autoware Universe [node diagram](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/node-diagram/)  : https://github.com/autowarefoundation/autoware-documentation/pull/322

**Comment by badai-nguyen** [comment]
@kaancolak I think all PRs related to update perception pipeline are merged, so could we close this issue? Any other fix or update is needed?
