### ISSUE TITLE
Support rolling(humble)

### ISSUE THREAD

**Issue by wep21** [autowarefoundation/autoware.universe#268]
Some modifications are necessary to migrate to ros2 rolling(humble).
https://github.com/autowarefoundation/autoware.universe/pull/247

**Comment by wep21** [comment]
https://docs.ros.org/en/foxy/Releases/Release-Humble-Hawksbill.html

**Comment by kenji-miyake** [comment]
We have to plan migration steps to Humble.

My (super rough) proposal is:
- Support rolling after Ubuntu 22.04 is released. (Around the end of April.)
  - If a change is supported by Galactic, merge to the `main` branch.
  - If not, merge to the `rolling` branch.
- Support Humble after ROS 2 Humble is released. (Around the end of May.)
  - Ideally, just renaming `rolling` to `humble`.
- Create the `galactic` branch and merge `humble` to `main`.

@xmfcx @mitsudome-r What do you think about it?

**Comment by kenji-miyake** [comment]
https://github.com/autowarefoundation/autoware.universe/labels/rolling
https://github.com/autowarefoundation/autoware.universe/labels/humble

**Comment by kenji-miyake** [comment]
I'll set up Ubuntu 22.04 next week and work in a branch.

**Comment by kenji-miyake** [comment]
TODO: Remove workarounds after we moved to Humble.
https://github.com/autowarefoundation/autoware.universe/pull/720

**Comment by kenji-miyake** [comment]
@esteve From your ROS experiences, do you have any suggestions on this?
https://github.com/autowarefoundation/autoware.universe/issues/268#issuecomment-1078430411

**Comment by esteve** [comment]
@kenji-miyake in my opinion, the plan sounds good. After Humble is released, we won't be supporting Rolling, right?

**Comment by kenji-miyake** [comment]
@esteve No, I believe we won't (at least proactively).
But if someone wants to add the Rolling support by using `ROS_DISTRO` macros, I think it can be acceptable.
However, it cannot be a mandatory condition for merging PRs because Rolling may collapse frequently.

**Comment by kenji-miyake** [comment]
Now the `main` branch supports both `Galactic` and `Humble`.
See https://github.com/autowarefoundation/autoware/pull/2692 for further information.
