### ISSUE TITLE
When the processing load of the main callback function is high, other callback functions starve.

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#275]
When the processing load of the main callback function is high, the other callback functions starve. 
In particular, some of the planning processes are so heavy that they cannot receive velocity, object and pointcloud.

The same problem occurred in localization, and it was solved by using multi-threading.
https://github.com/autowarefoundation/autoware.universe/commit/0ec1440064fcdc28ae9f04d23554dba65afbf87b#diff-636e0f59d675b65f5e7fc80e805b839474f437d7c89a46b4af048f455ee46e26

**Comment by kenji-miyake** [comment]
Resolved by #260.
