### ISSUE TITLE
Improve poincloud resolution for Euclidean cluster in long range

### ISSUE THREAD

**Issue by badai-nguyen** [autowarefoundation/autoware.universe#2754]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Currently, the detection range is extended until 150m in front by [this PR](https://github.com/autowarefoundation/autoware_launch/pull/141).
However, in camera_lidar_fusion mode, Euclidean cluster shows weak result of clustering from middle and long range due to of low pointcloud density or no pointcloud remained after [ voxel_grid and outlier_filter with the same size and threshold.](https://github.com/autowarefoundation/autoware.universe/blob/67459763bd61a57e044132174dd1c403550c1f00/perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py#L52-L81)  

![image](https://user-images.githubusercontent.com/94814556/214779204-e2297630-2e36-426b-b82c-af1924b0a8db.png)

### Purpose

I suggest that without downsampleing in middle and long range after ground_segmentation for Euclidean cluster input could improve the clustering result as well as camera_lidar_fusion result.

### Possible approaches

1. Use some changeable size and threshold for voxel_grid and outlier_filter. It looks quite hard since pcl library modification level is needed. 
2.  Separate the short-range region where downsampling is applied and keep middle,long-range out of downsampling. This is more feasible IMO.
Current pipeline around Euclidean cluster
![image](https://user-images.githubusercontent.com/94814556/214807871-45514903-3396-431c-8b8e-34ac77edc7bb.png)

Suggestion:

![image](https://user-images.githubusercontent.com/94814556/214808093-ed84e59e-82b4-492d-b0b1-748a598d7055.png)

### Definition of done

Sufficient pointclouds of compact car are remained at long-range for Euclidean_cluster.

**Comment by miursh** [comment]
closed by https://github.com/autowarefoundation/autoware.universe/pull/2749
