### ISSUE TITLE
Display labeled code coverage in pull requests

### ISSUE THREAD

**Issue by KeisukeShima** [autowarefoundation/autoware.universe#286]
Related to <https://github.com/autowarefoundation/autoware-documentation/issues/2>, I would like to add the feature to measure and display code coverage for pull requests to improve review process.

Considerations
* About the reporter, whether to use CodeCov or to create a function to measure and report in GitHub Actions.
* How to specify labels for coverage by label, whether to automatically collect all labels or to specify the labels we want to set.

**Comment by kenji-miyake** [comment]
:+1: 
I think using CodeCov at first is efficient.

**Comment by kenji-miyake** [comment]
@KeisukeShima Can this be closed?
Or will you work on `coverage by label` in this issue? If so, I think the title should be changed.

**Comment by KeisukeShima** [comment]
> @KeisukeShima Can this be closed? Or will you work on `coverage by label` in this issue? If so, I think the title should be changed.

I think that getting coverage by label is also part of this issue.
If we need to change the title, how about changing it to `Display labeled code coverage in pull request`?

**Comment by kenji-miyake** [comment]
I think we can close this for now. (Codecov integration is done.)
We'll reconsider this in https://github.com/autowarefoundation/autoware.core.
