### ISSUE TITLE
"lidar_centerpoint" gives poor pedestrian results after model change 

### ISSUE THREAD

**Issue by kaancolak** [autowarefoundation/autoware.universe#2865]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

 After updates of the model weight, "lidar_centerpoint" gives many false negatives for pedestrians and mixing vehicle-pedestrian labels. 

is it possible some retraining parameters were missed while adding the model?

When I revert the commit to the previously trained version, it looks better. 

**Re-trained current model:** 

[![Current model](https://img.youtube.com/vi/9R891cWf1BU/0.jpg)](https://www.youtube.com/watch?v=9R891cWf1BU "Current mode")

**Previously model:**

[![previously model](https://img.youtube.com/vi/INsgjGMya_c/0.jpg)](https://www.youtube.com/watch?v=INsgjGMya_c "previously model")

 Probably relevant PR: https://github.com/autowarefoundation/autoware.universe/pull/2553/files

Bag file : 
https://drive.google.com/file/d/1yhKURK1EQvQslw9lFRFhW551gLKhZaF-/view?usp=share_link

### Expected behavior

 Correctly detect road objects.

### Actual behavior

 Gives false negatives for pedestrians, and labels mix each other. 

### Steps to reproduce

1. Concat enate point cloud topics in the given bag file
2. Run the lidar_centerpoint model 

### Possible causes

 - Missing configuration or training issues

**Comment by knzo25** [comment]
Hi, this is due to a change in the database used for training (which had to be done for licensing reasons).

**Comment by kaancolak** [comment]
I see, thank you for the explanation.

> Hi, this is due to a change in the database used for training (which had to be done for licensing reasons).

I see, thank you for the explanation. I am closing the issue.
