### ISSUE TITLE
Update occupancy grid map frame to gain longer range visibility in the intersection

### ISSUE THREAD

**Issue by YoshiRi** [autowarefoundation/autoware.universe#2906]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Currently, we are using `base_link` frame to generate occupancy grid map.
The base_link is typically set at the center of the rear wheel, behind the vehicle rather than the LiDAR or driver. (See following Figure)

Therefore, the field of view of the occupancy grid map generated in the `base_link` is narrower than that of the driver or the sensor's viewpoint, for example, when turning right at an intersection.

![image](https://user-images.githubusercontent.com/20086766/219589024-3ba5f638-4366-4827-bf6b-65fad5fb4ac7.png)

### Purpose

We need to change grid map estimation frame to achieve

- **wider range visibility**
- principled correctness

### Possible approaches

I think there are two possible approaches:

| name | figure | note |
|--|--|--|
|current|![image](https://user-images.githubusercontent.com/20086766/219593451-dd92e24e-8889-41f6-b920-57195a213e89.png)|current setting|
|plan A|![image](https://user-images.githubusercontent.com/20086766/219593386-ac4a00b2-a426-4a4e-a2d6-be3d5d7fedea.png)|generate occupancy grid map in other frame|
|plan B|![image](https://user-images.githubusercontent.com/20086766/219594227-b8139749-16e7-4caf-9b64-e5bf26e8ca56.png)|More faithful method to sensor visibility|

planA should be easier to implement.   
planB will accurately represent the visible range of the sensor.

Since we often use only top LiDAR to sense further objects, I think using planA and set its frame to top lidar sensor will be enough.

### Definition of done

[TBD]

Should be confirmed in scenarios involving right turns at intersections.

**Comment by soblin** [comment]
In planning modules, the main customers for occupancy grid map are:
- occlusion_spot
- intersection
- pullover/pullout
modules.

This proposal maybe especially useful for intersection module.

**Comment by VRichardJP** [comment]
Although it might be more tedious to implement, plan B looks like the only valid option to me: if a vehicle has multiple sensors at several places, it is because visibility is not the same everywhere. For small vehicles such as cars, the top lidar is indeed the one with the widest/farthest FOV, but when it comes to larger vehicles (minibus, shuttle, bus, truck, etc), no sensor can clearly see everything around.

**Comment by miursh** [comment]
I suppose plan B is more suitable for expressing sensor FoV. 
Although, it would be quite complicated to implement and I believe there are several design points.
e.g. is isn't it difficult to determine whether out of sensor FoV or free space by only using limited FoV sensor, which both appears no return points.

**Comment by taikitanaka3** [comment]
@soblin 
I think generate grid map only at driver frame is also ok. I don't know module which requires grid map at baselink frame.

**Comment by YoshiRi** [comment]
Now I agree with VRichardJP and miurush that the plan B should be the final solution.
But you know, we need a lot of changes and there are also concern about computational load.

So I just implemented the plan A for the instant solution. 
@soblin could you check if this PR improves our planning scenarios?

**Comment by idorobotics** [comment]
@YoshiRi what is the current status for this issue?

**Comment by YoshiRi** [comment]
@idorobotics 
Sorry, I am Pending this matter now due to other prioritized tasks. 
The latest status is in [DevelopmentAboutOccupancyGridMapFusion.pdf](https://github.com/autowarefoundation/autoware.universe/files/12821145/DevelopmentAboutOccupancyGridMapFusion.pdf)


## remaining tasks
OGM fusion will be available after merging the following two PRs.

- [OGM fusion node PR](https://github.com/autowarefoundation/autoware.universe/pull/3107) 
- [launcher PR](https://github.com/autowarefoundation/autoware.universe/issues/3045)

**Comment by YoshiRi** [comment]
All features are merged and successfully tested.
Also see related discussion: https://github.com/orgs/autowarefoundation/discussions/4158#discussioncomment-8664198.
