### ISSUE TITLE
remove default parameters in planning/control modules

### ISSUE THREAD

**Issue by yamazakiTasuku** [autowarefoundation/autoware.universe#2969]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Currently, default values are set when using declare_parameter. Therefore, when a user sets a parameter, Autoware starts with that default value even if it is not set correctly.

### Expected behavior

When a user sets a parameter, Autoware starts with that default value even if it is not set correctly. This causes Autoware to run with parameters that the user does not intend.

### Actual behavior

There is a possibility of starting with different values than the set parameters.

### Steps to reproduce

Set parameters in the wrong way

### Additional context
Modified module

planning
- [x]  behavior_path_planner
- [x] behavior_velocity_planner
- [x] costmap_generator
- [X] external_velocity_limit_selector
- [x] freespace_planner
- [x] mission_planner
- [X] motion_velocity_smoother
- [x] obstacle_avoidance_planner
- [x] obstacle_cruise_planner
- [X] obstacle_stop_planner
- [x] obstacle_velocity_limiter
- [x] planning_debug_tools
- [x] planning_validator
- [x] route_handler
- [x] rtc_auto_mode_manager
- [x] rtc_interface
- [x] rtc_replayer
- [x] scenario_selector
- [x] static_centerline_optimizer
- [X] surround_obstacle_checker
- 
control
- [X] controller performance analysis
- [x] external_cmd_selector
- [X] joy controller
- [X] lane departure checker
- [x] mpc_lateral_controller
- [x] obstacle_collision_checker
- [x] operation_mode_transition_manager
- [x] pid_longitudinal_controller
- [x]  pure pursuit
- [X] shift decider
- [x] trajectory_follower_base
- [x] trajectory_follower_node
- [x] vehicle_cmd_gate

_No response_

**Comment by satoshi-ota** [comment]
@yamazakiTasuku Thanks for your contribution.
I think it is better to use checkbox to show your progress.

**PROGRESS**

- [ ] obstacle_stop_planner
- [ ] external_velocity_limit_selector
- [ ] motion_velocity_smoother
- [ ] surround_obstacle_checker
- [ ] behavior_velocity_planner
- [ ] ...
