### ISSUE TITLE
Simple planning simulator does not consider vehicle/engage result.

### ISSUE THREAD

**Issue by takayuki5168** [autowarefoundation/autoware.universe#300]
simple planning simulator dropped some features during .universe porting
- /vehicle/engage result is not considered for simulating (Ideally, simulating only when /vehicle/engage result is true)
- default parameter for /vehicle/engage result (current_engage_ variable) was removed and set false by default.

**Comment by kenji-miyake** [comment]
@takayuki5168 Can this be closed?
FYI: If you want to automatically close an issue after merging a PR, writing like `Resolve #300` is useful.

**Comment by takayuki5168** [comment]
@kenji-miyake Yes, this issue has been already resolved. Sorry about that. Thanks for your information!
