### ISSUE TITLE
autoware_state_panel cannot present NEUTRAL

### ISSUE THREAD

**Issue by ahuazuipiaoliang** [autowarefoundation/autoware.universe#3121]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

autoware_state_panel cannot present `NEUTRAL` gear

### Expected behavior

when the vehicle shift to `NEUTRAL`, we can see `NEUTRAL` in AutowareStatePanel in RViz

### Actual behavior

when the vehicle shift to `NEUTRAL`, it could not show `NEUTRAL` in the red box below
![image](https://user-images.githubusercontent.com/35034146/226260301-231d3f74-cc3d-406b-aeb1-92b4a3fddff7.png)

### Steps to reproduce

1. turn on Autoware.core/universe
2. switch vehicle to the gear of `NEUTRAL` 

### Versions

- OS: Ubuntu 22.04
- Autoware.universe: [4267add](https://github.com/autowarefoundation/autoware.universe/commit/4267add3ec861b333c8ccf8d1fe692d5dfb70d58)

### Possible causes

https://github.com/autowarefoundation/autoware.universe/blob/main/common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp#L517
there is no `NEUTRAL` handle command in `AutowareStatePanel::onShift` function
```c++
void AutowareStatePanel::onShift(
  const autoware_auto_vehicle_msgs::msg::GearReport::ConstSharedPtr msg)
{
  switch (msg->report) {
    case autoware_auto_vehicle_msgs::msg::GearReport::PARK:
      gear_label_ptr_->setText("PARKING");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::REVERSE:
      gear_label_ptr_->setText("REVERSE");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::DRIVE:
      gear_label_ptr_->setText("DRIVE");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::LOW:
      gear_label_ptr_->setText("LOW");
      break;
  }
}
```

**Comment by xmfcx** [comment]
@ahuazuipiaoliang Thanks for the issue, do you have plans to incorporate this feature into the autoware or should we assign someone for this task?
