### ISSUE TITLE
Move downloading artifacts outside CMake

### ISSUE THREAD

**Issue by esteve** [autowarefoundation/autoware.universe#3137]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Some packages download artifacts by default, which is not necessary for compiling them. Additionally, during the process for generating Debian packages, access to the network is restricted, so building these packages fail (see https://github.com/autowarefoundation/autoware/issues/3222#issuecomment-1478085589)

The packages that download ONNX models are:

 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3140
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3141
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3142
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3143
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3144
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/3145
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/4896
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/4904
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/4905

Other types of artifacts:

 - [x] https://github.com/autowarefoundation/autoware.universe/pull/4110
 - [x] https://github.com/autowarefoundation/autoware/pull/3855
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/4923
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/5367
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/5431

Update ansible scripts to download artifacts files:

 - [x] https://github.com/autowarefoundation/autoware/pull/3375
 - [x] https://github.com/autowarefoundation/autoware/pull/3848
 - [x]  <del>https://github.com/autowarefoundation/autoware/pull/3856</del>
 - [x] https://github.com/autowarefoundation/autoware/pull/3866
 - [x] https://github.com/autowarefoundation/autoware/pull/3916

Update documentation with instructions on how to download ONNX files:

 - [x] https://github.com/autowarefoundation/autoware-documentation/pull/345
 - [x] https://github.com/autowarefoundation/autoware-documentation/pull/456
 - [x] https://github.com/autowarefoundation/autoware/pull/3850
 - [x] https://github.com/autowarefoundation/autoware-documentation/pull/462
 - [x] https://github.com/autowarefoundation/autoware-documentation/pull/463  

Disable internet access for CI actions:

 - [x] https://github.com/autowarefoundation/autoware-github-actions/pull/241

Add `data_path` variable to `autoware_launch`:

 - [x] https://github.com/autowarefoundation/autoware_launch/pull/577
 - [x] https://github.com/autowarefoundation/autoware.universe/pull/5069

Update default path to artifacts in package launch files:

- [x] https://github.com/autowarefoundation/autoware.universe/pull/5118
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5119
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5139
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5141 
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5144 
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5158 
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5162 
- [x] https://github.com/autowarefoundation/autoware.universe/pull/5163

### Purpose

Be able to build the packages without requiring to download the ONNX models

### Possible approaches

Remove the download logic so that ONNX models, update `ansible` scripts to download them when deploying the packages and document how to manually download the models.

### Definition of done

Packages can be built without downloading the ONNX models. Documentation is updated to let users manually download the ONNX models. Update `ansible` scripts to download the models.

**Comment by yukkysaito** [comment]
Thank you for your proposal.
If DOWNLOAD_ARTIFACTS is default false, won't the rosbag replay simulator stop working?

**Comment by esteve** [comment]
@yukkysaito thanks for your comment. I've only submitted changes to the packages that download ONNX models. Could you link to the packages that download `rosbag` files? Thanks.

In any case, the reason for not downloading external files by default is because the processes we use for generating Debian packages restrict access to the network (as is the Debian policy for building packages), so we can't download files in `CMakeLists.txt`. I have some questions:

 - Is there another way to distribute the `rosbag` files?
 - Perhaps a separate package or adding instructions for users?
 - How big are the files?
 - Maybe we could use something like `git-lfs` to store them in Git?

Thanks.

**Comment by yukkysaito** [comment]
@esteve sorry, I may have written it badly and caused a misunderstanding.
I am not talking about rosbag, but rosbag replay simulator. :pray: 
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

rosbag replay simulator uses DNN such as centerpoint, so it is necessary to download the onnx file.
If the default is set to false, the onnx file will not be downloaded and the rosbag replay simulator in the tutorial will not work.

I would preferably download it when setting up the environment in ansible, so that no internet connection is needed at build time.

**Comment by esteve** [comment]
@yukkysaito ah, sorry, I misunderstood. Thanks, I agree it'd be much easier if downloading the ONNX models is done outside the build process of `CMakeLists.txt`. I can remove the logic from `CMakeLists.txt` and we can update the `ansible` scripts. I'm not familiar with `ansible`, but I can try.

**Comment by xmfcx** [comment]
I agree, the links are in the `CMakeLists.txt` file and most are in https://web.auto domain name right now.

Moving them to ansible and also adding the manual steps in the readme of the [role](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/) should be enough.

And yes like @esteve suggested we should remove the remains of the downloads from the `CMakeLists.txt` files.

**Comment by esteve** [comment]
Following this discussion I've closed https://github.com/autowarefoundation/autoware_common/pull/164 and will rework the rest of the PRs to remove the download logic. I'll also update the documentation and the ansible scripts.

**Comment by yukkysaito** [comment]
There are a few things to consider for downloading with ansible.

- Where to put the downloads?
- How do DNN pkgs (centerpoint, etc.) refer to the downloaded file from launch?

As an example,to refer to the downloaded file in launch file by ansible, we can create a specific package, put the weight file there, and refer to it from launch.
Do you have any other suggestions?

**Comment by xmfcx** [comment]
@yukkysaito

Right now Autoware has `map_path` as an external directory necessary for the runtime:
```bash
ros2 launch autoware_launch logging_simulator.launch.xml \
map_path:=$HOME/autoware_map/sample-map-rosbag \
vehicle_model:=sample_vehicle \
sensor_model:=sample_sensor_kit
```

What about adding a `neural_net_models` path too?

Then this path could be passed to the necessary nodes.

**Comment by esteve** [comment]
> There are a few things to consider for downloading with ansible.
> 
>     * Where to put the downloads?
> 
>     * How do DNN pkgs (centerpoint, etc.) refer to the downloaded file from launch?
> 
> 
> As an example,to refer to the downloaded file in launch file by ansible, we can create a specific package, put the weight file there, and refer to it from launch. Do you have any other suggestions?

Sorry, I'm afraid I'm not following here. Will the package store the weight file? And if not using `ansible`, how will the package get populated with the model files? Could you explain further? Thanks.

**Comment by esteve** [comment]
@xmfcx

> What about adding a `ml_models_path` (machine learning) path too?
> 
> Then this path could be passed to the necessary nodes.

I think this is a good idea, it'll standardize how to access the models across all nodes. What path by default should we tell users to download files to? With `ansible` we can decide for them, but I'm thinking of when Autoware is installed manually. 

Also, when/if we generate Debian packages for these packages, should the models be installed system-wide or in a user's folder?

**Comment by yukkysaito** [comment]
>What about adding a ml_models_path (machine learning) path too?
Then this path could be passed to the necessary nodes.

I think the map path is necessary because it specifies the environment in which to run, but ml_model_path seems to be a parameter of convenience inside Autoware.
So I would like to make the user don't care it, is there a good way to do this?

**Comment by xmfcx** [comment]
Related: https://github.com/orgs/autowarefoundation/discussions/3649

**Comment by esteve** [comment]
Closing this ticket now that all the linked PRs are merged. Thanks everyone, especially @lexavtanke
