### ISSUE TITLE
PathPointWithLaneId message used in behavior path / velocity planner is still tier4 original message

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#315]
since PathPointWithLaneId  is still tier4 original tier4_autoware_utils can't include PathPointWithLaneId message.

**Comment by kenji-miyake** [comment]
Also, we must move PathPointWithLaneId from autoware_auto_planning_msgs to tier4_planning_msgs because it's TIER IV's internal message.
https://github.com/autowarefoundation/autoware.universe/pull/306#discussion_r794243533

**Comment by kenji-miyake** [comment]
@taikitanaka3 Could you update the status?

**Comment by taikitanaka3** [comment]
It's not changed yet  I want someone to do this

**Comment by takayuki5168** [comment]
@taikitanaka3 Now it's okay to use PathWithLaneId in tier4_autoware_utils. Can I close this issue?

**Comment by taikitanaka3** [comment]
yes it can be closed
