### ISSUE TITLE
PullOver/Out limitation and development plan

### ISSUE THREAD

**Issue by kosuke55** [autowarefoundation/autoware.universe#3223]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

pull_over/out modules have the following limitations.

- [pull_over](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/behavior_path_planner_pull_over_design/)
  - Support parking on only `road_shoulder` 
![image](https://user-images.githubusercontent.com/39142679/229003311-09e8dff9-ef76-4059-bf3d-0416f4215c9e.png)

  - Cannot park on the `road` or in the same lane.
  - Cannot consider moving objects for safety judgment
- [pull_out](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/behavior_path_planner_pull_out_design/
)
  - Cannot start in cases requiring complicated maneuvering
  - Can only start from `road_shoulder`
  - Cannot start from the `road` or the same lane
  - Cannot consider moving objects for safety judgment

### Purpose

solve these limitations and improve functionalies

### Possible approaches

- pull_over
  - Support parking on both `road` and `road_shoulder` ->(deal this this patter with LC. pull over support only current road) ![image](https://user-images.githubusercontent.com/39142679/229003411-d7fa2ff3-dc65-4849-b341-00e4b9893546.png) 
  - Implement a goal planner
    - Activate every time when near the goal
      - If goal adjustment is allowed: park at the side edge of the lane(like pull over) ![image](https://user-images.githubusercontent.com/39142679/229003431-da95c824-e970-43f2-90d9-485ed19f2f6b.png)
      - If goal adjustment is not allowed: park at the given goal (like the current lane following)
![image](https://user-images.githubusercontent.com/39142679/229003573-26ee5ff2-678f-46f7-9a0f-20f1ebfdc46a.png)

  - work with MRM (Minimum Risk Maneuver)
    - https://github.com/autowarefoundation/autoware.universe/issues/3221 
    - also support rerouting when driving
  - Consider moving objects

- pull_out
  - Support starting from both `road` and `road_shoulder`
  - Implement a start planner
    - Activate every time at starting driving
    - Start towards the centerline or shift from the current lane to the desired lane
  - Consider moving objects
  - Use a free space planner for starting driving

### Definition of done

Complete these implementations to resolve limitations and improve functionalies

**Comment by kosuke55** [comment]
Currently in pull_over, if an object exists on the lane and the vehicle is stuck, generate a path for avoiding objects using `parking_lot` as a drivable area. (use the same algorithms of https://github.com/autowarefoundation/autoware.universe/tree/main/planning/freespace_planning_algorithms)

https://user-images.githubusercontent.com/39142679/231684049-21e8e7ca-9baf-48f5-a8a6-8d9517afecf5.mp4

We will plan to develop the same feature also in pull_out

> - pull_out
>   - Use a free space planner for starting driving

**Comment by kosuke55** [comment]
this is the sample behavior of `goal planner`


https://user-images.githubusercontent.com/39142679/231474481-49809d88-b09e-45d2-98fe-347310afe27a.mp4 

from  https://github.com/autowarefoundation/autoware.universe/pull/3370#pullrequestreview-1381339173

  - This module determines the goal position according to Autoware's decision when goal modification is allowed.
    - To avoid obstacles
    - Refine the goal according to a certain policy (e.g. right-align, left-align)
  - When the goal is not modified, it behaves as before.
    - Simply stop against the original goal by just lane following.

**Comment by kosuke55** [comment]
merged rough goal rviz plugin

https://github.com/autowarefoundation/autoware_launch/pull/295

`goal planner` is **under development**, so if setting rough goal now, the goal will **not** be modified.

**Comment by kosuke55** [comment]
send goal planner PR https://github.com/autowarefoundation/autoware.universe/pull/3454


Make pull_over execute when the vehicle is approaching the goal. (within `minimum_request_length`)

put goal in `road`
- `2D Goal Pose` in `road` 
  -  `modifyPathForSmoothGoalConnection` (same as current lane following arrival path)
- `2D Rough Goal Pose` in `Road` 
  -  pull over to the modified goal in `road` or `road_shoulder` with the select policy (e.g. parking left_side, right side)


check `2D Goal Pose` and `2D Rough Goal Pose`

https://user-images.githubusercontent.com/39142679/232829485-b9adcb85-c112-4ba1-972b-8440974c1e17.mp4

check planning to the fixed goal within `minimum_request_length`

https://user-images.githubusercontent.com/39142679/232829800-fdaf2e3c-ce74-483b-beb7-9b780d9b540f.mp4

lane_change ->goal planner

https://user-images.githubusercontent.com/39142679/232833424-ef5fcad0-3396-4348-a3fc-8e8906ddedc4.mp4

todo: need to execute lane_change and goal_planner wit new behavior path architecture to deal the situation the end of lane change is close to the goal. need 

https://user-images.githubusercontent.com/39142679/232833442-83c42958-9d43-47ca-9b97-e21d53a78e88.mp4

**Comment by zjw77889** [comment]
Is the shoulder lane the same as the lane? What attribute settings are required to add shoulder lanes and can a map be provided that can pull over.

**Comment by zjw77889** [comment]
@kosuke55

**Comment by kosuke55** [comment]
@zjw77889 
The `type` of the shoulder lane is `lanelet` so it is the same to the normal road lane, but the `subtype` is `road_shoulder` so it is different. You can set the `subtype` using [vector map builder](https://tools.tier4.jp/feature/vector_map_builder_ll2/) or editting .osm file directory.
the sample map in https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/ also have `road_shoulder` and you can try `pull_over` here in the image

![image](https://user-images.githubusercontent.com/39142679/235086244-b52286e3-7b6e-479b-96e7-1bb4879b5704.png)

Or also you can use pull_over in normal road lane if you setting  [`2D Rough Goal Pose`](https://github.com/autowarefoundation/autoware_launch/pull/295) with rviz(the shortcut key is `r`).  please refer to https://github.com/autowarefoundation/autoware.universe/pull/3419

![image](https://user-images.githubusercontent.com/39142679/235086794-c407f95e-951c-48d3-8d8a-94ed77aeb682.png)

**Comment by zjw77889** [comment]
@kosuke55
Thank you very much for your reply, it has been very helpful to me.

**Comment by kosuke55** [comment]
backward parking in narrow space

https://github.com/autowarefoundation/autoware.universe/assets/39142679/0ddf94d5-11b1-4dff-a0fe-a1237c632191

**Comment by kosuke55** [comment]
Free-space parking in complex object arrangements

https://github.com/autowarefoundation/autoware.universe/assets/39142679/f9ec2d11-d9d4-4ab2-b2c9-b567e1d384ec

**Comment by kosuke55** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/5979

**Comment by kosuke55** [comment]
safety checkhttps://github.com/autowarefoundation/autoware.universe/pull/5677

**Comment by kosuke55** [comment]
MRM https://github.com/autowarefoundation/autoware.universe/pull/5634
planning features have been merged.

https://github.com/autowarefoundation/autoware.universe/assets/876355/ba8278be-46ec-491f-b2d5-1459685bfa8a

**Comment by kosuke55** [comment]
# Development results

### Support parking on both road and road_shoulder


https://user-images.githubusercontent.com/39142679/232829485-b9adcb85-c112-4ba1-972b-8440974c1e17.mp4

### Implement a goal/start planner

see followings for the detail
- https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_goal_planner_module/
- https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_start_planner_module/

### work with MRM (Minimum Risk Maneuver) 

MRM https://github.com/autowarefoundation/autoware.universe/pull/5634
planning features have been merged.

https://github.com/autowarefoundation/autoware.universe/assets/876355/ba8278be-46ec-491f-b2d5-1459685bfa8a


### Consider moving objects

Perform safer safety checks using polygons of the predicted footprint integrated over time.

auto

https://github.com/autowarefoundation/autoware.universe/assets/39142679/762fd9ac-2651-4dd3-9b40-dc0a5e406c00

rtc

https://github.com/autowarefoundation/autoware.universe/assets/39142679/2a43837a-259b-447c-8895-9fb8024a19f4




###  free space planner

Free-space parking in complex object arrangements

https://github.com/autowarefoundation/autoware.universe/assets/39142679/f9ec2d11-d9d4-4ab2-b2c9-b567e1d384ec
