### ISSUE TITLE
DevOps Dojo: ROS Node Configuration - Adapt Lidar Apollo Segmentation TVM Nodes To New ROS Node Configuration

### ISSUE THREAD

**Issue by kaspermeck-arm** [autowarefoundation/autoware.universe#3239]
Make changes to [Lidar Apollo Segmentation TVM Nodes](https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_apollo_segmentation_tvm_nodes) in accordance to [Final3 Proposal](https://github.com/orgs/autowarefoundation/discussions/3371).

**Comment by Croquembouche** [comment]
Quick question about this package. Is this package only used if the Apollo LiDARs are used? What happens if I don't build this package?

**Comment by angry-crab** [comment]
> Quick question about this package. Is this package only used if the Apollo LiDARs are used? What happens if I don't build this package?

It has nothing to do Apollo Lidars. This package is used for object detection. You can use Centerpoint instead.
