### ISSUE TITLE
Fine weather Lidar Visibility dropped issue

### ISSUE THREAD

**Issue by badai-nguyen** [autowarefoundation/autoware.universe#357]
**Background**
 LiDAR Visibility is estimated based on noise point-cloud of weak_first_return from LiDAR Dual Mode. 

**Problem**
In road-side scenes which contain sparse point cloud objects such as plants, leaves or sport plastic nets, the LiDAR Visibility results are dramatically dropped, even in fine weather condition.

The reason is that such objects also return weak_first point cloud and treated as raindrop.

**Suggestions** 
1. Add logic to detect the sparse point cloud objects from weak_first_return point cloud, by extending the range of segment points
2. Exclude weak_first_return point clouds close to the last_strong_return point clouds which tend to be objects
+ Pros: high sensitivity
- Con: computation cost increase 

2. Exclude weak_first_return point cloud by setting region of interest (ROI):
+ Pros: low computation cost
- Cons: low sensitivity

**Comment by miursh** [comment]
This issue is resolved by https://github.com/autowarefoundation/autoware.universe/pull/345
