### ISSUE TITLE
There are duplicate parameters and functions in behavior_velocity_planner

### ISSUE THREAD

**Issue by kosuke55** [autowarefoundation/autoware.universe#361]
There are duplicate parameters and functions in bhavior_velocity_planner. It's better to common them.
- Functions
  -  calcSignedArcLength https://github.com/autowarefoundation/autoware.universe/pull/362
  - splineInterpolation https://github.com/autowarefoundation/autoware.universe/pull/411
  - isOverLine https://github.com/autowarefoundation/autoware.universe/pull/1599
  - insertStopPoint https://github.com/autowarefoundation/autoware.universe/pull/1599
  - findOffsetSegment https://github.com/autowarefoundation/autoware.universe/pull/1599
  - calcTargetPose https://github.com/autowarefoundation/autoware.universe/pull/1599
  - ...
- Parameters 
  - ...

**Comment by mitsudome-r** [comment]
@taikitanaka3 Are there still duplicate parameters functions in the planner node?

**Comment by taikitanaka3** [comment]
@mitsudome-r yes there still duplicated packages like autoware auto.utils.
but i think we wont fix in a month so.we can close issue for now and link this issue when refactoring.
@kosuke55 what do you.think？

**Comment by taikitanaka3** [comment]
@mitsudome-r yes there still duplicated packages like autoware auto.utils.
but i think we wont fix in a month so.we can close issue for now and link this issue when refactoring.
@kosuke55 what do you.think？

**Comment by kosuke55** [comment]
@mitsudome-r @taikitanaka3 
We haven't listed them yet because there are so many, but they're still there. (ex: behavior_velocity parameters are not commoned) 
It's OK to close this issue if this doesn't work. (or every time we find duplicates, we will list them here to help refactor.)

**Comment by mitsudome-r** [comment]
@kosuke55 I will close this issue for now. Please feel free to reopen or recreate a new issue if you have time to work on this.
