### ISSUE TITLE
Use pluginlib for behavior_velocity_planner

### ISSUE THREAD

**Issue by isamu-takagi** [autowarefoundation/autoware.universe#3724]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

The behavior_velocity_planner package contains many scene modules. I plan to use pluginlib to split the scene module into separate packages. This allows you to put additional scene modules in separate repositories. In addition, since the number of dependent libraries is minimized, the build efficiency is improved.

### Purpose

- Improve scene module extensibility.
- Improve build efficiency.

#### Classes

Move the interface and utilities into the common package. Move each scene module into its own package.

![behavior-velocity-pluginlib-class](https://github.com/autowarefoundation/autoware.universe/assets/43976882/a6741898-41e5-479c-a6d3-e93b4b922138)

#### Packages

The structure of the package is as follows.

```
planning
├── behavior_velocity_planner         (main node package)
├── behavior_velocity_planner_common  (plugin interface, library/utility)
├── behavior_velocity_foo_module
├── behavior_velocity_bar_module
└── behavior_velocity_baz_module
```

If the number of modules increases, the following structure is also a candidate.

```
planning
├── behavior_velocity_planner         (main node package)
├── behavior_velocity_planner_common  (plugin interface, library/utility)
└── behavior_velocity_modules
    ├── behavior_velocity_foo_module
    ├── behavior_velocity_bar_module
    └── behavior_velocity_baz_module
```

### Definition of done

- [x] split package with wrapper class
- [x] move readme
- [x] move parameter and launch files
- [ ] ~remove wrapper class~
  - [ ] blind spot
  - [ ] crosswalk
  - [ ] detection area
  - [ ] intersection
  - [ ] no stopping area
  - [ ] occlusion spot
  - [ ] out of lane
  - [ ] run out
  - [ ] speed bump
  - [ ] stop line
  - [ ] traffic light
  - [ ] virtual traffic light

**Comment by BonoloAWF** [comment]
@isamu-takagi can this issue be closed since https://github.com/autowarefoundation/autoware.universe/pull/3734 is merged?

**Comment by isamu-takagi** [comment]
The tasks listed in ”definition of done" section have not yet been completed.

**Comment by isamu-takagi** [comment]
I decided that I needed a wrapper class to use the constructor.
