### ISSUE TITLE
Difficulty of estimating velocity at future time t

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#383]
Currently there are behavior and motion planning modules.  Each modules publishes it's own planed velocity (eg. slow down or stop velocity). But this velocity planing is done sequentially from behavior to motion so behavior planning modules doesn't know how motion planing modules plan velocity.

![image](https://user-images.githubusercontent.com/65527974/153834405-a501e4d1-03b3-4975-9be3-2d7559ac6244.png)

**Comment by takayuki5168** [comment]
@taikitanaka3 Now we calculate the vehicle velocity with motion_velocity_smoother as a library in behavior_velocity_planner. Did this solve this issue?

**Comment by taikitanaka3** [comment]
no, but there is no approach with current architecture so i will close this issue.
