### ISSUE TITLE
map_loader and map_tf_generator can not load georeferenced maps

### ISSUE THREAD

**Issue by enesadastec** [autowarefoundation/autoware.universe#3882]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

"map_loader" and "map_tf_generator" packages can not load maps which have UTM coordinates like 4.000.000. Because these packages are reading ".pcd" files as pcl::PointXYZ which only supports float32 precision coordinates.

If we try to load UTM maps like that, the loaded map looks like corrupted on RVIZ (because all points are rounded to float32)
![image](https://github.com/autowarefoundation/autoware.universe/assets/94836003/d73d0a48-a11f-4fd0-a387-04f8cdb97fc0)

Here is an example pcd file which is not compatible with pcl::PointXYZ (float32)
![237363331-26c851a5-3f03-493e-9fee-05612abe5f2d](https://github.com/autowarefoundation/autoware.universe/assets/94836003/1b4daa9a-05a9-4fe2-b056-c4a5460433f4)

Discussion topic:
https://github.com/orgs/autowarefoundation/discussions/3355

### Purpose

Loading UTM maps which are not compatible with pcl::PointXYZ (float32)

### Possible approaches

- Set an origin point from the map and then substract this origin point from all points while reading map process (convert georeferenced coordinates to local coordinates)

### Definition of done

- Converting UTM maps to local coordinates and be able to visualize on RVIZ

**Comment by kminoda** [comment]
TIER IV is currently working on a very initial investigation for addressing maps that overlap MGRS grids or UTM zones. One possible approach we are considering is to create original projection from WGS84 to local coordinate. I believe this will subsidiary solve the issue mentioned here, as long as the map size are within appropriate range (say, 0km to 100km for x and y). With this update, **Autoware will be able to run without any worries on overlapping MGRS or UTM grids**.

We are currently in the final step of internal design review for this topic, so I think we can share the design within this month (or maybe in two weeks, if everything goes well). 

Here are some questions from our side:
- (Just as a confirmation) Does the above approach would solve your issue, doesn't it?
- What is your progress and future plan for the above issue?

We are happy to collaborate with you if necessary :+1:

**Comment by enesadastec** [comment]
Hi,

Thanks for your comment and brief information about your investigation.

1) As you can see on the photo in first comment, my map's X coordinate is 700.000 and Y coordinate is 4.700.000. Im not sure if your solution can handle situations like that.

2) Im currently aware of this problem and made a presentation in Mapping WG. As a solution, I was planning to add a feature that substracts origin coordinates that defined by user from all cloud points (with this way convert UTM coordinates to local coordinates).

If you currently working on this problem, we can wait for your test results to check whether this problem is solved with your solution. Then, if the problem is still occurs, we can reinvestigate the problem and we can talk about possible other solutions.

Also I will be very happy to contribute with you if there is something I can do.

**Comment by kminoda** [comment]
@enesadastec Thank you for the comments!  Let me move to the above discussion :pray:

**Comment by kminoda** [comment]
@enesadastec Sorry I forgot to post it here. Here's my proposal. Any comments or feedbacks are welcome!
https://github.com/orgs/autowarefoundation/discussions/3582

**Comment by enesadastec** [comment]
> 

Thanks for sharing the link. I checked the proposal and I believe it will solve this problem.

**Comment by kminoda** [comment]
@enesadastec Hi, I believe this issue is now solved with the proposal https://github.com/orgs/autowarefoundation/discussions/3582. Let us know if you have any further questions, and please close the issue if it is solved from your end as well.

**Comment by kminoda** [comment]
Since this is staled, I will convert this as closed. Please feel free to reopen this issue if you have any further issues. Thank you for your understanding.
