### ISSUE TITLE
Add design document of interface_test.

### ISSUE THREAD

**Issue by KeisukeShima** [autowarefoundation/autoware.universe#390]
# The reason of this change
By creating a framework for interface testing, we can perform efficient testing with less effort.
Design documentation will be created to discuss the design and usage.

# Approach

We will use rclpy's API to gather information about the topics that nodes are sending and receiving. Since no actual messages are sent or received, the test can be completed in a short time.
The predefined topic information is compared with the actual information to ensure that the specification and implementation are consistent.

# Alternatives

I considered using `launch_testing` to actually send and receive messages. However, this test is time consuming. It also requires more effort to set up the test than the above approach, since we have to define the appropriate inputs for each node.
For these reasons, I did not adopt this approach.

**Comment by kenji-miyake** [comment]
Same as this comment.
https://github.com/autowarefoundation/autoware.universe/issues/380#issuecomment-1038659995

If you create an issue, please write more descriptions so that people can understand.

**Comment by kenji-miyake** [comment]
@KeisukeShima Could you describe what errors can be prevented by this kind of test?
For example, "if a developer mistakenly wrote here as ..., then it will cause the error of ...".
