### ISSUE TITLE
Vehicle does not stop by goal pose in planning simulator

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [autowarefoundation/autoware.universe#3951]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

There is a weird behavior in planning simulator when you add a goal pose, the vehicle does not stop by the goal pose and keep moving forward and backward trying to reach the destination.

[Screencast from 12-06-23 18:32:27.webm](https://github.com/autowarefoundation/autoware.universe/assets/36835765/e87eb83c-e55c-4333-a933-4612b6a0fd74)

### Expected behavior

The vehicle should stop after reaching the goal and end the mission/

### Actual behavior

The vehicle does not stop and keep moving without ending the mission

### Steps to reproduce

1. Open planning simulator
2. Add start pose
3. Add end pose (try to make it a bit deviated from lane center)
4. Engage/Auto

**Comment by kosuke55** [comment]
@ahmeddesokyebrahim 
Thanks for the report. This issue seems to be related to `start_planner` in the behavior path old architecutre, I will check it :pray:

**Comment by kosuke55** [comment]
Fixed in https://github.com/autowarefoundation/autoware.universe/pull/3972
