### ISSUE TITLE
Not easy to see what topic is not ready in autoware state transition

### ISSUE THREAD

**Issue by takayuki5168** [autowarefoundation/autoware.universe#396]

**Comment by kenji-miyake** [comment]
Could you describe your use case more concretely? :pray:

**Comment by takayuki5168** [comment]
As you commented, we can see unrecieved topic from diagnostics
![image](https://user-images.githubusercontent.com/20228327/154246774-33238ad3-1f5b-4306-913f-b70bbcff1dc5.png)

**Comment by takayuki5168** [comment]
Usecase is, just when we launch autoware and autoware state does not transit to the next state because of some bugs or hardware errors, sometimes necessary topics are not published and ad_service_state_monitor detects it.
I want a easy way to see if there is any unrecieved topics or not.

**Comment by kenji-miyake** [comment]
What is the definition of `easy`? And what is difficult with `rqt_robot_monitor`?

**Comment by takayuki5168** [comment]
IMO, seeing unreceived topics from diagnostics takes a bit effort, but to prevent redundancy to check unreceived topics, we do no have to merge the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/397

If you agree, we can close this issue and PR

**Comment by kenji-miyake** [comment]
If you want to merge it, it's better to define the requirements for the UX like this: `Users shall be able to ... when ... because ...`.

**Comment by kenji-miyake** [comment]
We don't want to unnecessarily add debug interfaces, so we have to consider that before implementing them.

**Comment by takayuki5168** [comment]
Now I'm ok to close this issue. (I just didn't know we can see unreceived topics from diagnostics. Sorry to bother you.)

**Comment by kenji-miyake** [comment]
@takayuki5168 No problem! But let's keep in mind to discuss in issues about the approaches to problems before sending PRs! :+1:
