### ISSUE TITLE
`VoxelGridBasedEuclideanCluster` spam logs when an empty cloud is received 

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#4001]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

For example:
```
[component_container-40] Failed to find match for field 'x'.
[component_container-40] Failed to find match for field 'y'.
[component_container-40] Failed to find match for field 'z'.
[component_container-40] [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[component_container-40] Failed to find match for field 'x'.
[component_container-40] Failed to find match for field 'y'.
[component_container-40] Failed to find match for field 'z'.
[component_container-40] [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[component_container-40] Failed to find match for field 'x'.
[component_container-40] Failed to find match for field 'y'.
[component_container-40] Failed to find match for field 'z'.
[component_container-40] [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[component_container-40] Failed to find match for field 'x'.
[component_container-40] Failed to find match for field 'y'.
[component_container-40] Failed to find match for field 'z'.
[component_container-40] [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
```

There are a few cases where it could happen. For example, when the vehicle lidar scan perfectly matches the pointcloud map, the output of `VoxelBasedCompareMapFilterComponent` is empty. 

I think it would be nice to handle this case and avoid meaningless spam. Maybe a timed warning could do.

### Expected behavior

no spam, or at least meaningful messages.
There are many `kdtree->setInputCloud` in autoware, so it took me ages to find which one was having an issue.

### Actual behavior

SPAM

### Steps to reproduce

Edge use case, so difficult to reproduce. Maybe in a simulator it is easier.

**Comment by xmfcx** [comment]
Solved by:
- https://github.com/autowarefoundation/autoware.universe/pull/4029
