### ISSUE TITLE
In the looped path, the stop at temporary stop line is judged simultaneously.

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#423]
To solve the problem, it is necessary to change the distance between the vehicle's position and the stop line to the signed arc length.
![image](https://user-images.githubusercontent.com/8327598/154881154-f0384422-c313-477d-8213-f9e53d816711.png)

Also, when calculating the signed arc length, it is necessary to find out where the vehicle is in the path.
However, the current findNearestIndex does not know whether the looped path will select the position before or after the loop.
We are considering limiting the range of indexes to be searched.

**Comment by taikitanaka3** [comment]
solved by
![image](https://user-images.githubusercontent.com/65527974/158922550-7a37b067-0f15-400c-9ca2-d50d40a229ee.png)
