### ISSUE TITLE
build fail by pcl_ros packages

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#424]
build fail by pcl ros packages
https://github.com/autowarefoundation/autoware.universe/pull/425

# How to reproduce
git clone any [autoware.proj](https://github.com/tier4/autoware.proj) repos 
vcs import src<autoware.proj.repos
setup_ubuntu20.04.sh
colcon build

**Comment by kenji-miyake** [comment]
@taikitanaka3 Please clearly describe the steps to reproduce the problem.

**Comment by taikitanaka3** [comment]
@kenji-miyake 
I added how to reproduce

**Comment by kenji-miyake** [comment]
@taikitanaka3 There was no error in my local environment. So I guess this is a problem that is specific to your environment.

**Comment by taikitanaka3** [comment]
solved by rosdep update already
