### ISSUE TITLE
Unable to use Yabloc with AWSim

### ISSUE THREAD

**Issue by yaukaizhi** [autowarefoundation/autoware.universe#4318]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The yabloc localization module expects to receive a /sensor_msgs/CompressedImage message type, but AWSim only outputs /sensor_msgs/Image on /sensing/camera/traffic_light/image_raw topic

Does this mean yabloc localization is not currently supported on AWSim?

### Expected behavior

yabloc in AWSim

### Actual behavior

no yabloc in AWSim

### Steps to reproduce

Run yabloc localization in AWSim

**Comment by KYabuuchi** [comment]
@yaukaizhi  Hi! Thank you for your interest in YabLoc. 
As you pointed out, YabLoc currently subscribes to `CompressedImage` , which makes it incompatible with AWSIM.

However, you can run YabLoc by converting `Image` to `CompressedImage` using the script provided below. 
If you decide to use this script, please set [use_traffic_light_recognition](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/perception.launch.xml#L71) to **false**. The traffic_light node's decompress operation can cause issues with the script's functionality.

```py
#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from sensor_msgs.msg import CompressedImage
from cv_bridge import CvBridge
from rclpy.qos import QoSProfile, QoSReliabilityPolicy 

class Compressor(Node):
    def __init__(self):
        super().__init__('minimal_publisher')
        qos= QoSProfile(
            reliability=QoSReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT,
            depth=10
        )
        self.publisher_ = self.create_publisher(CompressedImage, '/sensing/camera/traffic_light/image_raw/compressed', qos)
        self.subscription = self.create_subscription(Image, '/sensing/camera/traffic_light/image_raw', self.on_image, qos)
        self.bridge_ = CvBridge()

    def on_image(self, msg):
        self.get_logger().info('subscribed')
        mat= self.bridge_.imgmsg_to_cv2(msg)
        compressed_msg = self.bridge_.cv2_to_compressed_imgmsg(mat)
        compressed_msg.header = msg.header
        self.publisher_.publish(compressed_msg)
        self.get_logger().info('published')


def main(args=None):
    rclpy.init(args=args)
    compressor = Compressor()
    rclpy.spin(compressor)
    compressor.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()

```
