### ISSUE TITLE
unit test of trajectory follower sometimes fails ramdomly

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#432]
https://github.com/autowarefoundation/autoware.universe/runs/5283234004?check_suite_focus=true
https://github.com/autowarefoundation/autoware.universe/runs/5284825263?check_suite_focus=true
![image](https://user-images.githubusercontent.com/65527974/155106546-e86906c9-bb2e-431a-8230-49e2f5205c5d.png)

**Comment by mitsudome-r** [comment]
This is probably fixed in https://github.com/autowarefoundation/autoware.universe/pull/661.
Feel free to re-open the issue if you still see the error.
