### ISSUE TITLE
the path is not generated properly

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#4391]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The path is not appropriately generated in some cases. The generated path is being generated shorter than it should be.

https://github.com/autowarefoundation/autoware.universe/assets/32412808/711e9928-c56e-4175-aa8f-981db77cbc7a

### Expected behavior

This is how the path should look like:

![Screenshot from 2023-07-25 18-41-22](https://github.com/autowarefoundation/autoware.universe/assets/32412808/1e4e3be6-4a0c-4335-a57d-b9dabe4f049e)

### Actual behavior

The path looks like this:

![Screenshot from 2023-07-25 18-41-38](https://github.com/autowarefoundation/autoware.universe/assets/32412808/52db370d-6e86-4a79-97cd-e6344490a707)

### Steps to reproduce

1. Download [map.tar.gz](https://github.com/autowarefoundation/autoware.universe/files/12163055/map.tar.gz)
2. run planning simulator
3. give an init and goal pose

**Comment by kosuke55** [comment]
@beyzanurkaya 
Thank you for your report. This issue seems similar to https://github.com/autowarefoundation/autoware.universe/pull/4109 :thinking: 
Does your branch include this PR? ( or similar issue happens again.

**Comment by beyzanurkaya** [comment]
@kosuke55 similar issue but this problem doesn't occur only in u-turns

**Comment by kosuke55** [comment]
memo:

here
![image](https://github.com/autowarefoundation/autoware.universe/assets/39142679/a5b96a1e-aa5b-4b61-8107-721508362b8a)

NG
![image](https://github.com/autowarefoundation/autoware.universe/assets/39142679/04e04d7b-2238-4c60-abf1-20c74e7398bb)


OK 
![image](https://github.com/autowarefoundation/autoware.universe/assets/39142679/cb1fc859-5e0b-47d6-9a1d-bd211c80081c)

**Comment by kosuke55** [comment]
seems similar but another problem to https://github.com/autowarefoundation/autoware.universe/pull/4109 :thinking:

**Comment by kosuke55** [comment]
memo:

checked https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp#L150-L157


![image](https://github.com/autowarefoundation/autoware.universe/assets/39142679/e76a46cc-c119-40a4-9bbf-6f85299fe38e)

```
[component_container_mt-27] goal_is_behind: 0, s_start: 74.5449, s_end: 93.0561
[component_container_mt-27] road_lanes: 2039, 2062, 2071, 2100, 8350, 1663, 8401, 1747, 8462, 1801, 8580, 1816, 8457, 1786, 8405, 1674, 8364, 2270,
```

the road_lanes is wrong maybe because of getExtendedCurrentLanes.
need to check the extended lane is road_lanes and add that as possible.
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/utils/utils.cpp#L2857

**Comment by kosuke55** [comment]
fixed in https://github.com/autowarefoundation/autoware.universe/pull/4418

![image](https://github.com/autowarefoundation/autoware.universe/assets/39142679/8828ea90-7f08-4341-9f67-f7a4a4be3f6c)

**Comment by beyzanurkaya** [comment]
@kosuke55 thank you, I'll close the issue then

**Comment by mehmetdogru** [comment]
Lets close the issue after the PRs Kosuke-san opened. @beyzanurkaya please test the PRs if possible https://github.com/autowarefoundation/autoware.universe/pull/4418
https://github.com/autowarefoundation/autoware.universe/pull/4422

**Comment by kosuke55** [comment]
I have merged the PRs, so please let me know if the problem still exists.

**Comment by beyzanurkaya** [comment]
@mehmetdogru @kosuke55 I tested https://github.com/autowarefoundation/autoware.universe/pull/4418 and https://github.com/autowarefoundation/autoware.universe/pull/4422. This problem seems to no longer exist.
