### ISSUE TITLE
Improve CI efficiency on build-and-test-differential jobs

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware.universe#4497]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

 We have so many [`build-and-test-differential` jobs queued up.](https://github.com/autowarefoundation/autoware.universe/actions/workflows/build-and-test-differential.yaml?query=is%3Aqueued)

<details>
  <summary>18 Jobs waiting in queue</summary>

![Screenshot from 2023-08-01 18-16-31](https://github.com/autowarefoundation/autoware.universe/assets/10751153/1208d6ea-3e0d-497a-9bc2-e761720f9498)

</details>

We currently have 2 runners just dedicated to run them.
1. ec2 c6a.xlarge: 4c4t (EPYC V3) 8gb
2. leo-copper pc: 4c8t (7820HK) 32gb

And these machines are just dedicated to run this `build-and-test-differential` and `clang-tidy-differential` actions only.

`clang-tidy-differential` is not a required job, maybe we can think about disabling it too, we can discuss this in another issue.

But still, they take so much time on build action.

A good example to analyze is this job:
[feat(crosswalk): suppress chattering of GO/STOP decision](https://github.com/autowarefoundation/autoware.universe/actions/runs/5725728049/job/15514775990)

Here, in [Get modified packages](https://github.com/autowarefoundation/autoware.universe/actions/runs/5725728049/job/15514775990#step:5:13) the only package to be built is: `behavior_velocity_crosswalk_module`
It's the only modified package.

In the build job, it then runs [`colcon build --packages-above-and-dependencies behavior_velocity_crosswalk_module`](https://github.com/autowarefoundation/autoware.universe/actions/runs/5725728049/job/15514775990#step:6:137)

This is a big problem because it will now build the following packages :astonished::
`autoware$ colcon list --packages-above-and-dependencies behavior_velocity_crosswalk_module --names-only`

<details>
  <summary>186 packages</summary>

1. ad_api_adaptors
1. automatic_pose_initializer
1. autoware_ad_api_specs
1. autoware_adapi_v1_msgs
1. autoware_adapi_version_msgs
1. autoware_auto_common
1. autoware_auto_control_msgs
1. autoware_auto_geometry
1. autoware_auto_geometry_msgs
1. autoware_auto_mapping_msgs
1. autoware_auto_perception_msgs
1. autoware_auto_planning_msgs
1. autoware_auto_system_msgs
1. autoware_auto_tf2
1. autoware_auto_vehicle_msgs
1. autoware_cmake
1. autoware_common_msgs
1. autoware_control_msgs
1. autoware_external_api_msgs
1. autoware_iv_external_api_adaptor
1. autoware_iv_internal_api_adaptor
1. autoware_launch
1. autoware_lint_common
1. autoware_map_msgs
1. autoware_perception_msgs
1. autoware_planning_msgs
1. autoware_point_types
1. autoware_testing
1. autoware_utils
1. awapi_awiv_adapter
1. behavior_path_planner
1. behavior_velocity_blind_spot_module
1. behavior_velocity_crosswalk_module
1. behavior_velocity_detection_area_module
1. behavior_velocity_intersection_module
1. behavior_velocity_no_drivable_lane_module
1. behavior_velocity_no_stopping_area_module
1. behavior_velocity_occlusion_spot_module
1. behavior_velocity_out_of_lane_module
1. behavior_velocity_planner
1. behavior_velocity_planner_common
1. behavior_velocity_run_out_module
1. behavior_velocity_speed_bump_module
1. behavior_velocity_stop_line_module
1. behavior_velocity_traffic_light_module
1. behavior_velocity_virtual_traffic_light_module
1. behavior_velocity_walkway_module
1. compare_map_segmentation
1. component_interface_specs
1. component_interface_utils
1. component_state_monitor
1. costmap_generator
1. crosswalk_traffic_light_estimator
1. cuda_utils
1. default_ad_api
1. detected_object_feature_remover
1. detected_object_validation
1. detection_by_tracker
1. dummy_perception_publisher
1. eagleye_coordinate
1. eagleye_fix2pose
1. eagleye_gnss_converter
1. eagleye_msgs
1. eagleye_navigation
1. eagleye_rt
1. ekf_localizer
1. emergency_handler
1. euclidean_cluster
1. external_cmd_converter
1. external_cmd_selector
1. external_velocity_limit_selector
1. fake_test_node
1. fault_injection
1. freespace_planner
1. freespace_planning_algorithms
1. global_parameter_loader
1. grid_map_utils
1. ground_segmentation
1. gyro_odometer
1. image_projection_based_fusion
1. image_transport_decompressor
1. interpolation
1. kalman_filter
1. lane_departure_checker
1. lanelet2_extension
1. lidar_apollo_instance_segmentation
1. lidar_centerpoint
1. llh_converter
1. map_based_prediction
1. map_height_fitter
1. map_loader
1. map_tf_generator
1. mission_planner
1. motion_utils
1. motion_velocity_smoother
1. mpc_lateral_controller
1. multi_object_tracker
1. mussp
1. ndt_omp
1. ndt_scan_matcher
1. object_merger
1. object_range_splitter
1. object_recognition_utils
1. object_velocity_splitter
1. obstacle_avoidance_planner
1. obstacle_cruise_planner
1. obstacle_stop_planner
1. occupancy_grid_map_outlier_filter
1. osqp_interface
1. path_distance_calculator
1. perception_utils
1. pid_longitudinal_controller
1. planning_evaluator
1. planning_test_utils
1. planning_validator
1. pointcloud_preprocessor
1. pointcloud_to_laserscan
1. pose_initializer
1. probabilistic_occupancy_grid_map
1. pure_pursuit
1. radar_crossing_objects_noise_filter
1. radar_fusion_to_detected_object
1. radar_object_clustering
1. radar_object_tracker
1. raw_vehicle_cmd_converter
1. route_handler
1. rtc_auto_mode_manager
1. rtc_interface
1. rtklib_msgs
1. scenario_selector
1. shape_estimation
1. shift_decider
1. signal_processing
1. simple_planning_simulator
1. surround_obstacle_checker
1. system_error_monitor
1. system_monitor
1. tensorrt_classifier
1. tensorrt_common
1. tensorrt_yolo
1. tensorrt_yolox
1. tier4_api_msgs
1. tier4_api_utils
1. tier4_auto_msgs_converter
1. tier4_autoware_api_launch
1. tier4_autoware_utils
1. tier4_control_launch
1. tier4_control_msgs
1. tier4_debug_msgs
1. tier4_external_api_msgs
1. tier4_localization_launch
1. tier4_localization_msgs
1. tier4_map_launch
1. tier4_map_msgs
1. tier4_pcl_extensions
1. tier4_perception_launch
1. tier4_perception_msgs
1. tier4_planning_launch
1. tier4_planning_msgs
1. tier4_rtc_msgs
1. tier4_sensing_launch
1. tier4_simulation_msgs
1. tier4_simulator_launch
1. tier4_system_launch
1. tier4_system_msgs
1. tier4_v2x_msgs
1. tier4_vehicle_launch
1. tier4_vehicle_msgs
1. topic_state_monitor
1. traffic_light_arbiter
1. traffic_light_classifier
1. traffic_light_fine_detector
1. traffic_light_map_based_detector
1. traffic_light_multi_camera_fusion
1. traffic_light_occlusion_predictor
1. traffic_light_utils
1. traffic_light_visualization
1. trajectory_follower_base
1. trajectory_follower_node
1. vehicle_cmd_gate
1. vehicle_info_util
1. yabloc_common
1. yabloc_image_processing
1. yabloc_monitor
1. yabloc_particle_filter
1. yabloc_pose_initializer
  
</details>

And these 186 packages include the infamous `behavior_path_planner` and almost all of the `behavior_velocity_x_module`s.

This is a waste of time and we can avoid all these and only build the single package. I will explain the plan below.

### Purpose

- To reduce the time wasted in CI machines
- To reduce the queue in CI
- To help users get feedback from CI faster

### Possible approaches

It's simple.

#### Approach 1, upload and download the build artifact

After a commit is made to the main branch,
- Update the packages to whatever latest, similar to the build
- Build the entire Autoware at that time (basically [build-and-test job](https://github.com/autowarefoundation/autoware.universe/actions/runs/5727526598/job/15520116853))
- Upload the compressed `autoware` folder as an artifact. (These are stored for 90 days by default, we can also increase the duration.)
- In this `build-and-test-differential` job, after pulling the build environment, we run [download-workflow-artifact](https://github.com/marketplace/actions/download-workflow-artifact) to download the artifact from that workflow.
- We decompress the `autoware` folder and checkout to this repository's branch in `autoware.universe`.
- Now that we have everything already built,
   - Instead of `colcon build --packages-above-and-dependencies`
   - We can run `colcon build --packages-select`
   - For the example given above, we will only build a single package.

#### Approach 2 (preferred), push the built version as a docker image

Another approach can be to build a docker image in the `build-and-test` with following layers:
- base image
- the changes made to update the system
- the changes made to build the autoware
And push it to the registry.

`build-and-test-differential` job can use this image as the base image.

This is much simpler and can be achieved faster probably.

With these approaches,
[feat(crosswalk): suppress chattering of GO/STOP decision](https://github.com/autowarefoundation/autoware.universe/actions/runs/5725728049/job/15514775990) will take like 4m instead of 40m

#### Approach 1:

- [ ] Modify the [build-and-test.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/build-and-test.yaml) to upload the artifact after it successfully builds.
- [ ] Modify the [build-and-test-differential.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/build-and-test-differential.yaml) to:
   - [ ] Download the artifact using [download-workflow-artifact](https://github.com/marketplace/actions/download-workflow-artifact)
   - [ ] Extract and use it as the `autoware` folder instead of pulling
   - [ ] Also pull the latest branch in the `autoware.universe` repository
   - [ ] Build only the packages modified, not their dependencies

#### Approach 2 (preferred):

- [ ] Modify the [build-and-test.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/build-and-test.yaml) to build and push the `prebuilt` image of the `autoware`.
- [ ] Modify the [build-and-test-differential.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/build-and-test-differential.yaml) to:
   - [ ] Pull the `prebuilt` image instead
   - [ ] Also pull the latest branch in the `autoware.universe` repository
   - [ ] Build only the packages modified, not their dependencies

**Comment by xmfcx** [comment]
cc. @mitsudome-r @shmpwk @esteve

**Comment by xmfcx** [comment]
I didn't take [--packages-above](https://colcon.readthedocs.io/en/released/reference/package-selection-arguments.html#package-selection-arguments) into consideration.

> --packages-above [PKG_NAME [PKG_NAME …]]
>     Select the packages with the passed names as well as packages which recursively depend on them. 

So we should use this parameter.
I will also check how many packages are there with `--packages-above`, compared to `--packages-above-and-dependencies`

**Comment by xmfcx** [comment]
Related: https://github.com/orgs/autowarefoundation/discussions/3469#discussioncomment-5965946

**Comment by kminoda** [comment]
Thank you for the proposal @xmfcx. Let me ask a minor question that came up in my mind:

How do you think we can guarantee that all the build-and-test-differential CIs can access the latest build artifacts? I understood that both approach assumes that the build artifacts of the dependency packages are from the latest `main`, and may fail if this assumption breaks (correct me if I am wrong). I am not sure how flexible we can manage the order of CIs in GitHub Actions, but I guess it may be difficult to guarantee above statement if we consider multiple PRs created and merged in arbitrary order.

**Comment by esteve** [comment]
@xmfcx thanks for the proposal. One issue I see with this approach is that we'd have to be very strict about API and ABI versioning when a module changes. In the example you provided, if the module changed its API or ABI, or if it were a messages package that changed a message definition, we would still need to build the downstream packages. AFAIK, neither API, ABI or messages have been formally stabilized, so any package is still free to change anything and the downstream packages would need to be updated.

**Comment by xmfcx** [comment]
@esteve let's consider following scenario:

```mermaid
graph TD
    F:::cls_01 -->|"depends on"| D:::cls_03
    D -->|"depends on"| E:::cls_02
    D -->|"depends on"| C:::cls_04
    C-->|"depends on"| B:::cls_05
    B -->|"depends on"| A:::cls_06

classDef cls_00 fill:#DDDDDD,stroke:#999,stroke-width:1px;
classDef cls_01 fill:#FBF8CC,stroke:#999,stroke-width:1px;
classDef cls_02 fill:#FDE4CF,stroke:#999,stroke-width:1px;
classDef cls_03 fill:#FFCFD2,stroke:#999,stroke-width:1px;
classDef cls_04 fill:#F1C0E8,stroke:#999,stroke-width:1px;
classDef cls_05 fill:#CFBAF0,stroke:#999,stroke-width:1px;
classDef cls_06 fill:#A3C4F3,stroke:#999,stroke-width:1px;
```

Here the **Package C** is changed/updated package.

```console
$ colcon list --packages-up-to C
A, B, C

$ colcon list --packages-above C
C, D, F

$ colcon list --packages-above-depth 1 C
C, D

$ colcon list --packages-above-and-dependencies C
A, B, C, D, E, F
```

Keeping these in mind, Let's assume everything is compiled with `colcon build`

Then, **Package C** is changed.

Now, recompiling **Package C** and **Package D** should suffice. (`colcon list --packages-above-depth 1 C`)
No need to recompile **Package F** since it's not directly dependent on **Package C**.

But current implementation builds every package out there **(A, B, C, D, E, F)** since because the build artifacts from the latest build is not present.

My proposal just tells it to rebuild and test **C** and **D**, and that's it.

How is this related to API/ABI compatibility?

**Comment by xmfcx** [comment]
@kminoda one way is to store the build artifacts with the commit hash of the universe repository. Then we can check if they match. If they don't match, the job fails.

We can print a sensible message to retry the job once the main build artifact is present.

**Comment by esteve** [comment]
@xmfcx 

Thanks for the explanation, I see it more clearly now. It may work if we only build C and D, however, transitve dependencies (e.g. `_export` tags) and `-extras.cmake` files may cause problems, though, but I think we barely use them and always declare all the dependencies in downstream packages.

> How is this related to API/ABI compatibility?

If C changes its API/ABI and we don't rebuild D, we wouldn't catch any incompatibilities, but I see now that you're proposing to rebuild D as well.

**Comment by oguzkaganozt** [comment]
@xmfcx 

Even Approach 2 seems more elegant we would need to create a new container, copy artifacts into the new container and save the container into registry to later use it in **build-test-differential**. Instead we can save our artifacts with the commit hash then download them into **build-test-differential** job. Am I missing something ?

**Comment by xmfcx** [comment]
Will be hopefully solved by:
- https://github.com/autowarefoundation/autoware/issues/3999

**Comment by xmfcx** [comment]
Now that
- https://github.com/autowarefoundation/autoware/issues/3999

is completed, we can close this. ✨🎇

**Comment by ambroise-arm** [comment]
@xmfcx Looking at [build-and-test-differential](https://github.com/autowarefoundation/autoware.universe/actions/runs/8184535807/job/22379153019#logs) we are still doing `rosdep install` and `colcon build` on `--packages-above-and-dependencies` and not `--packages-above-depth 1` as proposed in https://github.com/autowarefoundation/autoware.universe/issues/4497#issuecomment-1695694729. Is that on purpose?

I think it works well in theory, although I am not convinced that all packages declare their direct dependencies. For example in the case of:
```
   ┌─┐    
┌──┤C├──┐ 
│  └─┘  │ 
│       ▼ 
│      ┌─┐
│      │B│
│      └┬┘
│  ┌─┐  │ 
└─►│A│◄─┘ 
   └─┘    
```
I can perfectly see `C` only listing `B` and relying on its dependency to `A`. In which case doing `--packages-above-depth 1` on `A` will not test the `A`/`C` interface. However, note that I didn't try to look for an example of this happening and it might be an irrelevant concern.

**Comment by xmfcx** [comment]
@ambroise-arm thanks for reminding this, It's been so long, I forgot the real premise of my proposal 😅

To recap:
- Our docker images were too big for public runners
- We started running these workflows on self hosted runners
- We didn't have many, jobs sometimes piled up and caused this problem

Then,
- https://github.com/autowarefoundation/autoware/issues/3999 was merged yesterday
  - Images are small again, they now run on public runners
  - They also now use ccache artifacts in the prebuilt image, speeding things up much more compared to what we had before

But looking at this again, @esteve has been fixing the dependencies for all the packages for a while now.
I think we can give `--packages-above-depth 1` option a shot.

Even if we have some failures, we will detect them once the https://github.com/autowarefoundation/autoware.universe/actions/workflows/build-and-test.yaml is triggered (it runs everytime something is merged to universe main) and we will have time to update the incorrect dependencies.

I will create a PR to modify it such.

**Comment by xmfcx** [comment]
We would need to restructure colcon-build action from autoware-github-actions and sync it with Universe repo.

- https://github.com/autowarefoundation/autoware-github-actions/blob/8ce979ef277058cd28af34ebecf35347e658b576/colcon-build/action.yaml#L53-L85

Currently this is too much work for relatively little benefit (compared to the time when I had opened up this issue), will mark this as a low priority issue.

I will un-assign myself and leave this open.

**Comment by ambroise-arm** [comment]
>but since we won't have the build artifacts as in build and install folders from most recent successful previous run, we will need to combine:
>
>```console
> $ colcon list --packages-above-depth 1 C && colcon list --packages-up-to C
>A, B, C, D
>```
>
> We still need to build dependencies under.

We have the `install` directory in the prebuilt image. And I think that's enough. Doing `source` on the install artifacts I can then do:
```
root@f66d64e2081b:/autoware/autoware.universe# colcon build --packages-select pure_pursuit
Starting >>> pure_pursuit
[3.802s] WARNING:colcon.colcon_core.shell:The following packages are in the workspace but haven't been built:
- osqp_interface
- tier4_autoware_utils
- interpolation
- vehicle_info_util
- motion_utils
- trajectory_follower_base
They are being used from the following locations instead:
- /autoware/install/osqp_interface
- /autoware/install/tier4_autoware_utils
- /autoware/install/interpolation
- /autoware/install/vehicle_info_util
- /autoware/install/motion_utils
- /autoware/install/trajectory_follower_base
To suppress this warning ignore these packages in the workspace:
--packages-ignore osqp_interface tier4_autoware_utils interpolation vehicle_info_util motion_utils trajectory_follower_base
[Processing: pure_pursuit]                         
[Processing: pure_pursuit]                                     
Finished <<< pure_pursuit [1min 7s]                             

Summary: 1 package finished [1min 10s]
```

**Comment by xmfcx** [comment]
> EDIT: Oh, was "from most recent successful previous run" the important part? Yeah, that might be a problem.

Exactly, this requires a good orchestration effort. Uploading most recent successful main branch run artifacts and retrieving them in the build-and-test-differential jobs.

**Comment by esteve** [comment]
> But looking at this again, @esteve has been fixing the dependencies for all the packages for a while now.
I think we can give --packages-above-depth 1 option a shot.

Yeah, I agree, we can give it a try.

**Comment by xmfcx** [comment]
Closing this in favor of:
- https://github.com/autowarefoundation/autoware.universe/issues/7501
