### ISSUE TITLE
build  tier4_simulated_clock_rviz_plugin failed

### ISSUE THREAD

**Issue by lpxiangyan9** [autowarefoundation/autoware.universe#4504]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

build autoware.universe 
throws exception 
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qspinbox.h:90:5: error: ‘StepType’ does not name a type
   90 |     StepType stepType() const;
      |     ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qspinbox.h:91:22: error: ‘StepType’ has not been declared
   91 |     void setStepType(StepType stepType);
      |                      ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qspinbox.h:155:5: error: ‘StepType’ does not name a type
  155 |     StepType stepType() const;
      |     ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qspinbox.h:156:22: error: ‘StepType’ has not been declared

### Expected behavior

success

### Actual behavior

faild

### Steps to reproduce

rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
success
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

### Versions

-os:ubuntu 20.04
-ROS2:galactic
-autoware:autoware.universe

**Comment by maxime-clem** [comment]
Thank you for reporting this issue.
This looks like a problem with the version of `qt5`. Which version do you have installed ?
For me:
```
▶ qmake --version
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu
```

**Comment by lpxiangyan9** [comment]
> Thank you for reporting this issue. This looks like a problem with the version of `qt5`. Which version do you have installed ? For me:
> 
> ```
> ▶ qmake --version
> QMake version 3.1
> Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu
> ```

Qmake version 3.1 and qt version 5.9.7

**Comment by maxime-clem** [comment]
The `StepType` was added in version `5.12` (https://doc.qt.io/archives/qt-5.12/qabstractspinbox.html).
If possible please update your Qt version and the issue should be solved.

**Comment by lpxiangyan9** [comment]
> The `StepType` was added in version `5.12` (https://doc.qt.io/archives/qt-5.12/qabstractspinbox.html). If possible please update your Qt version and the issue should be solved.

now, i update qt to 5.15.2 but Successfully compiled polar_ Grid build  failed

error: ‘QMetaObject::SuperData’ has not been declared
   81 |     QMetaObject::SuperData::link<rviz_common::Display::staticMetaObject>(),
      |                  ^~~~~~~~~
~/autowarefoundation/autoware/build/polar_grid/polar_grid_autogen/UVLADIE3JM/moc_polar_grid_display.cpp:81:74: error: expected primary-expression before ‘)’ token
   81 |     QMetaObject::SuperData::link<rviz_common::Display::staticMetaObject>(),
      |                                                                          ^

**Comment by maxime-clem** [comment]
Can you try again after cleaning up the previous build files (which were using the old version of qt) ?
You can do `rm build/ install/ -rf` in your workspace.

**Comment by lpxiangyan9** [comment]
> Can you try again after cleaning up the previous build files (which were using the old version of qt) ? You can do `rm build/ install/ -rf` in your workspace.

OK i sloved this problm 
use qt 5.12.12  version .
autoware.universer galactic branch  must use qt 5.12 or 5.13 . i try 5.15  polar_ Grid  build  faild because QT. Version greater than 13 does not support this code method
