### ISSUE TITLE
`/perception/traffic_light_recognition/traffic_signals` message type inconsistency

### ISSUE THREAD

**Issue by lchojnack** [autowarefoundation/autoware.universe#4510]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Trying to subscribe the `/perception/traffic_light_recognition/traffic_signals` topic, I've got the message
```
Cannot echo topic '/perception/traffic_light_recognition/traffic_signals', as it contains more than one type: [autoware_auto_perception_msgs/msg/TrafficSignalArray, autoware_perception_msgs/msg/TrafficSignalArray]
```

The issue appears because `traffic_light_arbiter` node publishes the message with type `autoware_perception_msgs/msg/TrafficSignalArray` and `behavior_velocity_planner` [subscribes the topic](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/src/node.cpp#L104) with `autoware_auto_perception_msgs/msg/TrafficSignalArray` type as presented in the picture below

![Screenshot_20230803_153847](https://github.com/autowarefoundation/autoware.universe/assets/8416175/bfec1d38-e88b-4f1f-897e-9e4bf2ac65cd)

### Expected behavior

It is possible to subscribe the `/perception/traffic_light_recognition/traffic_signals` by using `ros2 topic echo` command

### Actual behavior

<img width="1394" alt="Screenshot_20230803_155257" src="https://github.com/autowarefoundation/autoware.universe/assets/8416175/e57fd901-879c-47c8-a35d-a313c34353fb">

### Steps to reproduce

1. Run Autoware e.g.
```
ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=$HOME/autoware_map/nishishinjuku_autoware_map/
````
2. In another terminal run
```
ros2 topic echo /perception/traffic_light_recognition/traffic_signals
```

### Versions

- OS: Ubuntu 22.04
- ROS: humble
- autoware.universe branch `main`  commit `2f282edb474aabb071746e4ed0f6ff2b0f3403db`

**Comment by isamu-takagi** [comment]
Looks like this PR (https://github.com/autowarefoundation/autoware.universe/pull/4133) will solve it.
