### ISSUE TITLE
Planning module generates infeasible trajectory.

### ISSUE THREAD

**Issue by Kim-mins** [autowarefoundation/autoware.universe#4559]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hi team,
I'm currently running Autoware on Carla, and I just observed a strange trajectory during the driving.
Here's a video and `launch.log` for better understanding: [[video 1](https://drive.google.com/file/d/1JY7WamWEGDm6gjYEpnwERUGjUCFtO5F9/view?usp=sharing)] [[video 2](https://drive.google.com/file/d/1PtP8LFlR0XJKlqjQKKIPxzVW6x3LZBXy/view?usp=sharing)] [[launch.log](https://drive.google.com/file/d/1fGq8UHHv3JIjlpEbxDKlL6rXiklTZ5_T/view?usp=sharing)]

On video 1, you can see that the (seemingly) good and bad trajectories are competing each other, but the ego vehicle eventually follows the one that seems infeasible.

 Actually, the issue occurs while driving at a tunnel. Please refer to the second video from **4:20**.

### Expected behavior

I expected only the feasible path to be generated.

### Actual behavior

The seemingly infeasible path is generated and the ego vehicle follows the path.

### Steps to reproduce

[[rosbag file](https://drive.google.com/drive/folders/1Bp4MVBYtonTDDFuPjNg8OhxEvNZxMoPw?usp=sharing)]

Actually, I cannot reproduce without the rosbag file.
I could not encounter this situation anymore with my current version(Autoware version: 2023/02/15), and I also could not reproduce the same issue on the recent one(Autoware version: 2023/07/15).

### Versions

I ran the experiment on the container from the image [here](https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/70625594?tag=humble-20230215-prebuilt-cuda-amd64).
Carla version: 0.9.13

**Comment by maxime-clem** [comment]
I am closing this old issue as it could not be reproduced with more recent versions of Autoware.
If a similar issue occurs again, let's reopen the issue.
![image](https://github.com/autowarefoundation/autoware.universe/assets/78338830/23016aad-a2e2-43fc-abbc-511e51b8568c)
