### ISSUE TITLE
Rviz plugin `tier4_localization_rviz_plugin/InitialPoseButtonPanel` does not exists

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#4848]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I just pulled latest Autoware and am testing it. When I start autoware, rviz reports the following error:
```
[rviz2-74] [ERROR 1693558088.618417957] [rviz2]: PluginlibFactory: The plugin for class 'tier4_localization_rviz_plugin/InitialPoseButtonPanel' failed to load. Error: According to the loaded plugin descriptions the class tier4_localization_rviz_plugin/InitialPoseButtonPanel with base class type rviz_common::Panel does not exist. Declared types are  AutowareDateTimePanel AutowareScreenCapturePanel rviz_plugins/ManualController rviz_plugins::AutowareAutomaticGoalPanel rviz_plugins::AutowareStatePanel rviz_plugins::BagTimeManagerPanel rviz_plugins::RTCManagerPanel rviz_plugins::SimulatedClockPanel rviz_plugins::TrafficLightPublishPanel rviz_plugins::VelocitySteeringFactorsPanel tier4_adapi_rviz_plugins::RoutePanel tier4_calibration_rviz_plugin/AccelBrakeMapCalibratorButtonPanel (operator()() at ./src/main.cpp:68)
```

So apparently, `tier4_localization_rviz_plugin/InitialPoseButtonPanel` plugin is missing on my machine. But I can't find it anywhere:
```
$ rg -l InitialPoseButtonPanel src
src/universe/autoware.universe/planning/obstacle_avoidance_planner/rviz/obstacle_avoidance_planner.rviz
src/universe/autoware.universe/planning/static_centerline_optimizer/rviz/static_centerline_optimizer.rviz
src/universe/autoware.universe/vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/rviz/occupancy.rviz
src/universe/autoware.universe/perception/lidar_centerpoint/launch/centerpoint_vs_centerpoint-tiny/rviz/centerpoint.rviz
src/universe/autoware.universe/perception/lidar_centerpoint/launch/centerpoint_vs_centerpoint-tiny/rviz/centerpoint_tiny.rviz
src/launcher/autoware_launch/autoware_launch/rviz/autoware.rviz
```

Where is this plugin supposed to be built?

### Expected behavior

No error on startup

### Actual behavior

error message on startup

### Steps to reproduce

Launch autoware?

**Comment by YamatoAndo** [comment]
@VRichardJP Hi.
That package was recently removed. https://github.com/autowarefoundation/autoware.universe/pull/4519

**Comment by VRichardJP** [comment]
In that case, the .rviz config files should be updated accordingly, right?

**Comment by YamatoAndo** [comment]
@VRichardJP Yes! you are right.
Sorry, I forgot to remove it from the .rviz config files.
