### ISSUE TITLE
Vehicle stopped in planning simulator near roundabout 

### ISSUE THREAD

**Issue by brkay54** [autowarefoundation/autoware.universe#4972]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

While testing our map in planning_simulator, I realized that the vehicle stopping always while turning roundabout. 
Then we realized that after the vehicle stopped, the drivable area marker changed. I added a video to see the problem.

https://github.com/autowarefoundation/autoware.universe/assets/45468306/16b9d479-7868-477a-b6e8-37409d82d8dc

--- 

Also, I got the same problem at the different roundabout:

https://github.com/autowarefoundation/autoware.universe/assets/45468306/1d1d9acd-f6bc-4bcd-938a-532bae4f2502

### Expected behavior

The vehicle should not change its velocity to zero.

### Actual behavior

The vehicle stops at the nearby roundabout and after that drivable area marker changes and starts driving. I think it is because of some bugs in the drivable area package.

### Steps to reproduce

-

### Versions

-

### Possible causes

-

**Comment by mehmetdogru** [comment]
@brkay54 Thank you for creating the issue. 

Could you create a scenario and share it here (under steps the reproduce section) with the HD-Map you used to create the scenario?

**Comment by VRichardJP** [comment]
Looking at the lanelet2 map and symptoms, I think it could be the same problem as in https://github.com/autowarefoundation/autoware.universe/issues/3368#issuecomment-1508048547

**Comment by mehmetdogru** [comment]
@beyzanurkaya

Could you create a scenario and share it here (under steps the reproduce section) with the HD-Map you used to create the scenario?

**Comment by beyzanurkaya** [comment]
@mehmetdogru 

This one is the 14th November Autoware Test;

https://github.com/autowarefoundation/autoware.universe/assets/32412808/8e1be247-e42b-4b4d-afb6-ed5d3569c0ba

This one is the today Autoware Test;


https://github.com/autowarefoundation/autoware.universe/assets/32412808/a18ab6e2-5136-40a3-9356-7c02f2d896fa

Then this was the commit that solved this problem: https://github.com/autowarefoundation/autoware.universe/commit/32f0547d62e0e031708dc92ea59de254e1de56a5
