### ISSUE TITLE
Pointcloud concatenation fails while input data is empty

### ISSUE THREAD

**Issue by amadeuszsz** [autowarefoundation/autoware.universe#5010]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Recently, I struggled with the random dying of an entire pointcloud container after integrating a second sensor. I guess the bug fix #3814 generated a new one which provides possible `nullptr` currently [here](https://github.com/autowarefoundation/autoware.universe/blob/9da75550cb9cc512287a35546256fa8e254daa8e/sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp#L463). I've used Ouster lidars and as I noticed, there is a high probability that during initialization the sensor / driver may produce empty pointcloud data. Quick fix solves the issue.

### Expected behavior

Skipping empty data.

### Actual behavior

Pointcloud container with all components dies.

### Steps to reproduce

1. Provide dummy topic with empty data or just cover / tape the lidar sensor.
2. Run concatenate_data_node from pointcloud_preprocessor package.

**Comment by kyoichi-sugahara** [comment]
@amadeuszsz 
Sorry if it's not helpful but I hope this information is useful.
In the planning (and control) module, node dying happens often when empty trajectory/path/pose is received.
So we created test for some node (not for all node) to check node doesn't get died when empty input is given.
I introduced [here](https://github.com/autowarefoundation/autoware.universe/issues/3723).
With this kind of test, if you implement some fearture/function teat will fail and you can't merge the PR.
So it may be useful to avoid the described issue.
