### ISSUE TITLE
Expanding rviz plugins (perception, planning, localization, debug, etc...)

### ISSUE THREAD

**Issue by satoshi-ota** [autowarefoundation/autoware.universe#533]
Add useful rviz plugin tools to accelerate the development of autoware.

**Comment by mitsudome-r** [comment]
Do you still have any other tools that you are thinking of? If so, please list them up in the issue description.

**Comment by satoshi-ota** [comment]
@mitsudome-r No, I don't. So, I will close this issue. (If I need new tools, I'll re-open this issue.)
