### ISSUE TITLE
Max steer angle parameter is defined in each package, not in vehicle_info package

### ISSUE THREAD

**Issue by takayuki5168** [autowarefoundation/autoware.universe#535]
Since max steer angle parameter is not in the vehicle_info package, this parameter is defined in each packages' yaml file.

**Comment by takayuki5168** [comment]
cc @satoshi-ota

**Comment by takayuki5168** [comment]
Max jerk, acceleration, velocity are the same. (should be in vehicle_info package)

**Comment by takayuki5168** [comment]
@satoshi-ota @kenji-miyake 
Do you agree, and if so, do you have any other parameters to include in the `vehicle_info` package.

**Comment by kenji-miyake** [comment]
cc @yukkysaito @mitsudome-r @xmfcx 
I agree that we should manage `max_steer_angle` as a global parameter.
For what else, I have no concrete ideas, but I feel they should be categorized like `shape`, `hard_limit`, `soft_limit`, etc.

Also, as a long-term issue, we should write a design document for global parameters and re-design some packages for Autoware Core.

**Comment by takayuki5168** [comment]
@kenji-miyake 
We've already commonized max and min acceleration and jerk. It may be better to write max and min velocity as well here though.
https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_planning_launch/config/scenario_planning/common/common.param.yaml

For the `vehicle_info` package, I don't have any parameters other than `max_steer_angle` so far.

@TakaHoribe 
Could you give us your opinion.

**Comment by TakaHoribe** [comment]
I agree to have `max_steer_angle` in the vehicle_info data. There already are some packages defining max_steer value in their local and it's getting messy.

About the velocity, it may be ok to have the max_velocity in the planning common param. In my opinion, we could have two max_velocity: `normal.max_velocity` and `limit.max_velocity`. They are like, "follow the limit if possible" and "vehicle must follow the limit". However the definition of the `normal` and `limit` is a little vague, so it'd be nice to add more detailed description for them when we add a max_velocty.

**Comment by takayuki5168** [comment]
I'm thinking about the name of the parameter, `max_steer_angle` or `max_tire_angle`. I'm not sure if `max_steer_angle` is confusing for non-Japanese people.

@xmfcx Could you tell me your opinion.

**Comment by xmfcx** [comment]
@takayuki5168 I think `max_steer_angle` is ok. 

![image](https://user-images.githubusercontent.com/10751153/164230504-0f264013-1fc7-44cd-b3a1-e2d75fcd03e8.png)

Reference: http://street.umn.edu/VehControl/javahelp/HTML/Definition_of_Vehicle_Heading_and_Steeing_Angle.htm

**Comment by xmfcx** [comment]
@TakaHoribe 

> About the velocity, it may be ok to have the max_velocity in the planning common param. In my opinion, we could have two max_velocity: `normal.max_velocity` and `limit.max_velocity`. They are like, "follow the limit if possible" and "vehicle must follow the limit".

What is the difference between these 2? 

Why is a single speed limit not enough, like vehicle is never allowed to go over 50kmph?

The other speed limits are road related, not vehicle.

**Comment by takayuki5168** [comment]
@TakaHoribe @kenji-miyake @xmfcx cc @tkimura4 @h-ohta 
We found that `max_steer_angle` is not required for the differential wheeled robot.

So how about the following `vehicle_info.param.yaml`?
Any major/minor comment would be welcome!
```
/**:
  ros__parameters:
    wheel_radius: 0.39
    wheel_width: 0.42
    ...
    vehicle_height: 2.5

    vehicle_model: "differential_model" # select the vehicle model from differential_model or bicycle_model

    differential_model:
        # if there is any parameter for differential model.
    bicycle_model:
        max_steer_angle: 0.70 # [rad]
```

**Comment by takayuki5168** [comment]
@TakaHoribe What do you think.

**Comment by TakaHoribe** [comment]
> What is the difference between these 2?

@xmfcx In my mind, just one velocity limit is enough.
However, the concept of 2 limits (e.g normal.max_acc and limit.max_acc) is that different accelerations are use for emergency situations (like, a very large acceleration is required to avoid a risk) and non-emergency situations. And I think it is reasonable.

So we can apply the same idea to the velocity limit as well, that is, the two velocity limits for regular and emergency situations. For example, in the case of merging, ego-vehicle may sometimes need to accelerate beyond the velocity limit to avoid a collision to the behind vehicle.

But as you say, the velocity limit should be defined by the road, so just having two velocity limits as I wrote is not a good way.
(I don't think we have to care about this right now though.)

**Comment by TakaHoribe** [comment]
@takayuki5168 
The current policy for the adaptation to the differential drive robot is to consider the robot as a virtual Ackerman vehicle. 

In order to support the differential drive robot officially, we need to replace many parts of planning/control/vehicle modules.

Whereas, the drawbacks of the virtual Ackerman vehicle is handling of the non-essential parameters like steering angle and the lack of the pure angular-velocity rotation. This is not that burden compared to the modification of all Ackerman-specific modules.

So I suggest to have max_steer parameter for all types of vehicles (at least for now).

**Comment by takayuki5168** [comment]
@TakaHoribe 

> In order to support the differential drive robot officially, we need to replace many parts of planning/control/vehicle modules.

Right. I've been thinking about using (this yaml file)[https://github.com/autowarefoundation/autoware.universe/issues/535#issuecomment-1104791848] with the comment "the differential model is not officially supported. xxx have to be fixed.".

But I found this almost meaningless for now. Now I totally agree with your opinion. Thank you so much.
