### ISSUE TITLE
Cannot get Velodyne Lidar UDP packet in docker container ( --host network mode ) by tier4 Velodyne driver

### ISSUE THREAD

**Issue by xczhanjun** [autowarefoundation/autoware.universe#549]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The perception module cannot  get Velodyne UDP packet in docker container ( by --host network mode ) by tier4 Velodyne driver, but the https://github.com/ros-drivers/velodyne/tree/ros2 drive can.

### Expected behavior

The perception module cannot  get Velodyne UDP packet in docker ( b--host network mode ) by tier4 Velodyne driver, but the https://github.com/ros-drivers/velodyne/tree/ros2 driver can.

### Actual behavior

The official https://github.com/ros-drivers/velodyne/tree/ros2 driver can work.

### Steps to reproduce

just run ros2 launch velodyne_dirvers  16C.xml in latest -amd64-prebuilt(20220315) docker  container.

**Comment by kenji-miyake** [comment]
Please write more clear steps to reproduce. For example, what (all and exact) commands you executed, what data you used, etc.

**Comment by xczhanjun** [comment]
> Please write more clear steps to reproduce. For example, what (all and exact) commands you executed, what data you used, etc.

**Comment by xczhanjun** [comment]
@kenji-miyake hi, today I tested the latest code using docker --net=host mode again, the velodyne_driver can get the udp packet from host network for a while, but it cannot work after a reboot. I will send you a msg when I figured out the root cause.

**Comment by kenji-miyake** [comment]
I understand, thank you for your investigation! :smile:

**Comment by mitsudome-r** [comment]
@xczhanjun 
> hi, today I tested the latest code using docker --net=host mode again, the velodyne_driver can get the udp packet from host network for a while, but it cannot work after a reboot. I will send you a msg when I figured out the root cause.

Were you able to find the root cause of the issue?

**Comment by xmfcx** [comment]
@xczhanjun are there any updates on this issue? Are you still having this issue?

**Comment by mitsudome-r** [comment]
Since there are no response, I will close this issue. @xczhanjun Feel free to reopen as necessary.
