### ISSUE TITLE
Implement sensor drivers for ROS 2

### ISSUE THREAD

**Issue by BonoloAWF** [autowarefoundation/autoware.universe#551]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Implement sensor drivers for ROS 2

### Purpose

The Bus ODD is being developed in ROS 2 which requires porting sensor drivers where required

### Possible approaches

Find open source sensor drivers or implement the required drivers

#### ITRI Bus
- [x] List of sensors on the bus 
- [x] List of missing ROS 2 drivers 
- [ ] Development of missing drivers

**Drivers post:** https://github.com/autowarefoundation/autoware.universe/issues/551#issuecomment-1211529554

#### Leo Drive - Isuzu Bus
- [x] List of sensors on the bus 
- [x] List of missing ROS 2 drivers 
- [x] Development of missing drivers

**Drivers post:** https://github.com/autowarefoundation/autoware.universe/issues/551#issuecomment-1190294431

**Comment by mitsudome-r** [comment]
Yang shared https://github.com/Kitware/LidarView, which might help us design a unified sensor driver for different LiDARs

**Comment by TakumiKozaka-T4** [comment]
@BonoloAWF 
Could you remove my name from assignees?
I'm not concerned with this issue.

> [TakumiKozaka-T4](https://github.com/TakumiKozaka-T4) pushed a commit to TakumiKozaka-T4/autoware.universe that referenced this issue [22 hours ago](https://github.com/autowarefoundation/autoware.universe/issues/551#ref-commit-bd4111f)

I didn't push anything. I only updated my forked repository.

**Comment by senagolcuk** [comment]
| Sensor Type | Sensor Model      | Sensor Driver                                          |
|-------------|-------------------|--------------------------------------------------------------|
| Radar       | Delphi ESR        |                                                              |
| Lidar       | Ouster OS1-64     | [OS1-64 ROS2 Driver](https://github.com/ros-drivers/ros2_ouster_drivers/tree/ros2) |
| GNSS-INS    | Trimble BX992-INS |                                                              |
| Camera      | Onsemi AC-AR0231  |                                                              |

**Comment by senagolcuk** [comment]
| Sensor Type | Sensor Model      | Sensor Driver                                          |
|-------------|-------------------|--------------------------------------------------------------|
| Radar       | Delphi ESR        |   Missing                                                           |
| Lidar       | Ouster OS1-64     | [OS1-64 ROS2 Driver](https://github.com/ros-drivers/ros2_ouster_drivers/tree/ros2) |
| GNSS-INS    | Trimble BX992-INS |                     Missing                                             |
| Camera      | Onsemi AC-AR0231  |                  Missing                                                |

**Comment by mitsudome-r** [comment]
@mitsudome-r will check with ITRI about ROS2 drivers for their platform

**Comment by BonoloAWF** [comment]
@hueirutseng what is the status update regarding upgrading ROS 2 drivers for the Bus ODD ITRI platform? Are there any missing drivers?

**Comment by jason914** [comment]
|Sensor Type       | Sensor Model            |Sensor driver          |Status        |                
| ----------------- |------------------------|---------------------|------------|
|Radar                  |Delphi ESR                 |Missing                  |Work in progress|
|Lidar                    |Ouster OS1-64          |[OS1-64-ROS2 driver](https://github.com/ros-drivers/ros2_ouster_drivers/tree/ros2)|Tested OK |
|GNSS-INS            |Trimble BX992-INS    |Missing                  |Work in progess|
|Camera                |Onsemi AC-AR0231 | Private code(Please contact [Neousys](https://www.neousys-tech.com/en/) for source code)|Tested OK|

**Comment by mitsudome-r** [comment]
@jason914 Thanks for posting the table.
Do you have any updates + estimated timeline on Radar and GNSS-INS sensor driver?

**Comment by mikechan0731** [comment]
Sensor Type | Sensor Model | Sensor driver | Status
-- | -- | -- | --
Radar | Delphi ESR | Missing | WIP, Estimated test date is the end of June.
Lidar | Ouster OS1-64 | OS1-64-ROS2 driver | Tested OK
GNSS-INS | Trimble BX992-INS | Missing | WIP, Estimated test date is the end of August.
Camera | Onsemi AC-AR0231 | Private code(Please contact Neousys for source code) | Tested OK

**Comment by mitsudome-r** [comment]
Expected message for GNSS is explained here: https://github.com/autowarefoundation/autoware_msgs/pull/24

**Comment by mitsudome-r** [comment]
Once we have all drivers available, we can merge the information with the list created in the hardware WG and post it in autoware website.

**Comment by xmfcx** [comment]
@senagolcuk could you update here with the sensor drivers used in the ISUZU bus project?

@meliketanrikulu can you share the estimated timeline for the open sourcing of the applanix driver?

**Comment by xmfcx** [comment]
GNSS-INS driver will be published here: https://github.com/autowarefoundation/applanix

**Comment by mitsudome-r** [comment]
@senagolcuk 
Could you tell me why your sensor driver status for lidar is "Work in progress"?
If you have the link to the driver that you are using, could you share it as well?

**Comment by senagolcuk** [comment]
@mitsudome-r 

I'm updating now.

**Comment by meliketanrikulu** [comment]
> Applanix POS LVX GNSS-INS driver will be published here: https://github.com/autowarefoundation/applanix

Added applanix POS LVX GNSS-INS driver.

**Comment by sglee-morai** [comment]
I have a question. Is it planned that [OS1-64-ROS2 driver](https://github.com/ros-drivers/ros2_ouster_drivers/tree/ros2) will be included in the Autoware.Universe like Velodyne drivers are? I see OS1-64 in the comment above, but cannot find a PR regarding that.

**Comment by mitsudome-r** [comment]
@mikechan0731 Could you update [this comment](https://github.com/autowarefoundation/autoware.universe/issues/551#issuecomment-1149385309) to add the link to the drivers that you are using?

**Comment by senagolcuk** [comment]
@meliketanrikulu thanks for Applanix Driver. I'm updating the table for the new driver.

**Comment by jason914** [comment]
|Sensor Type       | Sensor Model            |Sensor Driver Status        |                
| ----------------- |------------------------|-----------|
|Radar                  |Delphi ESR                 |WIP, Estimated completion date is the end of August|
|Lidar                    |Ouster OS1-64          |[ros2-ouster-driver](https://github.com/ros-drivers/ros2_ouster_drivers) |
|GNSS-INS            |Trimble BX992-INS    |WIP, Estimated completion date is the end of August|
|Camera                |Onsemi AC-AR0231 | Private code, Camera manufacturer does not provide code.|

**Comment by xmfcx** [comment]
@senagolcuk could you update the list with the https://github.com/autowarefoundation/lucid_vision_driver driver?

**Comment by senagolcuk** [comment]
@xmfcx I updated it.

**Comment by mitsudome-r** [comment]
Regarding ITRI's comment: https://github.com/autowarefoundation/autoware.universe/issues/551#issuecomment-1211529554
GNSS-INS driver is ready for testing, but the code is private now. They need internal review to find if they can share the code.

**Comment by xmfcx** [comment]
Since we've gathered possible sensor drivers, we can close this issue.

**Comment by xmfcx** [comment]
https://github.com/autowarefoundation/autoware-projects/wiki/Bus-ODD-Project related.
