### ISSUE TITLE
Tensorrt_yolox package does not work correctly

### ISSUE THREAD

**Issue by batuhanbeytekin** [autowarefoundation/autoware.universe#5524]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hello,
I'm trying to change the detection model from Yolo to Yolox.

Only when I ran the tensorrt_yolox package and tested it with my own bag file, I noticed that it did not enter the callback function.

![Selection_006](https://github.com/autowarefoundation/autoware.universe/assets/71197983/58ad66ae-c2ba-48f3-8821-e9dadda7ef44)

I used standard ros2 subscriber instead of image_transport but I did not get any results.

Also, the same problem occurs with the tensorrt_yolox package with the rosbag replay simulator.

### Expected behavior

The callback function should work in the tensorrt_yolox package and its outputs should be seen.

### Actual behavior

The callback function does not work and no output is seen.

### Steps to reproduce

Run autoware with yolox

**Comment by miursh** [comment]
@batuhanbeytekin 
Can you ensure the following:
1. What command do you type to run tensorrt_yolox?
2. Is the ONNX file correctly downloaded? (The current default directory is (Current default directory is `~/autoware_data/tensorrt_yolox`)
3. Which model are you attempting to run?
4. Does the node successfully load the chosen ONNX file? Could you share the terminal output?
5. Was the .engine file built successfully?

**Comment by batuhanbeytekin** [comment]
Hi @miursh,
First of all, thank you for your reply.

1) I'm running the tensorrt_yolox package with the below command:
`ros2 launch tensorrt_yolox yolox.launch.xml`

2) Here is the current location of ONNX files:
![terminal3](https://github.com/autowarefoundation/autoware.universe/assets/71197983/a3a34dcf-07cb-41a7-b199-6fe4faedd888)

3) You can see the running model file:
![terminal4](https://github.com/autowarefoundation/autoware.universe/assets/71197983/e4f5f8dc-ed6b-4f95-8aec-07945dd096e2)

4) I also downloaded the ONNX file manually but I got the same result. Here is the terminal output.
![terminal1](https://github.com/autowarefoundation/autoware.universe/assets/71197983/0a063af4-025b-448d-814c-8d80be1124ee)

![terminal2](https://github.com/autowarefoundation/autoware.universe/assets/71197983/9ec6e9a4-5287-4354-8f86-aa18a5bd20ab)


5) You can see that the .engine file has been created:
![terminal5](https://github.com/autowarefoundation/autoware.universe/assets/71197983/0d0fe156-36be-48de-b723-d1766f1d95e4)

**Comment by miursh** [comment]
@batuhanbeytekin 
Thank you for the information. That looks fine.
In that way, the nodes (`/image_transport_decompressor_node` and `/tensorrt_yolox`) receives input image as `/sensing/camera/camera0/image_rect_color/compressed` (sensor_msgs/msg/CompressedImage) and publishes output rois as `/perception/object_recognition/detection/rois0`  (tier4_perception_msgs/msg/DetectedObjectsWithFeature) and debug image (`/tensorrt_yolox/out/image`)
Could you make sure that the topic name in your rosbag is `/sensing/camera/camera0/image_rect_color/compressed`? (or remapped to this)

**Comment by batuhanbeytekin** [comment]
@miursh 
Following your advice I remapped my image topic to (sensor_msgs/msg/CompressedImage) and it is working correctly. I have also resolved the confusion regarding the `use_decompressor` parameter.

Thank you for the help.

**Comment by vyshakhullas** [comment]
Hello, I am facing the same problem. I remapped the ~/in/image of tensorrt_yolox node first with CompressedImage, then with /sensing/camera/camera0/image_rect_color like in the official launch file, but it always ends up not subscribing to the correct topic. Checked on rqt_image_view and using rqt_graph. Image decompressor works when I send it the CompressedImage topic. It publishes /sensing/camera/camera0/image_rect_color properly. But, the problem lies with /tensorrt_yolox, no matter what I try. Any help would be greatly appreciated. Thank you!

**Comment by vyshakhullas** [comment]
vyshakh@vyshakh-linux:~$ ros2 node info /tensorrt_yolox
/tensorrt_yolox
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /parameter_events: rcl_interfaces/msg/ParameterEvent
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/mask0: sensor_msgs/msg/Image
    /perception/object_recognition/detection/rois0: tier4_perception_msgs/msg/DetectedObjectsWithFeature
    /rosout: rcl_interfaces/msg/Log
    /tensorrt_yolox/out/color_mask: sensor_msgs/msg/Image
    /tensorrt_yolox/out/color_mask/compressed: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/color_mask/compressedDepth: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/color_mask/theora: theora_image_transport/msg/Packet
    /tensorrt_yolox/out/image: sensor_msgs/msg/Image
    /tensorrt_yolox/out/image/compressed: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/image/compressedDepth: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/image/theora: theora_image_transport/msg/Packet
    /tensorrt_yolox/out/mask/compressed: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/mask/compressedDepth: sensor_msgs/msg/CompressedImage
    /tensorrt_yolox/out/mask/theora: theora_image_transport/msg/Packet
  Service Servers:
    /tensorrt_yolox/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /tensorrt_yolox/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /tensorrt_yolox/get_parameters: rcl_interfaces/srv/GetParameters
    /tensorrt_yolox/list_parameters: rcl_interfaces/srv/ListParameters
    /tensorrt_yolox/set_parameters: rcl_interfaces/srv/SetParameters
    /tensorrt_yolox/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:

vyshakh@vyshakh-linux:~$ ros2 node info /image_decompressor 
/image_decompressor
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /sensing/camera/camera0/image_rect_color/compressed: sensor_msgs/msg/CompressedImage
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /rosout: rcl_interfaces/msg/Log
    /sensing/camera/camera0/image_rect_color: sensor_msgs/msg/Image
  Service Servers:
    /image_decompressor/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /image_decompressor/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /image_decompressor/get_parameters: rcl_interfaces/srv/GetParameters
    /image_decompressor/list_parameters: rcl_interfaces/srv/ListParameters
    /image_decompressor/set_parameters: rcl_interfaces/srv/SetParameters
    /image_decompressor/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:
