### ISSUE TITLE
Cannot get the traffic_light_rois and the image raw in rviz2 when executing Autoware+AWSIM simulation

### ISSUE THREAD

**Issue by ZiweiSong96** [autowarefoundation/autoware.universe#5567]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When I start the simulation with AWSIM and Autoware.Universe, the image raw cannot display normally.
So I check the traffic_light detector related topic and find that the node "/perception/traffic_light_recognition/traffic_light/detection/traffic_light_map_based_detector" cannot execute normally. The publisher count of ros2 topic "/perception/traffic_light_recognition/traffic_light/debug/rois" is 0.
And the log shows a warning about this: [perception.traffic_light_recognition.traffic_light.detection.traffic_light_map_based_detector]: cannot get transform from map frame to camera frame.
This bug makes the autonomous simulation cannot recognize the traffic lights.
But my mate executes the same simulation procedure and get the right results.

### Expected behavior

![Screenshot from 2023-11-13 20-17-16](https://github.com/autowarefoundation/autoware.universe/assets/33652840/0f06f189-1c69-46cd-a657-12d6f7b453c3)

### Actual behavior

![Screenshot from 2023-11-13 20-17-40](https://github.com/autowarefoundation/autoware.universe/assets/33652840/5e16a1cb-3892-463c-a26b-084c259ffd81)
![Screenshot from 2023-11-13 20-14-59](https://github.com/autowarefoundation/autoware.universe/assets/33652840/5b52d6b2-28d6-4060-aa3f-f70e47ffa299)
![Screenshot from 2023-11-13 20-10-49](https://github.com/autowarefoundation/autoware.universe/assets/33652840/5172abef-abed-460a-9eb2-2636c0a299d5)

### Steps to reproduce

Clone and Build the Autoware.Universe
Start AWSIM
ros2 launch the AWSIM e2e simulation,

### Versions

Ubuntu 22.04
ROS2 HUMBLE
AWSIM v1.1.0
NVIDIA A4000 GPU
NVIDIA driver version is 545.23.06
cuda r11.6

### Possible causes

I rebuild the workspace and Ubuntu 22.04 system for many times. I think maybe it is the NVIDIA GPU problem. But according to the ROS2 log and ROS2 topic info, it seems the tf2 topic transform problem

**Comment by miursh** [comment]
@ZiweiSong96 
Please verify that the localization module is working correctly and that 'map -> base_link' is being published within the tf.

**Comment by ZiweiSong96** [comment]
> @ZiweiSong96 Please verify that the localization module is working correctly and that 'map -> base_link' is being published within the tf.

Actually the simulation pipeline can be executed normally and the localization module is working correctly, but it cannot recognize traffic light, whicn means the vehicle is driving no matter what color the traffic light is.
Besides, I use tools to check tf2 tree, and the "map"->"base_link" is published.

**Comment by annb3** [comment]
I have the same problem and also the model for pedestrian and car .onnx, requested from the code are are not available yet. 
Have someone solved this issue?

**Comment by amadeuszsz** [comment]
Hi @ZiweiSong96 
Does the issue still occur? Please, make sure you use updated repositories for AWSIM and Autoware. If it doesn't help, please share appropriate data and steps to reproduce your issue. To do this:
* Record necessary input data, basically it is all the output from AWSIM. Do not record output from Autoware stack.
* Run logging simulator from `autoware_launch` and play recorded data.
* Check if issue occurs using recorded data (it should).

We will take a look directly into code to see what is the source of problem.

However, I have some thought about possible causes:
* There is a small chance that TensoRT engine is not built yet, it takes some time for first run (appropriate logs can be seen in console).
* Misalignment between repositories updates. You use new Autoware features, but accidentally forgot to [update artifacts](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/artifacts).

Hint: Remove all built engines in `autoware_data` directory, run stack, check console carefully if any node died and wait until TensorRT will finish engines build.

**Comment by ZiweiSong96** [comment]
> Hi @ZiweiSong96 Does the issue still occur? Please, make sure you use updated repositories for AWSIM and Autoware. If it doesn't help, please share appropriate data and steps to reproduce your issue. To do this:
> 
> * Record necessary input data, basically it is all the output from AWSIM. Do not record output from Autoware stack.
> * Run logging simulator from `autoware_launch` and play recorded data.
> * Check if issue occurs using recorded data (it should).
> 
> We will take a look directly into code to see what is the source of problem.
> 
> However, I have some thought about possible causes:
> 
> * There is a small chance that TensoRT engine is not built yet, it takes some time for first run (appropriate logs can be seen in console).
> * Misalignment between repositories updates. You use new Autoware features, but accidentally forgot to [update artifacts](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/artifacts).
> 
> Hint: Remove all built engines in `autoware_data` directory, run stack, check console carefully if any node died and wait until TensorRT will finish engines build.

Thanks a lot for helping, this problem does not occured when I changed the repository version, besides, it seems the GPU device also causes this question, it performs normally when I change the NVIDIA A4000 to NVIDIA RTX 3080

**Comment by amadeuszsz** [comment]
@ZiweiSong96 
Great to hear you made it work! 

> it performs normally when I change the NVIDIA A4000 to NVIDIA RTX 3080

Please, clarify me that change. Did you:
* Checked that traffic_light_rois doesn't work.
* Changed GPU without touching Autoware repositories.
* Confirmed that traffic_light_rois works correctly.

?

If you changed repositories (pulled again, updated artifacts etc.), it might be reason why traffic_light_rois was fixed.

**Comment by amadeuszsz** [comment]
Closing as solved.
