### ISSUE TITLE
Problems when add NPC to the scenario editor

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#558]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I created 5 different scenarios with the scenario editor. These scenarios were as follows:

1. A single Ego vehicle is placed and a target position is in a different lane. The ego vehicle must change lane.
2. Ego vehicle and an NPC are in different lanes and their target positions are in their own lanes.
3. The Ego vehicle and an NPC are in different lanes, and their target position is in the lane the Ego vehicle is in. NPC must change lane.
4. The Ego vehicle and an NPC are in different lanes, and their target position is in the lane the NPC is in. The Ego vehicle must change lane.
5. The Ego vehicle and an NPC are in same lane, and their target position is in a different lane. Both vehicle must change lane. 

However, not all of these scenarios were successful.

In case 4, reference_trajectory msg cannot be received and autoware shut down.

> [openscenario_interpreter_node-3] [component_container-18] [INFO] [1647943781.308669420] [control.trajectory_follower.lane_departure_checker_node]: waiting for reference_trajectory msg... 

In case 5, the Ego vehicle changed lane but NPC didn't. 

### Expected behavior

In case 4, reference_trajectory msg must be received and because of that the Ego vehicle should be able to change lane. 
IN case 5, NPC, also should change lane.

### Actual behavior

- NPC can not pass into the lane where the Ego vehicle is.
- The Ego vehicle changed lane but NPC couldn't.

### Steps to reproduce

1. I created several scenario in tier4 scenario editor.
2. If I add Ego vehicle and NPC in different lanes, and their destination point is the lane where ego vehicle is in, I can not get reference_trajectory msg, scenario can not be run and autoware shut down.

### Versions

- ROS2
- autoware.universe

**Comment by mitsudome-r** [comment]
This should be fixed now.
