### ISSUE TITLE
Rendering error in Image projection based fusion

### ISSUE THREAD

**Issue by sezan92** [autowarefoundation/autoware.universe#5607]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I was following the Autoware Universe Documentation. I have found this link has a table , but the table has not been rendered properly https://autowarefoundation.github.io/autoware.universe/main/perception/image_projection_based_fusion/

I have checked the raw file , I copied the table to my `VS code` , there the table is correctly rendered.

### Expected behavior

from Markdown tables generator
![Screenshot from 2023-11-16 17-56-32](https://github.com/autowarefoundation/autoware.universe/assets/11025093/1ac70a96-34c4-4b6f-914e-c821da9fd4d4)

### Actual behavior

![Screenshot from 2023-11-16 17-58-20](https://github.com/autowarefoundation/autoware.universe/assets/11025093/e86f8655-bcbd-4919-827e-c93cc70c9d06)

### Steps to reproduce

1. check the link

**Comment by idorobotics** [comment]
@sezan92 thank you for reporting this. Are you able to create a PR in the docs repo for the quick fix?

**Comment by idorobotics** [comment]
@sezan92 thank you for reporting this. Are you able to create a PR in the docs repo for the quick fix?

**Comment by sezan92** [comment]
@idorobotics someone already created a PR in #5625

**Comment by idorobotics** [comment]
Closed, #5625 merged.
