### ISSUE TITLE
Double detection of objects 

### ISSUE THREAD

**Issue by adamkrawczyk** [autowarefoundation/autoware.universe#5613]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When used with `scenario_simulator_v2` there are cases when the object is detected twice (in the published output topic `/perception/object_recognition/objects` there are sometimes double detections. The input topic `/perception/object_recognition/detection/objects` - from the scenario_simulator_v2 does not contain the duplicated detections). 

See attached rosbag. 
[rosbag2_2023_04_11-08_32_18.zip](https://github.com/autowarefoundation/autoware/files/11197346/rosbag2_2023_04_11-08_32_18.zip)

### Expected behavior

One detection of the pedestrian (it is the case in the attached scenario)

### Actual behavior

The pedestrian detection is duplicated

### Steps to reproduce

1. Build autoware from the main branch (in my case it happens at least from the `18d7f6f22a11582aea568566e6bde77d42c1d794` (~360 commits behind) 
2. Run the scenario with the following configuration (launcher could be from the scenario simulator v2 - `scenario_test_runner.launch.py`) : 
  -  architecture_type : awf/universe
  -  vehicle_model : sample_vehicle              
  - sensor_model : sample_sensor_kit

The rest is the default. 

The scenario (remove `.txt` - github limitation): 
[demo-unstructured.yaml.txt](https://github.com/autowarefoundation/autoware/files/11197377/demo-unstructured.yaml.txt)

The map used for testing is the [kashiwanoha map](https://github.com/tier4/scenario_simulator_v2/tree/master/map/kashiwanoha_map), we have used a slightly modified. If there will be some issues with the map I think I can provide it but have to consult before sharing. 

### Versions

- OS: Ubuntu 22.04 amd64
- Ros2: humble
- Autoware: main
- Scenario_simulator_v2: [master](https://github.com/tier4/scenario_simulator_v2)

### Possible causes

I haven't analyzed the autoware but it seems that it is not the issue with the scenario_simulator - the detections are not duplicated

### Additional context

Graphical representation (there are also two descriptions that make the view so unclear) but you can see the two yellow boxes representing the object (pedestrian) 
![image](https://user-images.githubusercontent.com/29305346/231079066-0b11806e-7498-48d2-a67f-588fa5567683.png)

**Comment by technolojin** [comment]
Hi.

Can you let me know the issue is persist until now?
I could not get the scenario file. Maybe it is too old.

**Comment by mebasoglu** [comment]
Hello, I tried to reproduce this issue but I couldn't get the issue with the up-to-date Autoware.

Here is the commit ID of Autoware.Universe which I used: `d5cef0dd4da8a881c20dbf9bf0fb7e351549b836`

To be able to run, I changed the map as the default ones on the scenario file like this:

```yaml
  RoadNetwork:
    LogicFile:
      filepath: $(find-pkg-share kashiwanoha_map)/map/lanelet2_map.osm
    SceneGraphFile:
      filepath: $(find-pkg-share kashiwanoha_map)/map/pointcloud_map.pcd
```

I tried with both architecture types. Here is the command that I used:
```bash
ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe record:=true scenario:=/home/meb/projects/autoware/demo-unstructured.yaml sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle global

ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe/20230906 record:=true scenario:=/home/meb/projects/autoware/demo-unstructured.yaml sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle global
```

**Comment by adamkrawczyk** [comment]
I think this can be closed. For now, I don't even have access to the repository that I was using for this purpose so I can't tell if this still occurs. 
If now you can't confirm the issue I'm glad maybe it was fixed in some patch. 
Best, 
Adam
