### ISSUE TITLE
Collect raw sensor data to test sensor drivers

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#562]
### Description

Collect pcap files or candump files to test drivers.

### Purpose

The Bus ODD is being developed in ROS 2 which requires porting sensor drivers where required and needs test data.

### Definition of done

- [ ] raw data for sensors available for https://github.com/autowarefoundation/autoware.universe/issues/551

**Comment by Sharrrrk** [comment]
@BonoloAWF please assign this task to me.

**Comment by Sharrrrk** [comment]
> https://drive.google.com/file/d/13oypA5UdlW1XIqw6l5C3qf0I4sFaZ1Nz/view?usp=sharing
> 
> > Copyright 2022 AutoCore, Inc.
> > Uploder: @Sharrrrk
> > Record Date: 14th.Apr.2022
> 
> ### Description:
> 
> This folder contains pcap files and rosbag files from Ouster OS1-64 Lidar. The pcap file and rosbag file is recored in the same time with slight difference in duration.
> 
> Senario1: multiple static trucks on road side. -- trucks.pcap -- rosbag2_2022_04_14-trucks
> 
> Senario1: Pedstrain moving around vehicle with static vehicle on road side. -- ped_vehicle.pcap -- rosbag2_2022_04_14-ped_vehicle

Using the driver below:
https://github.com/ros-drivers/ros2_ouster_drivers

**Comment by Sharrrrk** [comment]
Data has been provided
