### ISSUE TITLE
Finalize the field type for pointcloud

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#563]
### Description

The output type of lidars should be clarified.

### Purpose

The message information from the sensor drivers should be available for users to implement their own drivers.
Relate discussion: https://github.com/autowarefoundation/autoware/discussions/2480

### Definition of done

- [x] The details of output message from sensor drivers should be available in documentation

**Comment by mitsudome-r** [comment]
We have discussed on this in the Architecture WG
https://github.com/autowarefoundation/autoware/discussions/364

> Lidar:
We still need to agree on pointfield definition
PointXYZI+LaserChannel+Time
Do we want to remove laser channel after preprocessing is done within sensor module?
We can still allow additional fields if required

@xmfcx will create a PR to design document.

**Comment by xmfcx** [comment]
https://github.com/autowarefoundation/autoware-documentation/pull/180 This is being worked on.
