### ISSUE TITLE
Collect training/test data for object detection for Bus ODD

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#564]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Collect the data to train and test perception pipeline for Autoware.Universe

### Purpose

We have to evaluate if perception pipeline in Autoware.Universe is enough to do a demo for Bus ODD.

### Possible approaches

Collect rosbag of sensors using ITRI's Bus.

### Definition of done

- [x] #680
- [x] collect rosbag of sensor data for lidar

**Comment by Sharrrrk** [comment]
@xmfcx as disscussed in last WG meeting, the data has been collected. Shall I use this issue or you would like to create the subtask "collect rosbag of sensor data for lidar".

**Comment by Sharrrrk** [comment]
LiDAR data has been provided in#562

**Comment by xmfcx** [comment]
@xmfcx close this once the rosbags are uploaded to s3

**Comment by xmfcx** [comment]
https://autowarefoundation.github.io/autoware-documentation/main/datasets/
