### ISSUE TITLE
Dead link in behavior path planning document

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#575]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

![image](https://user-images.githubusercontent.com/8327598/159716225-61d6b8f0-7d0d-4fcc-88b4-053a56d35f44.png)
There are regular errors in PR's CI due to dead links in some documents.

### Expected behavior

None

### Actual behavior

None

### Steps to reproduce

None

**Comment by kenji-miyake** [comment]
I think this is resolved by #580.
@TakaHoribe Could you confirm it and close this issue?

**Comment by mitsudome-r** [comment]
This seems to be fixed now.
