### ISSUE TITLE
Perception packages support CUDA 11.4 and TensorRT 8.2.2

### ISSUE THREAD

**Issue by yukke42** [autowarefoundation/autoware.universe#589]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Perception packages are ported from https://github.com/tier4/AutowareArchitectureProposal.iv and some of them depend on CUDA 11.1 and TensorRT 7.2.1, but https://github.com/autowarefoundation/autoware requires CUDA 11.4 and TensorRT 8.2.2.

Therefore, the packages below should be checked to work.

- [x] traffic_light_ssd_fine_detector
- [x] traffic_light_classifier
- [x] lidar_centerpoint
- [x] tensorrt_yolo
- [x] lidar_apollo_instance_segmentation

### Purpose

The perception packages work on the https://github.com/autowarefoundation/autoware environement.

### Possible approaches

If necessary, refer to https://github.com/tier4/tensorrt_common to switch the TensorRT version.

### Definition of done

The packages are checked to work on both versions.

**Comment by yukke42** [comment]
I confirmed lidar_centerpoint works. https://github.com/autowarefoundation/autoware.universe/issues/643#issuecomment-1090090877

**Comment by wep21** [comment]
apollo
![image](https://user-images.githubusercontent.com/42202095/162098105-657337f1-9e52-414c-be88-100b28ee801c.png)

**Comment by wep21** [comment]
yolo
![image](https://user-images.githubusercontent.com/42202095/162103978-2b717423-c4a5-4444-b49c-9fcb0cd389f6.png)

**Comment by wep21** [comment]
traffic light
![image](https://user-images.githubusercontent.com/42202095/162107329-2e79f2ac-e2ff-4035-b99a-aaa8060d3a76.png)

**Comment by yukke42** [comment]
Thank you! :clap:

**Comment by yukke42** [comment]
We checked for the packages to work, so close this issue.
