### ISSUE TITLE
`tier4_sensing_launch` now depends on `common_sensor_launch`

### ISSUE THREAD

**Issue by h-ohta** [autowarefoundation/autoware.universe#619]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

`tier4_sensing_launch` now depends on `common_sensor_launch`.

https://github.com/autowarefoundation/autoware.universe/blob/95414c5d3ff944016dab9376d82d7fdceeb10e4e/launch/tier4_sensing_launch/package.xml#L12

### Purpose

I think `common_sensor_launch` is not always needed when developping autoware.

### Possible approaches

I propose to delete this. 

### Definition of done

- [ ] `common_sensor_launch` is deleted from package.xml in `tier4_sensing_launch`.

**Comment by h-ohta** [comment]
@kenji-miyake Do you have time?

**Comment by kenji-miyake** [comment]
@h-ohta Hmm? What do you mean? I think we can merge it if you send a PR.

**Comment by h-ohta** [comment]
@kenji-miyake OK. I'll make PR.
