### ISSUE TITLE
Can't generate proper route in some merging pattern

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#6282]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Using the planning simulator with the sample map, I have found a strange pattern in which it is either not possible to create a route or the generated route is impossible:

[cannot_set_goal-2024-02-01_16.15.53.webm](https://github.com/autowarefoundation/autoware.universe/assets/18645627/cdbb5444-1b51-4065-a482-5c7ec9a247e1)

For example:
- from 0:20 to 0:30, a broken route is generated
- from 0:30 to 0:40 then from 0:55 to 1:10, goal pose is rejected

I know looped routes are not supported, but I don't think there is any lanelet loop here. Some route lanelet may physically overlap but it should not be a problem?

### Expected behavior

No problem to generate any of the routes?

### Actual behavior

Autoware refuses some goals.

### Steps to reproduce

planning simulator with sample map.

**Comment by maxime-clem** [comment]
Routing fails because of the `Route Handler`  and its function to remove overlapping lanelets. In this case, the ego lanelet is also removed and it causes the bug.
Since the `Route Handler` is used in many different modules, it is hard to fix this bug without affecting the behavior of other modules.

**Comment by VRichardJP** [comment]
@maxime-clem Ah yes!

I guess the best way to fix that would be to have the route handler send and update partial routes. For example, the first 500m or up to the first overlap (whichever comes first).
