### ISSUE TITLE
Some errors are occurred in the tutorial

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#630]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

There are several error outputs in the tutorial.

#### planning simulation errors (no initial pose and goal)
1. `[component_container_mt-2] [ERROR 1649127322.717185575] [system.system_monitor.hdd_monitor]: Failed to execute findmnt. /dev/sda3 (getDeviceFromMountPoint() at /home/yukky/workspace/awf-autoware/src/universe/autoware/system/system_monitor/src/hdd_monitor/hdd_monitor.cpp:336)`
![image](https://user-images.githubusercontent.com/8327598/161669907-ca4610ed-e3b7-43be-8d80-71c58241ac19.png)

2. `[system_error_monitor-5] [ERROR 1649127352.426385570] [system_error_monitor system_error_monitor/input_data_timeout]: [Single Point Fault]:  (logThrottledNamed() at /home/yukky/workspace/awf-autoware/src/universe/autoware/system/system_error_monitor/src/system_error_monitor_core.cpp:54)`
![image](https://user-images.githubusercontent.com/8327598/161669969-b5a3cef2-747b-4cdb-b94c-929a49422037.png)

#### planning simulation errors (after set initial pose and goal)
![image](https://user-images.githubusercontent.com/8327598/161670107-a3b793b5-d61d-42ad-896a-3c1bb53f7c60.png)
![image](https://user-images.githubusercontent.com/8327598/161671758-26789891-dd2f-4d3c-897b-81dbc8bf335b.png)

#### rosbag play simulation errors (before play rosbag)
1. `[component_container_mt-3] [ERROR 1649077390.399824469] [system.system_monitor.hdd_monitor]: Failed to execute findmnt. /dev/sda3 (getDeviceFromMountPoint() at /home/yukky/workspace/awf-autoware/src/universe/autoware/system/system_monitor/src/hdd_monitor/hdd_monitor.cpp:336)`
![image](https://user-images.githubusercontent.com/8327598/161669425-ef451629-6dc0-414d-b327-ad1c7d209d6c.png)

2. `[system_error_monitor-6] [ERROR 1649077411.984191756] [system_error_monitor system_error_monitor/input_data_timeout]: [Single Point Fault]:  (logThrottledNamed() at /home/yukky/workspace/awf-autoware/src/universe/autoware/system/system_error_monitor/src/system_error_monitor_core.cpp:54)` 
![image](https://user-images.githubusercontent.com/8327598/161669505-d7d013a1-fc5e-4abb-9f7c-d2f033e88366.png)

#### rosbag play simulation errors (after play rosbag)
![image](https://user-images.githubusercontent.com/8327598/161669704-594cec5f-70ce-4076-a461-07bcca0a70e0.png)
![image](https://user-images.githubusercontent.com/8327598/161672078-74131401-1a52-49a4-a1f7-6f8b0d79cdf3.png)

### Expected behavior

There are No error.

### Actual behavior

There are several error outputs in the tutorial.

### Steps to reproduce

Planning simulation
`ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/Downloads/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit`
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/

Rosbag replay simulation
`ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/Downloads/sample-map-rosbag vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit`
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

**Comment by yukkysaito** [comment]
@ito-san Can you investigate the error regarding hdd_monitor?

**Comment by xmfcx** [comment]
Are https://github.com/autowarefoundation/autoware.universe/issues/641 and https://github.com/autowarefoundation/autoware.universe/issues/643 are part of this issue?

**Comment by xmfcx** [comment]
Since the tasks need to be re-done, we'll close the issue and if errors occur again, this issue needs to be re-created.

**Comment by yukkysaito** [comment]
cc @ito-san 
Now, I want to reopen this issue because we get some errors when plannign simulator is launched.
![image](https://user-images.githubusercontent.com/8327598/201011681-061f2df7-feb7-40dd-857f-bfe477d82db8.png)

**Comment by ito-san** [comment]
@yukkysaito Please consider to close this issue if you don't have any problem with it after the fixes.

**Comment by xmfcx** [comment]
@yukkysaito is this issue still present?

**Comment by mitsudome-r** [comment]
I'm closing the issue since there are no updates for long time.
We can reopen this issue or create new one if we find issue with the tutorial.
