### ISSUE TITLE
refactor(mission_planner/lanelet2_plugins): function updateRoute/clearRoute should be public override

### ISSUE THREAD

**Issue by felixf4xu** [autowarefoundation/autoware.universe#6302]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

it's more like a refactor not a bug or even a question to confirm the current design.

In `planning/mission_planner/include/mission_planner/mission_planner_plugin.hpp`, 

`updateRoute()` and `clearRoute()` are declared as **public** virtual:

https://github.com/autowarefoundation/autoware.universe/blob/main/planning/mission_planner/include/mission_planner/mission_planner_plugin.hpp#L44-L45

```cpp
class PlannerPlugin
{
public:
  virtual void updateRoute(const LaneletRoute & route) = 0;
  virtual void clearRoute() = 0;
};
```
but in `planning/mission_planner/src/lanelet2_plugins/default_planner.hpp`, those 2 functions are declared as **private**:
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/mission_planner/src/lanelet2_plugins/default_planner.hpp#L81-L82
```cpp
class DefaultPlanner : public mission_planner::PlannerPlugin
{
public:

private:
  void updateRoute(const PlannerPlugin::LaneletRoute & route);
  void clearRoute();
};
```
I'd like to check if this is intentional or not.

### Expected behavior

derived class should not hide public functions in base class

### Actual behavior

in `DefaultPlanner`, those 2 functions are private, but if we use the base class's reference or pointer to call those 2 functions, they still can be called, which leads to confusion in code design.

### Steps to reproduce

n/a

### Possible causes

make those 2 functions `public override`

**Comment by isamu-takagi** [comment]
@felixf4xu I don't think it was intentional. These functions should be public for mission_planner.
@kosuke55 (https://github.com/autowarefoundation/autoware.universe/pull/3334 reviewer) If there is a special reason, please let me know.
