### ISSUE TITLE
Dead link in emergency_handler

### ISSUE THREAD

**Issue by meliketanrikulu** [autowarefoundation/autoware.universe#635]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

![dead_link](https://user-images.githubusercontent.com/41450930/161759884-f95fdd85-f2b4-4193-a265-b1e061b110bd.png)

There are errors during your PR due to dead links in some documents.

You can see the dead link in the document below:

https://github.com/autowarefoundation/autoware.universe/tree/main/system/emergency_handler#emergency_handler

### Expected behavior

None

### Actual behavior

None

### Steps to reproduce

None

**Comment by angry-crab** [comment]
@kenji-miyake Hi Miyake-san, the dead link is confirmed. I see that you are the maintainer of this package. Is there another link for this image?
