### ISSUE TITLE
The planning simulator does not work as per the tutorial.

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#641]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The planning simulator does not work as per the tutorial.
It seems to the pull over function of the behavior path planner does not publish.
![image](https://user-images.githubusercontent.com/8327598/161913352-3e6b9b24-f74f-415c-a7c2-aa46f68de985.png)
![image](https://user-images.githubusercontent.com/8327598/161913382-ae7c0589-de4a-4022-9e41-5bcb2e41ae82.png)

### Expected behavior

https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/

### Actual behavior

The planning simulator does not work as per the tutorial.

### Steps to reproduce

https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/

**Comment by rej55** [comment]
It seems to be happen because the status of scene modules is not initialized.
https://github.com/autowarefoundation/autoware.universe/blob/7ee98f4768870e0f33688922c68143faa3acd29f/planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp#L202

The initial status should be `BT::NodeStatus::IDLE`.
I'll fix it.

**Comment by yukkysaito** [comment]
@rej55 Thank you!

**Comment by yukkysaito** [comment]
New issues : 
- Poor trajectory follower performance and no parking state.
![image](https://user-images.githubusercontent.com/8327598/162191009-8fcd832c-610c-4300-8ab7-26eeb497383b.png)

- If a goal is set quickly at startup, it cannot move.
![image](https://user-images.githubusercontent.com/8327598/162191207-0ca95f47-61ac-4253-85a2-3f17536fb0d2.png)

**Comment by mitsudome-r** [comment]
@yukkysaito Do we still have issues with the tutorial? I believe they are working with the newest code.

**Comment by xmfcx** [comment]
We'll close this issue and it can be re-opened if it occurs again.
