### ISSUE TITLE
The rosbag replay simulator does not work as per the tutorial.

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#643]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The rosbag replay simulator does not work as per the tutorial.
- centerpoint doesn't work (weight file is downloaded manually)
- apollo instance segmentation doesn't work (weight file is downloaded manually)
- traffic_light_ssd_fine_detector doesn't work. Too many downloads are failing in gdown.

![image](https://user-images.githubusercontent.com/8327598/161924930-9718be60-a34e-471c-83c3-6dfad5cc3874.png)

### Expected behavior

https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

### Actual behavior

The rosbag replay simulator does not work as per the tutorial.
- centerpoint doesn't publish the topic
- traffic_light_ssd_fine_detector doesn't work

### Steps to reproduce

https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

### Versions

```
yukky@yukky:~/workspace/tutorial/autoware$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0
```
```
yukky@yukky:~/workspace/tutorial/autoware$ nvidia-smi
Wed Apr  6 17:04:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:09:00.0  On |                  N/A |
| 33%   48C    P2    53W / 250W |    887MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by wep21** [comment]
Could you check if gdown successfully download the weight files?
```
❯ ls install/traffic_light_ssd_fine_detector/share/traffic_light_ssd_fine_detector/data/
mb2-ssd-lite-tlr.onnx  voc_labels_tl.txt
```
```
❯ ls install/lidar_centerpoint/share/lidar_centerpoint/data/
pts_backbone_neck_head_aip_x2.onnx     pts_backbone_neck_head_default.onnx  pts_voxel_encoder_default.engine
pts_backbone_neck_head_default.engine  pts_voxel_encoder_aip_x2.onnx        pts_voxel_encoder_default.onnx
```

**Comment by yukkysaito** [comment]
@wep21 thank you
yes, too many downloads are failing in gdown.
That was the reason why traffic_light_ssd_fine_detector was not working.
But the centerpoint weights file is downloaded manually. (engine file is created at initial runtime)
```
yukky@yukky:~/workspace/tutorial/autoware$ ls src/universe/autoware/perception/lidar_centerpoint/data/
pts_backbone_neck_head_aip_x2.onnx  pts_backbone_neck_head_default.onnx  pts_voxel_encoder_aip_x2.onnx  pts_voxel_encoder_default.onnx
```

**Comment by yukkysaito** [comment]
I manually down loaded the traffic light and the error disappeared.

**Comment by yukkysaito** [comment]
lidar_apollo_instance_segmentation_node does not work, too :cry:

**Comment by yukke42** [comment]
This error is possibly caused by TensorRT version. https://github.com/autowarefoundation/autoware.universe/issues/589

**Comment by wep21** [comment]
@yukkysaito Could you check the tensorrt version?
```
❯ apt-cache policy libnvinfer-dev
libnvinfer-dev:
  インストールされているバージョン: 8.2.4-1+cuda11.4
  候補:               8.2.4-1+cuda11.4
```

**Comment by yukke42** [comment]
Using docker lidar_centerpoint can be built and run successfully, but the subscribed topic name to it is weird.
![Screenshot from 2022-04-06 18-53-36](https://user-images.githubusercontent.com/24660808/161949513-afacd9f6-33c2-4d67-a348-53918163859e.png)

**Comment by yukke42** [comment]
I launch autoware without perception and launch lidar_centerpoint in other terminal, the detected objects are visualized on rviz.
![Screenshot from 2022-04-06 19-04-30](https://user-images.githubusercontent.com/24660808/161951604-3fb12e18-9452-4de1-b9d8-59ab955939d0.png)

**Comment by yukke42** [comment]
@yukkysaito 

Was this issue solved by [this PR](https://github.com/autowarefoundation/autoware.universe/pull/645#event-6381035116)?

**Comment by yukkysaito** [comment]
@yukke42 Yes! Thank you
