### ISSUE TITLE
behavior_planning_container dies because of guard_condition

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#6452]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

![Screenshot from 2024-02-07 17-22-44](https://github.com/autowarefoundation/autoware.universe/assets/32412808/704de1b3-19a6-4008-91eb-f2330fce36d6)

### Expected behavior

no crash

### Actual behavior

behavior_planning_container  dies

### Steps to reproduce

Give goal position repeatedly

**Comment by beyzanurkaya** [comment]
@takayuki5168 https://github.com/autowarefoundation/autoware.universe/issues/2684 is very similar to that one. do you have any idea what caused this?

**Comment by maxime-clem** [comment]
It could be related to https://github.com/autowarefoundation/autoware/issues/4138
The "steps to reproduce" is similar (set a goal position again).

**Comment by takayuki5168** [comment]
@beyzanurkaya Sorry, I don't have any idea.

**Comment by beyzanurkaya** [comment]
ROS Issue: https://github.com/ros2/rclcpp/issues/2163

**Comment by xiaoc88** [comment]
@maxime-clem @beyzanurkaya @takayuki5168 Hi,I also encountered the same problem. Has this issue been resolved? I found that using the command to publish in a loop easily reproduces this issue.
![image](https://github.com/autowarefoundation/autoware.universe/assets/170789842/3a9993e1-64fa-4e6b-b197-1d3bc3ab3c2b)

Command: ros2 topic pub --rate 1 /planning/mission_planning/goal geometry_msgs/msg/PoseStamped "{
  header: {stamp: {sec: 0, nanosec: 0}, frame_id: 'map'},
  pose: {position: {x: -171.8, y: 78.1, z: -1.27}, orientation: {x: 0.0, y: 0.0, z: 0.62, w: 0.78}}
}"
commit: ab8bbf56ecdacbabae89f56f4bc8b6ea1d7bf0df
![image](https://github.com/autowarefoundation/autoware.universe/assets/170789842/4f809e9a-7fa4-4889-803a-69192060bf57)

-DCMAKE_BUILD_TYPE=Release
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
Ros2: Humble
![image](https://github.com/autowarefoundation/autoware.universe/assets/170789842/490fc5b5-3f77-4de7-aa48-f8f67624937b)

**Comment by beyzanurkaya** [comment]
@xiaoc88 I solved this problem by installing ROS2 from the source. This PR that tier4 opened for this issue solved the problem.

PR: [Fix SharedFuture from async_send_request never becomes valid (#2044) … · tier4/rclcpp@0189b7c](https://github.com/tier4/rclcpp/commit/0189b7c2146e558218b8f0775d8e006cd062787d)

FYI: @mitsudome-r @xmfcx

**Comment by idorobotics** [comment]
>@xiaoc88 I solved this problem by installing ROS2 from the source. This PR that tier4 opened for this issue solved the problem.

PR: [Fix SharedFuture from async_send_request never becomes valid (#2044) … · tier4/rclcpp@0189b7c](https://github.com/tier4/rclcpp/commit/0189b7c2146e558218b8f0775d8e006cd062787d)

FYI: @mitsudome-r @xmfcx 
@beyzanurkaya can this issue be closed?

**Comment by idorobotics** [comment]
> @xiaoc88 I solved this problem by installing ROS2 from the source. This PR that tier4 opened for this issue solved the problem.

@beyzanurkaya can this issue be closed?

**Comment by luojiaxiang11** [comment]
> @maxime-clem @beyzanurkaya @takayuki5168 Hi,I also encountered the same problem. Has this issue been resolved? I found that using the command to publish in a loop easily reproduces this issue. ![image](https://private-user-images.githubusercontent.com/170789842/337314021-3a9993e1-64fa-4e6b-b197-1d3bc3ab3c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjY2MjcsIm5iZiI6MTcxODc2NjMyNywicGF0aCI6Ii8xNzA3ODk4NDIvMzM3MzE0MDIxLTNhOTk5M2UxLTY0ZmEtNGU2Yi1iMTk3LTFkM2JjM2FiM2MyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzA1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmE0NDlkYzZiMzBmZmFiMDBlNzZiYzgyODJhZWQwN2E0MTM4MDA1MGFhNGZjOWFkOWJlNDVmOWY5NWY0ZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zKse7riIiW_k4eJUUiyuVHZHoX3PRDuw7rqBuKRcIk4)
> 
> Command: ros2 topic pub --rate 1 /planning/mission_planning/goal geometry_msgs/msg/PoseStamped "{ header: {stamp: {sec: 0, nanosec: 0}, frame_id: 'map'}, pose: {position: {x: -171.8, y: 78.1, z: -1.27}, orientation: {x: 0.0, y: 0.0, z: 0.62, w: 0.78}} }" commit: ab8bbf56ecdacbabae89f56f4bc8b6ea1d7bf0df ![image](https://private-user-images.githubusercontent.com/170789842/337287074-4f809e9a-7fa4-4889-803a-69192060bf57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjY2MjcsIm5iZiI6MTcxODc2NjMyNywicGF0aCI6Ii8xNzA3ODk4NDIvMzM3Mjg3MDc0LTRmODA5ZTlhLTdmYTQtNDg4OS04MDNhLTY5MTkyMDYwYmY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzA1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDg3Y2VlNWI3ZDY2ODA2MTJhMzgxY2M3YTFiMWU4ZTkzZTBkZTY5NTA3M2IwNDYyYzI1NDdkNjdkY2FkNmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eCxqd3mJuv6RDQeIRbOkrLoQNSRBQ5tXMmV44Y1EME8)
> 
> -DCMAKE_BUILD_TYPE=Release RMW_IMPLEMENTATION=rmw_cyclonedds_cpp Ros2: Humble ![image](https://private-user-images.githubusercontent.com/170789842/337283121-490fc5b5-3f77-4de7-aa48-f8f67624937b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjY2MjcsIm5iZiI6MTcxODc2NjMyNywicGF0aCI6Ii8xNzA3ODk4NDIvMzM3MjgzMTIxLTQ5MGZjNWI1LTNmNzctNGRlNy1hYTQ4LWY4ZjY3NjI0OTM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzA1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTk5Mjg2YjY3MGVjYWJmYjE0ZGM4OWExMGI3ZmU5OWExOWQ5MjVlMDg2YTE4YjU1NTI5N2NlN2E5ZTVhODZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mwExqofctQ308OexCy-VJw-ebTUuHTzGmrXp1471G_g)
 
Hello，have you solved this problem? I have encountered this problem as well, but it only occurs occasionally without a specific trigger scenario. Installing ROS2 from the source does not solve my problem.

**Comment by maxime-clem** [comment]
@luojiaxiang11 are you using the custom `rclcpp` with this commit https://github.com/tier4/rclcpp/commit/0189b7c2146e558218b8f0775d8e006cd062787d ?

**Comment by luojiaxiang11** [comment]
> @luojiaxiang11 are you using the custom `rclcpp` with this commit [tier4/rclcpp@0189b7c](https://github.com/tier4/rclcpp/commit/0189b7c2146e558218b8f0775d8e006cd062787d) ?

Yes,i using it.

**Comment by maxime-clem** [comment]
Please share the log file (found in `~/.ros/log/{DATE-TIME-...}/`) showing the logs when the error happened.
If the error is the same let's reopen the issue.

**Comment by luojiaxiang11** [comment]
@maxime-clem 
Errors are not exactly the same, but behavior_planning_container also died.Error message as shown in the figure.
![image](https://github.com/autowarefoundation/autoware.universe/assets/74884156/a2c937f7-c827-4081-ae47-51708af57b25)
The full log information as
[launch.log](https://github.com/user-attachments/files/15896376/launch.log)

**Comment by maxime-clem** [comment]
Thank you for sharing the log. Unfortunately there is no information that could help identify the issue.
Which Autoware branch are you using ? If possible please open a new issue where you share details about your setup, and if possible a bag recording to try to reproduce the issue.

**Comment by luojiaxiang11** [comment]
> Thank you for sharing the log. Unfortunately there is no information that could help identify the issue. Which Autoware branch are you using ? If possible please open a new issue where you share details about your setup, and if possible a bag recording to try to reproduce the issue.

Thank you for your suggestion ,and my branch is release/v1.0.

**Comment by DavideGiancola** [comment]
hi, I still have the same problem as described. I upgraded to the version in the main today 28/June. Checking the version of ROS installed automatically in the container (with option --devel) the proposed modification in commit [tier4/rclcpp@0189b7c](https://github.com/tier4/rclcpp/commit/0189b7c2146e558218b8f0775d8e006cd062787d) is already present the problem persists. I have additionally observed that in one particular condition it does not occur: if the first goal is a parking space, the second will be successful. On the next goal the problem occurs again.

**Comment by takayuki5168** [comment]
@DavideGiancola cc @kosuke55 @soblin 
If you come across the issue again, please let us know how to reproduce the issue.
