### ISSUE TITLE
docs(traffic_light_visualization): `tier4_perception_msgs` should be `autoware_perception_msgs` in README.md

### ISSUE THREAD

**Issue by felixf4xu** [autowarefoundation/autoware.universe#6459]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

in `autoware.universe/perception/traffic_light_visualization/README.md`, 
```md
| `~/input/tl_state`   | `tier4_perception_msgs::msg::TrafficLightArray` | status of traffic lights |
```
should be 
```md
| `~/input/tl_state`   | `autoware_perception_msgs::msg::TrafficLightArray` | status of traffic lights |
```

### Expected behavior

readme document is aligned with latest code

### Actual behavior

forgot to update readme doc after code change

### Steps to reproduce

```sh
ros2 node info /perception/traffic_light_recognition/traffic_light_map_visualizer
```
```
/perception/traffic_light_recognition/traffic_light_map_visualizer
  Subscribers:
    /map/vector_map: autoware_auto_mapping_msgs/msg/HADMapBin
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/traffic_light_recognition/traffic_signals: autoware_perception_msgs/msg/TrafficSignalArray
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/traffic_light_recognition/traffic_signals/markers: visualization_msgs/msg/MarkerArray
    /rosout: rcl_interfaces/msg/Log
  Service Servers:
    /perception/traffic_light_recognition/traffic_light_map_visualizer/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /perception/traffic_light_recognition/traffic_light_map_visualizer/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /perception/traffic_light_recognition/traffic_light_map_visualizer/get_parameters: rcl_interfaces/srv/GetParameters
    /perception/traffic_light_recognition/traffic_light_map_visualizer/list_parameters: rcl_interfaces/srv/ListParameters
    /perception/traffic_light_recognition/traffic_light_map_visualizer/set_parameters: rcl_interfaces/srv/SetParameters
    /perception/traffic_light_recognition/traffic_light_map_visualizer/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
```

### Versions

v1.0 and the main branch

### Additional context

similar issue: https://github.com/autowarefoundation/autoware.universe/pull/4158

**Comment by meliketanrikulu** [comment]
Hello @felixf4xu . I couldn't see any incompatibility between the code and the README.md
```
| `~/input/tl_state`   | `tier4_perception_msgs::msg::TrafficLightArray` | status of traffic lights |
```
I see that the message type used in the package is also in the same type. : https://github.com/autowarefoundation/autoware.universe/tree/main/perception/traffic_light_visualization .

The topic you are looking at with node info is: ` autoware_perception_msgs/msg/TrafficSignalArray ` . 

Can you check once again? If there is no confusion, we can close this issue.
