### ISSUE TITLE
This program was not compiled for SM 89   : cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by TUMGEKA** [autowarefoundation/autoware.universe#6461]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I just followed the tutorial for building the newest autoware inside docker. I am trying to run autoware universe with AWSIM according to the documentation, but the perception ist not working properly. I dont see bounding boxes. Looking at the Console I can see the following error:  

> [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'lidar_centerpoint' of type 'centerpoint::LidarCenterPointNode' in container 'pointcloud_container': Component constructor threw an exception: This program was not compiled for SM 89  
: cudaErrorInvalidDevice: invalid device ordinal

### Expected behavior

Perception should work and I should see bounding boxes.

### Actual behavior

Lidarcenterpoint throws and error.

### Steps to reproduce

1. ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=<your mapfile location>

### Versions

- ROS2 Humble
- Newest Autoware Universe
- AWSIM 1.2.0
- NVIDIA RTX 4090

**Comment by mitsudome-r** [comment]
I will test this with the latest docker and see if I can reproduce the error.

**Comment by xmfcx** [comment]
@Aysenayilmaz could you test it on an RTX4080 too?

**Comment by TUMGEKA** [comment]
I fixed the Issue by updating my nvidia driver from 525 to 545.

**Comment by gaoyelu1996** [comment]
Hello, may I ask if the problem has been resolved? I am currently facing the same problem as you.

**Comment by TUMGEKA** [comment]
> Hello, may I ask if the problem has been resolved? I am currently facing the same problem as you.

which nvidia driver are you using?

**Comment by gaoyelu1996** [comment]
> > Hello, may I ask if the problem has been resolved? I am currently facing the same problem as you.
> 
> which nvidia driver are you using?

hello, nvidia drinver 535

**Comment by gaoyelu1996** [comment]
> > Hello, may I ask if the problem has been resolved? I am currently facing the same problem as you.
> 
> which nvidia driver are you using?

Hello, my computer configuration is as follows:
Ubuntu20.04, 4060Ti, nvidia driver 535
I can't find the NVIDIA driver 545 version on my computer. Do you have any good methods to update the NVIDIA driver from 535 to 545?

**Comment by xmfcx** [comment]
Autoware requires Ubuntu 22.04 to function.

If you use Ubuntu 20.04, maybe the `galactic` branch might work for you but I don't know.

**Comment by gaoyelu1996** [comment]
> Autoware requires Ubuntu 22.04 to function.
> 
> If you use Ubuntu 20.04, maybe the `galactic` branch might work for you but I don't know.

Hello, thank you very much for your suggestion, but I installed it through Docker. I modified the nvidia driver from 535 to 545 and the error was resolved.

**Comment by matthew-rococo** [comment]
> > > Hello, may I ask if the problem has been resolved? I am currently facing the same problem as you.
> > 
> > 
> > which nvidia driver are you using?
> 
> Hello, my computer configuration is as follows: Ubuntu20.04, 4060Ti, nvidia driver 535 I can't find the NVIDIA driver 545 version on my computer. Do you have any good methods to update the NVIDIA driver from 535 to 545?

1. Update your system:
```
sudo apt update
sudo apt upgrade

```
2.  Add the NVIDIA PPA
```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt update
```
3. Install the NVIDIA driver
```
sudo apt install nvidia-driver-545

```

4. Reboot you system to apply the changes
```
sudo reboot
```
