### ISSUE TITLE
Add a new tool to measure end-to-end delay of the Autoware for sudden obstacles

### ISSUE THREAD

**Issue by brkay54** [autowarefoundation/autoware.universe#6547]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

In Autoware, accurately detecting the first response to sudden obstacles in various topics is challenging. There's a need for a tool that can create a test environment, listen to critical topics, and measure the system's reaction across different pipelines including Sensing, Perception, Planning, and Control.

**This is a follow-up from:**
- https://github.com/autowarefoundation/autoware.universe/issues/5540

### Purpose

The purpose of this tool is to enhance the reliability and responsiveness of Autoware by providing a means to measure and analyze the delay in reacting to sudden obstacles. This will help in optimizing the system's performance across all stages of its pipeline, ensuring safer autonomous driving capabilities.

### Possible approaches

1. Develop a simulation environment within Autoware that can dynamically spawn obstacles.
2. Implement a listener module that subscribes to key topics (the topics such messages have been publishing: PredictedObjects, DetectedObjects, TrackedObjects, PointCloud2, Trajectory, AckermannControlCommand) to monitor and log reactions.
3. Design a measurement tool that calculates the time delay from obstacle-spawned time to the generation of a control command.
4. Incorporate a reporting mechanism to visualize and analyze the reaction times across different modules.

### Definition of done

- [x] A simulation environment capable of spawning sudden obstacles is implemented.
- [x] A module for subscribing and listening to the necessary topics is developed.
- [x] The tool can accurately measure reaction times across Sensing, Perception, Planning, and Control pipelines.
- [ ] A comprehensive report detailing the reaction times and suggesting areas for optimization is produced.
- [x] Merge the PRs that solve the issue: https://github.com/autowarefoundation/autoware.universe/issues/6255
    - [x] https://github.com/autowarefoundation/autoware/pull/4212
    - [x] https://github.com/autowarefoundation/autoware_internal_msgs/pull/1
    - [x] https://github.com/autowarefoundation/autoware.universe/pull/6440
    - [x] https://github.com/autowarefoundation/autoware.universe/pull/6490
- [ ] Merge the PRs to close this issue.
    - [x] https://github.com/autowarefoundation/autoware_launch/pull/886
    - [x] https://github.com/autowarefoundation/autoware.universe/pull/6382
    - [ ] https://github.com/autowarefoundation/autoware.universe/pull/5954

**Comment by doganulus** [comment]
> create a test environment, listen to critical topics, and measure the system's reaction

It would be nice to write down these topics of interest, valid test conditions, and acceptable/unacceptable values from such measurements. For example,

- If the value in `/namespace/topic_name` is greater than `0`, then `/namespace/another_topic_name` will be greater than `5` within `10` milliseconds. 
- Given `/namespace/topic_name` equals to `ENUM_VALUE` and  `/namespace/another_topic_name` is greater than `20`, then `/namespace/topic3` is always `true`.

What could be other things/constructs you find useful in writing such sentences for such analysis?

**Comment by doganulus** [comment]
Thank you @brkay54. I will wait for your report. Looks very useful.

**Comment by brkay54** [comment]
I created the following document by using the reaction_analyzer before. 
The tests marked by yellow color indicate more delay caused by this [issue](https://github.com/autowarefoundation/autoware.universe/issues/6575).

- Document: [GoogleDocs](https://docs.google.com/spreadsheets/d/1vPWfAfba6vsPu4sFLXpypNAc3NqCepM11d6rKnp2u4Y/edit#gid=0)
