### ISSUE TITLE
The gpu_monitor publishes errors in diagnostics with "No message was set".

### ISSUE THREAD

**Issue by ito-san** [autowarefoundation/autoware.universe#6787]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

On the latest version of Autoware, we are experiencing the following errors when running planning_simulator with system_monitor enabled.

- The gpu_monitor publishes errors in diagnostics wtih "No message was set".
  
![image](https://github.com/autowarefoundation/autoware.universe/assets/57388357/390a6d21-9f0c-45fd-b0a7-38b725cfbe82)

### Root cause

The recent updates to NVIDIA-related libraries seem to have changed the location of `nvml.h`.<br>
The `nvml.h` is located under `/usr/include/hwloc`. Since `FindNVML.cmake` only searches in `/usr/local/cuda/include`, the cmake is unable to find the header and thus the build is performed without NVML.

https://github.com/autowarefoundation/autoware.universe/blob/06bb9bdab6398c717f5e5b234c0f35ad268e80c8/system/system_monitor/cmake/FindNVML.cmake#L23

### Expected behavior

The gpu_monitor publishes not errors in diagnostics.

### Actual behavior

The gpu_monitor publishes errors in diagnostics wtih "No message was set".

### Steps to reproduce

1. Build the latest version of Autoware.
    See [Autoware Documentation / Planning simulation / Installation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/scenario-simulation/planning-simulation/installation/).

2. Run planning_simulator with system_monitor enabled.
    ```console
    source ~/autoware/install/setup.bash
    ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit launch_system_monitor:=true
    ```

3. Run rqt_runtime_monitor.
    ```console
    ros2 run rqt_runtime_monitor rqt_runtime_monitor
    ```

**Comment by ito-san** [comment]
`/usr/include/hwloc/nvml.h` is provided by Portable Hardware Locality project, not NVIDIA.
It seems that there is an issue with the setup.

**Comment by ito-san** [comment]
Resolved the issue by installing the `libnvidia-ml-dev` package, which generated the `nvml.h` file under `/usr/include`.
```console
❯ find /usr -type f -name nvml.h
/usr/include/hwloc/nvml.h
/usr/include/nvml.h
```
![image](https://github.com/autowarefoundation/autoware.universe/assets/57388357/8aae7aa0-0efa-4392-9492-9f45f27f696b)

**Comment by ito-san** [comment]
```console
❯ dpkg -S /usr/local/cuda-12.3/targets/x86_64-linux/include/nvml.h
cuda-nvml-dev-12-3: /usr/local/cuda-12.3/targets/x86_64-linux/include/nvml.h
```
cuda-nvml-dev-{{ cuda__dash_case_cuda_version.stdout }} is better.

**Comment by meliketanrikulu** [comment]
Hello @ito-san . Thanks for your contribution. Your PR looks merged. Can we close this issue?

**Comment by ito-san** [comment]
Thank your for the follow up. I'm closing this issue.
