### ISSUE TITLE
Implement any missing calibration tools

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#679]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description
This is a sub-ticket of https://github.com/autowarefoundation/autoware.universe/issues/592 
Implement any missing calibration tools for sensors.

### Purpose

Create calibration tool so that users can generate calibration parameters for sensors.
This includes: 
 - Intrinsic parameter for cameras
 - extrinsic parameter between cameras (camera-camera calibration)
 - extrinsic parameter between lidars (lidar-lidar calibration)
 - extrinsic parameter between a camera and a lidar (camera-lidar calibration)

### Definition of done
- [ ] missing calibration tools specified in https://github.com/autowarefoundation/autoware.universe/issues/677
- [ ] do implementation of the calibraiton tools

**Comment by xmfcx** [comment]
@armaganarsln to provide data for lidar-imu calibration

**Comment by JianKangEgon** [comment]
@xmfcx hi, from Autocore's side, we got one well-worked open sourced tool to calibrate lidar and imu for our SLAM related works, see the link: https://github.com/APRIL-ZJU/lidar_IMU_calib

Currently, the original version supported by developers could only works for velodyne lidar packets. We have overwritten the lidar inputs to receive our ouster lidar as well. If necessary, I'm willing to provide ros bags and modified codes.

**Comment by mitsudome-r** [comment]
@JianKangEgon It would be nice if you can provide the rosbag and share the modified branch here. If the change is generic for all lidars, then you may also create PR to the upstream.

**Comment by JianKangEgon** [comment]
@mitsudome-r  okay sure, I'd love to do that. It takes some days to organize documentation, code and sensor data.

**Comment by JianKangEgon** [comment]
@mitsudome-r  Currently, I've organized one public repo, see link: https://gitlab.com/JianKang_Egon/li_calib/-/tree/main/
You can easily check the README for details and try this tool to know if it satisfies your need. For any question, just feel free to let me know.

**Comment by armaganarsln** [comment]
> @armaganarsln to provide data for lidar-imu calibration

@meliketanrikulu could you please provide the rosbag file of Applanix + Velodyne Puck?

**Comment by meliketanrikulu** [comment]
@armaganarsln Applanix + Velodyne Puck Data:
https://drive.google.com/drive/folders/1b4hSw8oaMPje2DFNC1TUFukDl2NuduVz?usp=sharing

**Comment by mitsudome-r** [comment]
Thanks @JianKangEgon for the information.
Maybe we can start creating documentation page to list up potential calibration tools that developers might want to use.

**Comment by JianKangEgon** [comment]
@mitsudome-r yeah sure. And now my colleagues and I are parallel working on other calibration tools. Once the documentation page is created, you can assign to shark or me to fulfill it.

**Comment by mitsudome-r** [comment]
@JianKangEgon 
Could you start creating PR to update [this page](https://github.com/autowarefoundation/autoware-documentation/blob/main/docs/tutorials/advanced/sensor-calibration.md)?

**Comment by mitsudome-r** [comment]
Autocore merrged a guide for lidar-IMU calibration.
They will proceed to add a guide for lidar-camera and lidar-lidar calibration as well.

**Comment by JianKangEgon** [comment]
@mitsudome-r @armaganarsln yeah sure, for any question, just feel free to let me know

**Comment by xmfcx** [comment]
Let's create an issue to add it to autoware documentation page.
