### ISSUE TITLE
LOAM Mapping Task 3 - Integrate featureExtraction from LIO-SAM

### ISSUE THREAD

**Issue by ataparlar** [autowarefoundation/autoware.universe#6838]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

This task is the subtask of Point cloud feature extraction for LOAM based localization.
- https://github.com/autowarefoundation/autoware.universe/issues/6741
<hr>

For using them in the LOAM Based Localization, we need to export point cloud feature maps separately. Related issue:
- https://github.com/autowarefoundation/autoware/issues/4592

To implement feature extraction from a projected point cloud, the below task needs to be done:
- https://github.com/autowarefoundation/autoware.universe/issues/6837

### Purpose

Extracting the features (planar, edge...) from the generated point clouds.

### Possible approaches

- Use instantaneous point clouds for detecting the features.
- Use the full point cloud map for detecting the features.

### Definition of done

- [ ] Undistort point clouds.
- [x] Visualize the extracting process of the features in RViz as point clouds.
- [x] Export the point cloud feature maps to `pcd` files.

**Comment by ataparlar** [comment]
The tool can export corner feature point cloud map and surface feature point cloud map. Before exporting, it is visualizing both in the rviz. Right now, point cloud undistortion is not implemented. We wanted to see we can see the feature point clouds.

## RViz Visualization: 
### Corner Cloud
![Screenshot from 2024-04-26 17-37-20](https://github.com/autowarefoundation/autoware.universe/assets/44242212/36b482f4-9bce-4c6c-b252-622b5563eee5)

### Surface Cloud
![Screenshot from 2024-04-26 17-38-20](https://github.com/autowarefoundation/autoware.universe/assets/44242212/a4f9d5f3-a2e6-4275-a775-9c7292eae87e)


## Exported .pcd:
### Corner Cloud
![Screenshot from 2024-04-26 17-44-46](https://github.com/autowarefoundation/autoware.universe/assets/44242212/def4d4fc-9c77-4dd1-a7af-8317985f21ae)

### Surface Cloud
![Screenshot from 2024-04-26 17-45-00](https://github.com/autowarefoundation/autoware.universe/assets/44242212/e8b8fd6f-9f0a-47fe-8eca-fa33b8d0f843)

**Comment by meliketanrikulu** [comment]
Thanks for your effort @ataparlar . Could you share .pcd files too to examine

**Comment by ataparlar** [comment]
I noticed that the projected image is not correct for some reason. The edge points are not extracted from the corners. They seems like just picking some random points from the point cloud. 

I debugged the projected point cloud's point angles with HSV color space for [loam_mapper](https://github.com/ataparlar/loam-mapper/tree/imu-deskew), original [LIO-SAM](https://github.com/TixiaoShan/LIO-SAM/tree/ros2) and [Velodyne VLP16 ROS2 driver](https://github.com/ros-drivers/velodyne/tree/humble-devel). The videos of them can found below:

Velodyne VLP16 ROS2 driver video:
https://youtu.be/NdwLPB2fWHc

Original LIO-SAM video:
https://youtu.be/sQA-Ilz-8BY

loam_mapper video:
https://youtu.be/tULkP0HXCQs

According to the comparison between those videos, in loam_mapper, the pixels that must be empty are very noisy. I am trying to solve that right now.

**Comment by ataparlar** [comment]
The image_projection seems good right now. But the same error still exist. I am observing the `cloudInfo` message which is crucial for feature extraction. It keeps the point cloumn info, point range info, point start ring index and point end ring index for each point for each cloud. This thing is most probably filled wrong in the program. I am working on it. Here is the video of the last situation:
- https://youtu.be/9cJQO9Oyed4
The turquois points are the edge feature points extracted. They are so wrong obviously. I will keep here posted.

**Comment by ataparlar** [comment]
Hey everyone. I solved the problem and I added point deskewing for feature extraction. Here is the demonstration video and an image of it:
- https://youtu.be/MbFCKkah0y4

![loam_mapper_edge_and_surface_features](https://github.com/autowarefoundation/autoware.universe/assets/44242212/d7062df7-a8f2-4216-926b-9f41cb8b4da3)

I made the changes in `imu_deskew` branch and merged this branch into the master after it is done.

This subtask is done with the commit: 
- https://github.com/ataparlar/loam-mapper/tree/ec3697dcf67b0d4db0c21e648646685cf88df0f9
