### ISSUE TITLE
refactor global_parameter_loader

### ISSUE THREAD

**Issue by h-ohta** [autowarefoundation/autoware.universe#6874]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

The [global_parameter_loader](https://github.com/autowarefoundation/autoware.universe/tree/main/common/global_parameter_loader) created some years ago to set common ROS parameters to each node, but now only set two parameters, use_sim_time and vehicle_info.

### Purpose

To refactor global_parameter_loader, we discuss how it should be.

### Possible approaches

For example, we simply delete this package and set parameters directly in autoware.launch.xml

### Definition of done

make the conclusion to refactor global_parameter_loader.

**Comment by xmfcx** [comment]
- https://github.com/autowarefoundation/autoware.universe/pull/6872

Is merged, closing the issue.
