### ISSUE TITLE
Traffic Light Indicator Weird Behavior

### ISSUE THREAD

**Issue by KhalilSelyan** [autowarefoundation/autoware.universe#6880]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Traffic Light Indicator in the Rviz2 Overlay, flickers between indicators (green/red/yellow) because of sensor messages received ? planning seems to be doing the correct thing and following the indicator it should but not the indicator in the UI 

#### Video

[![Watch the video](https://img.youtube.com/vi/48V0BFjd73Y/maxresdefault.jpg)](https://youtu.be/48V0BFjd73Y)

### Expected behavior

No flickering, just stable light indicator according to which one the planning is following

### Actual behavior

Signals received alternate between colors depending on which signal is first on the array of signals received in the message from the topic being subscribed to

### Steps to reproduce

1. Launch Autoware and AWSIM
2. Drive by a few traffic lights

### Versions

- OS : Ubuntu 22.04
- ROS: Humble

### Possible causes

The way the UI Indicator subscribes/displays the data is not the same as how the planning is being handled most likely

### Additional context
- The code related to the drawing of the traffic display in the overlay
https://github.com/autowarefoundation/autoware.universe/blob/f297d068a0c8bf265d2dee16a0638b13f82d3f8f/common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/traffic_display.cpp#L73-L96

**Comment by KhalilSelyan** [comment]
Ping: @xmfcx @miura @takayuki5168

**Comment by maxime-clem** [comment]
I think we need to do the following:
- use the `traffic_signal_id` in the `TrafficSignal` messages to get the corresponding traffic lights in the map.
- calculate the traffic light longitudinal positions on the ego path.
- select the traffic light with the smallest longitudinal position (but ahead of the ego position).

Doing this requires adding many dependencies and topics to the rviz panel. If that's okay then I can implement it.

**Comment by xmfcx** [comment]
@maxime-clem what about publishing this from where the planning code already does this as a debug message?

**Comment by maxime-clem** [comment]
> @maxime-clem what about publishing this from where the planning code already does this as a debug message?

It may be better yes. I will try that first.

**Comment by maxime-clem** [comment]
@KhalilSelyan I opened a PR with the change: https://github.com/autowarefoundation/autoware.universe/pull/6899
I cannot easily test it at the moment so please confirm if it fixes the chattering issue.
