### ISSUE TITLE
Update RVIZ2 Overlay

### ISSUE THREAD

**Issue by KhalilSelyan** [autowarefoundation/autoware.universe#6882]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Updating the current rviz2 autoware overlay to look better and more sleek.

![image](https://github.com/autowarefoundation/autoware.universe/assets/36904941/2d61d0eb-f323-4b6a-ae1f-374fa691a394)

### Purpose

Updating the current rviz2 autoware overlay to look better and more sleek.

### Possible approaches

Using one island view with a single row instead of 2 separate island views with 2 rows

### Definition of done

- [x] Overlay is centered
- [x] All items in overlay are aligned

**Comment by xmfcx** [comment]
Closed with the PRs merged.

**Test video with AWSIM Labs 1.0.0:** https://www.youtube.com/watch?v=GPow8YPgi1s
