### ISSUE TITLE
radar_tracks_noise_filter 'param_path' not exists

### ISSUE THREAD

**Issue by mhmdrz-mirdamadi** [autowarefoundation/autoware.universe#7132]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The default value of `param_path` specified in the launch file of `radar_tracks_noise_filter`, does not exist.

### Expected behavior

To be run successfully

### Actual behavior

```
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: ~/autoware/install/radar_tracks_noise_filter/share/radar_tracks_noise_filter/config/object_velocity_splitter.param.yaml
[INFO] [radar_tracks_noise_filter_node-1]: process started with pid [27614]
[radar_tracks_noise_filter_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::UninitializedStaticallyTypedParameterException'
[radar_tracks_noise_filter_node-1]   what():  Statically typed parameter 'velocity_y_threshold' must be initialized.
[ERROR] [radar_tracks_noise_filter_node-1]: process has died [pid 27614, exit code -6, cmd '~/autoware/install/radar_tracks_noise_filter/lib/radar_tracks_noise_filter/radar_tracks_noise_filter_node --ros-args -r __node:=radar_tracks_noise_filter -r ~/input/tracks:=~/input/tracks -r ~/output/noise_tracks:=~/output/noise_tracks -r ~/output/filtered_tracks:=~/output/filtered_tracks'].
```

### Steps to reproduce

1. Build autoware
2. ```cd install/radar_tracks_noise_filter/share/radar_tracks_noise_filter/launch```
3. ```ros2 launch radar_tracks_noise_filter radar_tracks_noise_filter.launch.xml```

### Possible causes

The argument `param_path` which is specified in the launch file is:
```<arg name="param_path" default="$(find-pkg-share radar_tracks_noise_filter)/config/object_velocity_splitter.param.yaml"/>```

This line should be changed to:
```<arg name="param_path" default="$(find-pkg-share radar_tracks_noise_filter)/config/radar_tracks_noise_filter.param.yaml"/>```

**Comment by YoshiRi** [comment]
@mhmdrz-mirdamadi 
Thanks for your report. I could reproduce this error and confirmed your solution works.
Would you mind to open PR and link this issue to this?
