### ISSUE TITLE
Ambiguous `nullptr_t` in `common/autoware_auto_common`

### ISSUE THREAD

**Issue by veqcc** [autowarefoundation/autoware.universe#7205]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The clang-tidy warns the following in https://github.com/autowarefoundation/autoware.universe/blame/main/common/autoware_auto_common/include/autoware_auto_common/helper_functions/message_adapters.hpp 
```
unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
```

If there is any reason why you use `nullptr_t`, not `std::nullptr_t`, please explain it and avoid clang-tidy warnings!!

### Expected behavior

use `std::nullptr_t`

### Actual behavior

currently using `nullptr_t`

### Steps to reproduce

run clang-tidy

**Comment by shmpwk** [comment]
@veqcc 
Thank you for your check. I agree to use `std::nullptr_t` insted of `nullptr_t`.

**Comment by veqcc** [comment]
@shmpwk 
Do you create a PR by yourself? or, may I?

**Comment by shmpwk** [comment]
OK I will!
