### ISSUE TITLE
Split autoware_auto_msgs_adapter package as separate repository

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#7219]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

I think we should move autoware_auto_msgs_adapter as external repository.

### Purpose

When we do the migration in Autoware.Universe repository, we would like to remove autoware_auto_msgs repository from depend.repos file to make sure that we can make sure with CI that new PRs would not introduce dependency to autoware_auto_msgs. 

However, due to the nature of this package, we cannot remove dependency on autoware_auto_msgs from autoware_auto_msgs_adapter package so we should separate this as a separate repository.

### Possible approaches

Remove this package and add to autoware.repos file during migration period.

### Definition of done

- [x] Create new autoware_auto_msgs_adapter repository (https://github.com/autowarefoundation/autoware_auto_msgs_adapter)
- [x] Remove autoware_auto_msgs_adapter package from Autoware.Universe https://github.com/autowarefoundation/autoware.universe/pull/7220
- [ ] Add autoware_auto_msgs_adapter package to autoware.repos file https://github.com/autowarefoundation/autoware/pull/4802

**Comment by xmfcx** [comment]
Reason:
- https://github.com/autowarefoundation/autoware/pull/4802#issuecomment-2189227557
