### ISSUE TITLE
Error route planning in bidirectional lanes

### ISSUE THREAD

**Issue by NorahXiong** [autowarefoundation/autoware.universe#7272]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

A new bug is detected when fixing #6803. An unexpected route is produced when setting the start and goal in bidirectional lanelets as specified in **Expected behavior** section and **Actual behavior** section.

Set start and goal in the [reference map](https://github.com/user-attachments/files/15573521/overlap11.osm.txt) as below: 
![image](https://github.com/autowarefoundation/autoware.universe/assets/103234047/daa49852-5eac-41d1-8996-77fd57e93179)

Planning behaviors:
[Overlap_Bug_New.webm](https://github.com/autowarefoundation/autoware.universe/assets/103234047/9903e319-2697-408d-a12b-8cc20141b44c)

### Expected behavior

A drivable or no route should be generated rather than an incorrect route.
![image](https://github.com/autowarefoundation/autoware.universe/assets/103234047/059c83c2-e0fb-41a9-a668-8dc89c2b796d)
![image](https://github.com/autowarefoundation/autoware.universe/assets/103234047/666dbd8c-c4be-4210-9429-df0897c6556f)

### Actual behavior

An unexpected route is produced.
![image](https://github.com/autowarefoundation/autoware.universe/assets/103234047/18c564da-1383-491e-af51-172d1a6d979a)

### Steps to reproduce

See **Description** section.

### Versions

- OS: docker
- ROS2: humble
- Autoware: up to 20240530

**Comment by takayuki5168** [comment]
@NorahXiong cc @soblin @kosuke55 
The planning in the bidirectional lanes is not supported for now.

**Comment by NorahXiong** [comment]
> @NorahXiong cc @soblin @kosuke55 The planning in the bidirectional lanes is not supported for now.

@takayuki5168 Then I will close the issue. Any other comments?
