### ISSUE TITLE
`radar_object_tracker` launches even if no radar has been launched

### ISSUE THREAD

**Issue by mhmdrz-mirdamadi** [autowarefoundation/autoware.universe#7463]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When launching the perception, [this line](https://github.com/autowarefoundation/autoware.universe/blob/ab4badbbd00e1687247d1b25a1e3e857ea098fba/launch/tier4_perception_launch/launch/perception.launch.xml#L119C1-L123C5) makes the [radar object tracker](https://github.com/autowarefoundation/autoware.universe/tree/main/perception/radar_object_tracker) to be launched always even if there is no radar to get the [output](https://github.com/autowarefoundation/autoware.universe/tree/main/perception/radar_object_tracker#output) from it.

### Expected behavior

`use_radar_tracking_fusion` should be true if and only if the radar has a role in fusion. To be more precise, the [perception mode](https://github.com/autowarefoundation/autoware.universe/blob/ab4badbbd00e1687247d1b25a1e3e857ea098fba/launch/tier4_perception_launch/launch/perception.launch.xml#L48C1-L49C1) should be `camera_lidar_radar_fusion`, `lidar_radar_fusion` or `radar`.

### Actual behavior

`use_radar_tracking_fusion` will always be true even if no radar has a role in fusion.

### Steps to reproduce

1. Set the [perception mode](https://github.com/autowarefoundation/autoware.universe/blob/ab4badbbd00e1687247d1b25a1e3e857ea098fba/launch/tier4_perception_launch/launch/perception.launch.xml#L48C1-L49C1) to one of the `lidar` or `camera_lidar_fusion`.
2. Launch the perception.
3. List the topics with `ros2 topic list` and you see `/perception/object_recognition/tracking/radar/far_objects` and `/perception/object_recognition/detection/radar/far_objects` which are empty as there is no publisher for the latter.

### Possible causes

Decide to set the `use_radar_tracking_fusion` based on the `perception mode` value.

**Comment by amadeuszsz** [comment]
Seems this [PR](https://github.com/autowarefoundation/autoware.universe/pull/7194), resolved this problem [here](https://github.com/technolojin/autoware.universe/blob/d4596f8bf607f54daba12b30265d499becef9913/launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml#L13).
