### ISSUE TITLE
build-and-test workflow is failing due to CUDA runtime version

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware.universe#7668]
@knzo25 starting from this PR, The CI for `build-and-test` started failing:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9590002364/job/26444678737#step:15:22008
```
8: C++ exception with description "cudaErrorInsufficientDriver (35)@/__w/autoware.universe/autoware.universe/perception/lidar_centerpoint/include/lidar_centerpoint/cuda_utils.hpp#L80: CUDA driver version is insufficient for CUDA runtime version" thrown in the test body.
```

For some reason the [has CI passed](https://github.com/autowarefoundation/autoware.universe/actions/runs/9589903760/job/26444432176) for the `build-and-test-differential` cuda yet it fails the `build-and-test` checks.

_Originally posted by @xmfcx in https://github.com/autowarefoundation/autoware.universe/issues/6989#issuecomment-2186485659_

**Comment by knzo25** [comment]
@xmfcx 
Kind of a nasty one as I run the tests a while ago with no errors. Will look into it asap, but this week I am full of deadlines...

**Comment by knzo25** [comment]
@youtalk 

I tried to reproduce the error using a docker and following the ci/cd commands whenever possible.
However, the tests pass:

```
9: -- run_test.py: invoking following command in '/home/kenzolobos/workspace/autoware/build/lidar_centerpoint':
9:  - /home/kenzolobos/workspace/autoware/build/lidar_centerpoint/test_preprocess_kernel
9: [==========] Running 4 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 4 tests from PreprocessKernelTest
9: [ RUN      ] PreprocessKernelTest.EmptyVoxelTest
9: [       OK ] PreprocessKernelTest.EmptyVoxelTest (45 ms)
9: [ RUN      ] PreprocessKernelTest.BasicTest
9: [       OK ] PreprocessKernelTest.BasicTest (7 ms)
9: [ RUN      ] PreprocessKernelTest.OutOfRangeTest
9: [       OK ] PreprocessKernelTest.OutOfRangeTest (7 ms)
9: [ RUN      ] PreprocessKernelTest.VoxelOverflowTest
9: [       OK ] PreprocessKernelTest.VoxelOverflowTest (7 ms)
9: [----------] 4 tests from PreprocessKernelTest (66 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 4 tests from 1 test suite ran. (66 ms total)
9: [  PASSED  ] 4 tests.

```

**Comment by xmfcx** [comment]
Thanks @knzo25 , this explains why it specifically failed for the self hosted machines. I will try installing the dricer on the host machines and see.

**Comment by xmfcx** [comment]
I've installed CUDA 12.3 to both machines.

Running again:
- `common-runner-x64-01`: https://github.com/autowarefoundation/autoware.universe/actions/runs/9676012953
- `leo-copper`: https://github.com/autowarefoundation/autoware.universe/actions/runs/9675999034

**Comment by xmfcx** [comment]
They both failed with the same error: https://github.com/autowarefoundation/autoware.universe/actions/runs/9675999034/job/26698258077#step:15:22044

:confused: 

Here is the results from host machine (leo-copper):

```console
mfc@copper:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
mfc@copper:~$ nvidia-smi
Wed Jun 26 13:44:42 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        Off |   00000000:01:00.0  On |                  N/A |
| N/A   52C    P8             11W /  125W |     356MiB /   8192MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1086      G   /usr/lib/xorg/Xorg                            237MiB |
|    0   N/A  N/A      1333      G   /usr/bin/gnome-shell                          115MiB |
+-----------------------------------------------------------------------------------------+
```

The host machine has the necessary stuff and I've updated the rest of the machine with `sudo apt update && sudo apt dist-upgrade`. Then restarted them for good measure too.

@knzo25 I don't know what is missing then :(

**Comment by knzo25** [comment]
I have about the same as you :cry: 

```
kenzolobos@desktop:~/workspace/autoware$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
kenzolobos@desktop:~/workspace/autoware$ nvidia-smi
Wed Jun 26 19:59:29 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
```

I was going to recommend a reboot but you already did it. In the past when changing versions, unload and reload the kernel modules worked when nvidia-smi did not work, but this is not the case. Do you have the cuda samples in that machine to check if those run?

**Comment by xmfcx** [comment]
> Do you have the cuda samples in that machine to check if those run?

I followed the regular steps as always while installing from here: https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/cuda#manual-installation

I will install the nvidia-driver-550 and try again. (this is what I have on my daily work pc as well)

**Comment by xmfcx** [comment]
I think I've understood everything now.

[VoxelGeneratorTest.TwoFramesNoTf](https://github.com/autowarefoundation/autoware.universe/actions/runs/9675999034/job/26698258077#step:15:22041) this test is failing.

### What are the changes that caused it?

[In the PR here](https://github.com/autowarefoundation/autoware.universe/pull/6989/files#diff-13242fdbc1ea675fb9ec50231ca14e886455fdaa28a1f2de81d23b6847631139R169-R172)

> ```cpp
>   auto points_d = cuda::make_unique<float[]>(capacity_ * config.point_feature_size_);
>   cudaMemcpy(
>     points_d.get(), points.data(), capacity_ * config.point_feature_size_ * sizeof(float),
>     cudaMemcpyHostToDevice);
> ```

CUDA calls are being made.

I think before these, no serious CUDA calls were being made. Most of them could run on cpu too probably.

### What are the runner specs?

#### GitHub hosted runners

These are CPU only, [here are their specs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

Right now every job except:
- ARM64 workflows
- `build-and-test`
- `build-and-test-daily`

are running on them.

#### Self-hosted runners

And we have 2 machines here:
- `leo-copper`: has GTX1070
- `common-runner-x64-01` [c6a.xlarge](https://aws.amazon.com/ec2/instance-types/c6a/) cpu-only

These run:
- `build-and-test`
- `build-and-test-daily`

⚠️ [nvidia_container_toolkit](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/nvidia_container_toolkit) was not installed on these machines.

### Then how did it pass the b&t-diff in the first place then?

This is the first fishy part from the lidar_centerpoint [PR b&t-diff CI run](https://github.com/autowarefoundation/autoware.universe/actions/runs/9589903760/job/26444432176#step:11:7852):

> `Finished <<< lidar_centerpoint [1min 37s]`

On my high end machine,
> `Finished <<< lidar_centerpoint [4min 45s]`

This is too fast for this package.

And looking at its tests:

[Almost no tests are performed, including `VoxelGeneratorTest.TwoFramesNoTf`](https://github.com/autowarefoundation/autoware.universe/actions/runs/9589903760/job/26444432176#step:13:650)

I didn't investigate deeper on why this didn't run.

### Verdict

I think, until this PR, no serious CUDA code was in the colcon tests before.
Mostly simple stuff that could also be run on the CPU were tested.

For CUDA only tests to run, we need CUDA capable machines with GPUs.

These tests cannot be done on neither GitHub hosted machines nor the AWS cpu-only runner that we have.

I have now installed the [nvidia_container_toolkit](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/nvidia_container_toolkit) on the `leo-copper` machine with GTX1070 and restarted the machine.

Started [the test](https://github.com/autowarefoundation/autoware.universe/actions/runs/9676012953/job/26704233115) again. But it will probably fail because I don't think when GitHub initiates the containers, it passes `--gpus all` flag to the containers.

I will look into it to see how I can do that for that machine.

**Comment by xmfcx** [comment]
> ### Then how did it pass the b&t-diff in the first place then?

Found out the bug in:
- https://github.com/autowarefoundation/autoware.universe/pull/7712#issuecomment-2191900752

Now it fails on build-and-test-differential too.

**Comment by xmfcx** [comment]
The tests are alright because when I've configured leo-copper machine, it passed entire build-and-test successfully.
See:
- https://github.com/autowarefoundation/autoware.universe/pull/7721

But we will have to disable the tests that fail on non-cuda capable machines. Because we don't have the infrastructure ready to handle gpu based testing for every PR etc.

I will open up an issue to track disabled tests that should be re-enabled once CUDA capable machines are back.

**Comment by xmfcx** [comment]
![image](https://github.com/autowarefoundation/autoware.universe/assets/10751153/efa9bb1e-6015-48a1-9826-ff6b024890c3)

With all the CI cache related issues are fixed, CI filter issues solved, GPU requiring tests are disabled and tracked, and most importantly, `build-and-test` now passing, I think we can close this issue.

If you have any questions left, please feel free to ask.

![image](https://github.com/autowarefoundation/autoware.universe/assets/10751153/0b23ec30-e471-4b22-9dc1-ff085e107e80)
