### ISSUE TITLE
Implementing the control of the external request line change module using the buttons

### ISSUE THREAD

**Issue by Andrey949101** [autowarefoundation/autoware.universe#7711]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Hello everyone!
I am trying to implement lane change by pressing the "right" and "left" buttons. It seems to me that the most suitable module for this is the external request line change module. I wrote a plugin for Rviz that sends 1 and 2 depending on the required lane change direction. However, I cannot write the logic inside the module that it would use to handle these external issues.
Could you help me do this or tell me where to find examples and development guides.
Thank you in advance for your help!

### Purpose

Implement lane change by pressing the "right" and "left" buttons.

### Possible approaches

The external request line change planning module accepts an incoming request for a topic and starts rebuilding.

### Definition of done

The vehicle changes lanes when receiving a command from the user.

**Comment by idorobotics** [comment]
Please post your question in the  [Discussions Q&A](https://github.com/orgs/autowarefoundation/discussions/categories/q-a) section.
