### ISSUE TITLE
No detect output from yolox

### ISSUE THREAD

**Issue by beginningfan** [autowarefoundation/autoware.universe#7779]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I try to start the `tensorrt_yolox` node. When I set `preprocess_on_gpu` [here](https://github.com/autowarefoundation/autoware.universe/blob/9fcad6b9eaff02fba4642c8abbeca3003c48f2bc/perception/tensorrt_yolox/config/yolox_s_plus_opt.param.yaml#L36) to `true`,the ouptput in `/perception/object_recognition/detection/rois0` is empty. When I set it to `false`, it works well.

### Expected behavior

When I launch tensorrt_yolox with `preprocess_on_gpu` is `true`,the rois in output is not empty

### Actual behavior

![2024-07-01_18-15](https://github.com/autowarefoundation/autoware.universe/assets/103237402/4507cc56-5fe3-4ec7-b431-fd9bba123c7a)

### Steps to reproduce

use `ros2 launch tensorrt_yolox yolox.launch.xml` to launch this node

### Versions

OS: Ubuntu
ROS2: humble
Autoware: latest

**Comment by liuXinGangChina** [comment]
share the rosbag.

**Comment by beginningfan** [comment]
The bag was uploaded here https://drive.google.com/file/d/1Tp-cUaLl7m0XHDsvItfPMVkY-dWtGg7j/view?usp=drive_link

**Comment by liuXinGangChina** [comment]
Hi mits-san, will you help us by assign someone to take a look at this issue

**Comment by badai-nguyen** [comment]
@beginningfan 

I tested the latest autoware' tensorrt_yolox on two options of `preprocess_on_gpu`, both worked well on my side. Could you check around gpu and tensorrt seting and testing again?

`preprocess_on_gpu=true`:
![Screenshot from 2024-07-04 09-07-34](https://github.com/autowarefoundation/autoware.universe/assets/94814556/cf48855f-1b0d-422e-8d38-51669d51ad1d)


`preprocess_on_gpu=false`:
![Screenshot from 2024-07-04 09-05-15](https://github.com/autowarefoundation/autoware.universe/assets/94814556/5818d687-e3f4-4b07-8ae2-5087c1dead4b)

My environment: 
OS: Ubuntu
ROS2: humble
Autoware: latest

```
autoware@npc2201009-ubuntu22:~/autoware$ dpkg -l | grep TensorRT
hi  libnvinfer-dev                                    8.4.2-1+cuda11.6                                  amd64        TensorRT development libraries and headers
hi  libnvinfer-plugin-dev                             8.4.2-1+cuda11.6                                  amd64        TensorRT plugin libraries
hi  libnvinfer-plugin8                                8.4.2-1+cuda11.6                                  amd64        TensorRT plugin libraries
hi  libnvinfer8                                       8.4.2-1+cuda11.6                                  amd64        TensorRT runtime libraries
hi  libnvonnxparsers-dev                              8.4.2-1+cuda11.6                                  amd64        TensorRT ONNX libraries
hi  libnvonnxparsers8                                 8.4.2-1+cuda11.6                                  amd64        TensorRT ONNX libraries
hi  libnvparsers-dev                                  8.4.2-1+cuda11.6                                  amd64        TensorRT parsers libraries
hi  libnvparsers8                                     8.4.2-1+cuda11.6                                  amd64        TensorRT parsers libraries
ii  ros-humble-tensorrt-cmake-module                  0.0.3-1jammy.20240516.164153                      amd64        Exports a CMake module to find TensorRT.
autoware@npc2201009-ubuntu22:~/autoware$ dpkg -l | grep nvinfer
hi  libnvinfer-dev                                    8.4.2-1+cuda11.6                                  amd64        TensorRT development libraries and headers
hi  libnvinfer-plugin-dev                             8.4.2-1+cuda11.6                                  amd64        TensorRT plugin libraries
hi  libnvinfer-plugin8                                8.4.2-1+cuda11.6                                  amd64        TensorRT plugin libraries
hi  libnvinfer8                                       8.4.2-1+cuda11.6                                  amd64        TensorRT runtime libraries
```

**Comment by beginningfan** [comment]
@badai-nguyen Thanks for your reply. 
I tested it with your environment and it worked well. But I used [this docker image](https://github.com/autowarefoundation/autoware/pkgs/container/autoware/231809736?tag=20240618-devel-cuda-amd64) before, the TRT version is different from yours. It dosen't work.

```
root@Dell:/my_autoware# dpkg -l | grep TensorRT
hi  libnvinfer-dev                                    8.6.1.6-1+cuda12.0                      amd64        TensorRT development libraries
hi  libnvinfer-headers-dev                            8.6.1.6-1+cuda12.0                      amd64        TensorRT development headers
hi  libnvinfer-headers-plugin-dev                     8.6.1.6-1+cuda12.0                      amd64        TensorRT plugin headers
hi  libnvinfer-plugin-dev                             8.6.1.6-1+cuda12.0                      amd64        TensorRT plugin libraries
hi  libnvinfer-plugin8                                8.6.1.6-1+cuda12.0                      amd64        TensorRT plugin libraries
hi  libnvinfer8                                       8.6.1.6-1+cuda12.0                      amd64        TensorRT runtime libraries
hi  libnvonnxparsers-dev                              8.6.1.6-1+cuda12.0                      amd64        TensorRT ONNX libraries
hi  libnvonnxparsers8                                 8.6.1.6-1+cuda12.0                      amd64        TensorRT ONNX libraries
hi  libnvparsers-dev                                  8.6.1.6-1+cuda12.0                      amd64        TensorRT parsers libraries
hi  libnvparsers8                                     8.6.1.6-1+cuda12.0                      amd64        TensorRT parsers libraries
ii  ros-humble-tensorrt-cmake-module                  0.0.3-1jammy.20240516.164153            amd64        Exports a CMake module to find TensorRT.
```

**Comment by badai-nguyen** [comment]
@beginningfan Thank you for your confirmation. 
BTW, is there any error logging when you tested on `8.6.1.6-1+cuda12.0`?

**Comment by beginningfan** [comment]
@badai-nguyen  There is no useful information in the log.
I save all output on screen to this [tenerrt_yolox.log](https://github.com/user-attachments/files/16093649/tenerrt_yolox.log)

**Comment by miursh** [comment]
I use the same version as @beginningfan. Dai's version is a bit outdated; you should update the NVIDIA-related libraries.
```
$  dpkg -l | grep TensorRT
hi  libnvinfer-dev                                              8.6.1.6-1+cuda12.0                            amd64        TensorRT development libraries
ii  libnvinfer-headers-dev                                      8.6.1.6-1+cuda12.0                            amd64        TensorRT development headers
ii  libnvinfer-headers-plugin-dev                               8.6.1.6-1+cuda12.0                            amd64        TensorRT plugin headers
hi  libnvinfer-plugin-dev                                       8.6.1.6-1+cuda12.0                            amd64        TensorRT plugin libraries
hi  libnvinfer-plugin8                                          8.6.1.6-1+cuda12.0                            amd64        TensorRT plugin libraries
hi  libnvinfer8                                                 8.6.1.6-1+cuda12.0                            amd64        TensorRT runtime libraries
hi  libnvonnxparsers-dev                                        8.6.1.6-1+cuda12.0                            amd64        TensorRT ONNX libraries
hi  libnvonnxparsers8                                           8.6.1.6-1+cuda12.0                            amd64        TensorRT ONNX libraries
hi  libnvparsers-dev                                            8.6.1.6-1+cuda12.0                            amd64        TensorRT parsers libraries
hi  libnvparsers8                                               8.6.1.6-1+cuda12.0                            amd64        TensorRT parsers libraries
ii  ros-humble-tensorrt-cmake-module                            0.0.3-1jammy.20230919.195325                  amd64        Exports a CMake module to find TensorRT.
```

As a result, the model (yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx) worked without any issues, as shown in this image below.
![image](https://github.com/autowarefoundation/autoware.universe/assets/37187849/a72a18ac-f3fa-4dff-b582-fca31b3faf97)

I'm not sure what is happening but could you try with [this PR](https://github.com/autowarefoundation/autoware.universe/pull/7800) ?

**Comment by beginningfan** [comment]
@miursh Thanks for your replay.
I used the cmakelists.txt in the PR you mentioned, it still doesn't work. I tried in two different devices and two different docker image([20240618-devel-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware/231809736?tag=20240618-devel-cuda-amd64) and [20240708-devel-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware/240647558?tag=20240708-devel-cuda-amd64)), the results are the same. Where did you compile and run this node? Can you try it in one of these two dockers?

**Comment by miursh** [comment]
@beginningfan 
I'm sorry to hear that you're still encountering issues. I compiled and ran the node on my local machine (Ubuntu22.04), not within a Docker container. 
I wil try running it in the Docker images you mentioned.

**Comment by liuXinGangChina** [comment]
hi miura-san，any feedback for “run yolox node in docker([20240618-devel-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware/231809736?tag=20240618-devel-cuda-amd64) and [20240708-devel-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware/240647558?tag=20240708-devel-cuda-amd64)) ” ？ @miursh

**Comment by miursh** [comment]
@liuXinGangChina 
Sorry for the late response.
I tried with `ghcr.io/autowarefoundation/autoware:20240708-devel-cuda-amd64` but the node died with following error 
```
[ERROR] [tensorrt_yolox_node_exe-2]: process has died [pid 89, exit code 127, cmd '/autoware/install/tensorrt_yolox/lib/tensorrt_yolox/tensorrt_yolox_node_exe --ros-args -r __node:=tensorrt_yolox --params-file /tmp/launch_params_ghjqgbg6 --params-file /tmp/launch_params_t05htsl5 -r ~/in/image:=/sensing/camera/camera0/image_rect_color -r ~/out/objects:=/perception/object_recognition/detection/rois0 -r ~/out/mask:=/perception/object_recognition/detection/mask0'].
```

**Comment by storrrrrrrrm** [comment]
test on code up to this commit:https://github.com/autowarefoundation/autoware.universe/commit/083ed2f96875c10b17f59fc5bd2f151efe69029a , it works fine
![2024-08-28_17-44](https://github.com/user-attachments/assets/3b508d81-f99a-46c0-932e-95bcfa0f7447)

container version:
![2024-08-28_17-45](https://github.com/user-attachments/assets/5edfb67d-8ae4-4aa6-bdab-e0bc7eac5afb)

output:
![2024-08-28_17-42](https://github.com/user-attachments/assets/58b4f0ad-0428-4ecc-9397-fdaa351772b5)
