### ISSUE TITLE
[Dense-Urban-ODD] Improve cruise planner slowing down capabilities to overtaking NPC

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [autowarefoundation/autoware.universe#7877]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Part of:
- #7485

#### Dense Urban ODD Characteristics
- **Low-Speed Driving:** Typical speeds around 15 km/h.
- **Complex Traffic Elements:** Includes dense traffic with various dynamic interactions.
- **Dynamic Agents:** Frequent encounters with moving pedestrians and cyclists.
- **Bidirectional Movement:** Vehicles operate in lanes supporting bidirectional flow.
- **Traffic Rule Non-compliance:** Other road users may exhibit behaviors such as:
  - Driving in the wrong direction.
  - Cutting in unexpectedly from off-road areas.
  - Jaywalking pedestrians.
  - Improper / sudden overtaking by other road users.
  
In the context of Dense Urban ODD, we need to fine-tune the existing parameters of the `obstacle_cruise_planner` or potentially develop new features to improve the slowing down of ego vehicle to overtaking road user maintaining both passengers safety and comfortability.

#### Overtaking npc to ego lane then slowing down with different speeds "UC-NTR-001-0008"
The following image describes the scenario where ... 
- an npc is driving in adjacent lane to ego. 
- then it passes the ego vehicle and overtakes the ego lane. 
- after overtaking, it starts to slow down.
![image](https://github.com/autowarefoundation/autoware.universe/assets/36835765/92a91aa3-ffd8-4de6-a8b3-0613e828cb18)

The purpose of improvement in the following cases is to mitigate any unnecessary declaration (slowing down) value by ego vehicle while keeping the distance with overtaking npc.

##### NPC slowing down from 20 to 15 km/h "**PASSED** :heavy_check_mark: "
https://github.com/user-attachments/assets/917cda44-981e-42f1-9347-f7e694c41fd6

##### NPC slowing down from 20 to 12.5 km/h "**FAILED** :x:"
https://github.com/user-attachments/assets/53c59784-d77e-4438-b367-d6689d1e2109

##### NPC slowing down from 20 to 10 km/h "**FAILED** :x:"
https://github.com/user-attachments/assets/7fc53112-fbc0-48a5-aab8-57528b8b6f7e

For reproducing the issue using scenario simulation, you can use the these [scenario](https://github.com/user-attachments/files/16450289/UC-NTR-001-0008.zip) and [map](https://evaluation.ci.tier4.jp/evaluation/maps/980?project_id=awf) files.

### Possible approaches

The `obstacle_cruise_planner` should be capable of handling the situations mentioned above. 
- The primary goal will be to tune the parameters of the package to achieve the success of above scenarios.
- If tuning the parameters is not enough for having successful scenarios, the  `obstacle_cruise_planner` implementation should be improved.

### Definition of done

- [ ] Create a proposal for changing parameters.
- [ ] If the package is inadequate to handle scenarios, propose improvements.
- [ ] Ensure all scenarios for Dense Urban ODD pass.

**Comment by mitsudome-r** [comment]
This is the full length video of a scenario which doesn't abort when the failure condition is met. https://www.youtube.com/watch?v=c0ql4gGCVvo

**Comment by ahmeddesokyebrahim** [comment]
Closing this issue as completed after merging the relevant [PR](https://github.com/autowarefoundation/autoware_launch/pull/1166).
