### ISSUE TITLE
[Dense-Urban-ODD] Improve cruise planner safe distance when cruising a front npc

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [autowarefoundation/autoware.universe#7922]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Part of:
- #7485

#### Dense Urban ODD Characteristics
- **Low-Speed Driving:** Typical speeds around 15 km/h.
- **Complex Traffic Elements:** Includes dense traffic with various dynamic interactions.
- **Dynamic Agents:** Frequent encounters with moving pedestrians and cyclists.
- **Bidirectional Movement:** Vehicles operate in lanes supporting bidirectional flow.
- **Traffic Rule Non-compliance:** Other road users may exhibit behaviors such as:
  - Driving in the wrong direction.
  - Cutting in unexpectedly from off-road areas.
  - Jaywalking pedestrians.
  - Improper / sudden overtaking by other road users.

In the context of Dense Urban ODD, currently `obstacle_cruise_planner` keeps a very long safe distance between ego and front npc which makes the driving scenario not natural. or potentially develop new features to improve the slowing down of ego vehicle to overtaking road user maintaining both passengers safety and comfortability.

### Purpose

Based on description above, the purpose of this issue is to improve  `obstacle_cruise_planner`  safe distance calculations to have a more near human driving scenarios while cruising a front npc.

#### Cruising front npc "UC-NTR-005-0001"
The following image describes the scenario where ... 
- an npc is driving in in front of ego vehicle
- the npc slows down from 14 km/h to 10 km/h
- ego vehicle is expected to have a safe distance of 2-seconds (follow distance / separation distance) with front npc.

![image](https://github.com/autowarefoundation/autoware.universe/assets/36835765/39643caa-08f5-4a19-be70-0a12517176f5)

The purpose of of this improvement is to mitigate any unnecessary distance (very long distance between ego and npc) that makes the driving scenario not natural / human-like.

##### Npc slowing down from 14 km/h to 10 km/h
https://github.com/user-attachments/assets/9ce9d596-0150-4b66-b766-3658440e8695

For reproducing the issue using scenario simulation, you can use the these [scenario](https://github.com/user-attachments/files/16348835/UC-NTR-005-0001.zip) and [map](https://github.com/user-attachments/files/16348855/LEO-VM-00001.zip) files.
:exclamation: Note :exclamation: 
In this previous scenario, the safe distance is updated to be 12.5 m following the 3-seconds inter-vehicle time-distance distance performance requirements [here](https://docs.google.com/presentation/d/1t8PaJIXKCQ7GElig4dVbbkcjLEphHQ9ARmWCci5IML4/edit#slide=id.gd38c585fc3_0_7)

### Possible approaches

The `obstacle_cruise_planner`  already depends on a function named `calcRSSDistance()` to get the `target_dist_to_obstacle`
This function basically depends on this equation : 
```
d_safe =  v_ego * t_reaction + (v_ego^2) / (2 * a_max) - (v_obstacle^2) / (2 * a_min) + d_margin
```
The `d_margin` is set to 6.0 m which yields to a very long distance in the afortmentioned scenario between ego and front npc.

A possible approach is to provide speration between stop and cruise parameters and reduce the value for cruise paramter used by RSS equation to be just a small constant to avoid zero distance )

### Definition of done

- [ ] Add/separate needed parameters.
- [ ] Reflect needed changes in the code after parameters separation
- [ ] Ensure the target scenario is passing.

**Comment by mitsudome-r** [comment]
@brkay54 Could you provide the reasons behind the safety distance of 2 seconds?
Could you post the link to the reference you used to define this?
