### ISSUE TITLE
The output of the gnss_poser package is not suitable for ekf

### ISSUE THREAD

**Issue by meliketanrikulu** [autowarefoundation/autoware.universe#800]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The gnss_poser package generates the 21., 28., 35. indices of the 4x4 covariance matrix by giving default values. You can see in [these](https://github.com/autowarefoundation/autoware.universe/blob/b03d565c1ea455a23bd85f7cc751d3e508f63bfc/sensing/gnss_poser/src/gnss_poser_core.cpp#L134) lines.   (Because it only receives [nav_sat_fix](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatFix.html) message as input. The nav_sat_fix message contains a 3x3 covariance matrix. So it only contains covariance values for x,y,z. Does not include covariance values for roll pitch yaw)

Therefore, when we want to use the ekf_localizer package with the output of the gnss_poser package, we get incorrect results in the returns. You can see results in this [link](https://www.youtube.com/watch?v=VonYFqhLMW8)

We observed that the results improved when we gave the correct values to the 21st, 28th and 35th values of the covariance matrix in the gnss_poser package.  You can see results in this [link](https://www.youtube.com/watch?v=C7mtFypo97U)

We will need to be able to run the ekf_localizer package with the gnss-ins data. So the gnss_poser package needs to be updated.

### Expected behavior

We observed that the results improved when we gave the correct values to the 21st, 28th and 35th values of the covariance matrix in the gnss_poser package. You can see results in this [link](https://www.youtube.com/watch?v=C7mtFypo97U)

### Actual behavior

When we want to use the ekf_localizer package with the output of the gnss_poser package, we get incorrect results in the returns. You can see results in this [link](https://www.youtube.com/watch?v=VonYFqhLMW8)

### Steps to reproduce

You can observe the results yourself by running the output of gnss_poser and ekf_localizer together.

### Possible causes

The gnss_poser package generates the 21., 28., 35. indices of the 4x4 covariance matrix by giving default values. You can see in [these](https://github.com/autowarefoundation/autoware.universe/blob/b03d565c1ea455a23bd85f7cc751d3e508f63bfc/sensing/gnss_poser/src/gnss_poser_core.cpp#L134) lines.   (Because it only receives [nav_sat_fix](https://docs.ros.org/en/api/sensor_msgs/html/msg/NavSatFix.html) message as input. The nav_sat_fix message contains a 3x3 covariance matrix. So it only contains covariance values for x,y,z. Does not include covariance values for roll pitch yaw)

**Comment by YamatoAndo** [comment]
@meliketanrikulu Thank you for your report!
The default values were set without any verification, so I would like to be able to set them to appropriate values.

How about being able to change the values from a config file?

**Comment by xmfcx** [comment]
https://github.com/orgs/autowarefoundation/discussions/233

**Comment by meliketanrikulu** [comment]
Hello. In autoware_universe, I see that GNSS is not currently used as a localization source in localization design. 

![localization design](https://user-images.githubusercontent.com/13819566/167943612-418696de-2a0c-42fb-bb63-7983362465e5.png)

GNSS seems to be used only for initial_pose estimation. Is it planned to perform positioning by receiving the pose message from NDT and GNSS to ekf_localizer in the future? I think GNSS is an important source of localization. It may be more appropriate to fuse NDT and GNSS poses using EKF. what do you think about this

**Comment by YamatoAndo** [comment]
Yes! I have not gotten around to it yet, but that's what I was thinking!

As for other ways to use GNSS information, someone in my company is considering integrating GNSS information during NDT scan matching optimization calculations.

**Comment by xmfcx** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/1230 has fixed this issue.
