### ISSUE TITLE
[Dense-Urban-ODD] Improve avoidance for parked NPCs

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [autowarefoundation/autoware.universe#8539]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Part of:
- #7485

### Dense Urban ODD Characteristics
- **Low-Speed Driving:** Typical speeds around 15 km/h.
- **Complex Traffic Elements:** Includes dense traffic with various dynamic interactions.
- **Dynamic Agents:** Frequent encounters with moving pedestrians and cyclists.
- **Bidirectional Movement:** Vehicles operate in lanes supporting bidirectional flow.
- **Traffic Rule Non-compliance:** Other road users may exhibit behaviors such as:
  - Driving in the wrong direction.
  - Cutting in unexpectedly from off-road areas.
  - Jaywalking pedestrians.
  - Improper overtaking by drivers.
  - Inaccurate parking
  
In the context of Dense Urban ODD, we need to fine-tune the existing features of the `autoware_behavior_path_static_obstacle_avoidance_module` and potentially develop new features to better avoid parked and low speed NPC in dense urban areas.

#### Parked NPC in the same direction of ego "UC-NTR-002-0001" "1st iteration"
The following image describes the scenario where
 
![image](https://github.com/user-attachments/assets/f36b239f-3b88-47fc-a3e8-f5b9fdc60ca2)

#### Parked NPCs in the same and opposite direction of ego "UC-NTR-002-0002"
![image](https://github.com/user-attachments/assets/2ee879bf-b85b-4b7f-ad56-2aa2b31aaffb)

### Possible approaches

The `autoware_behavior_path_static_obstacle_avoidance_module`  should be capable of handling the situations mentioned above.
- The primary goal will be to tune the parameters of the package to achieve the success of above scenarios.
- If tuning the parameters is not enough for having successful scenarios, the `autoware_behavior_path_static_obstacle_avoidance_module` implementation should be improved.

### Definition of done

- [ ] Create a proposal for changing parameters.
- [ ] If the package is inadequate to handle scenarios, propose improvements.
- [ ] Ensure all scenarios for Dense Urban ODD pass.

**Comment by mitsudome-r** [comment]
This task will be taken care by @beyzanurkaya as @ahmeddesokyebrahim will be working on the cruising front NPC scenarios.
