### ISSUE TITLE
System_monitor build failure on Nvidia Xavier platform

### ISSUE THREAD

**Issue by Sharrrrk** [autowarefoundation/autoware.universe#868]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

system_monitor reported error building on Xavier.

```
--- stderr: system_monitor                                                                                                                                                   
/home/nv/ws/autoware/src/universe/autoware.universe/system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp: In member function ‘virtual void GPUMonitor::checkThrottling(diagnostic_updater::DiagnosticStatusWrapper&)’:
/home/nv/ws/autoware/src/universe/autoware.universe/system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp:130:80: error: unused parameter ‘stat’ [-Werror=unused-parameter]
  130 | void GPUMonitor::checkThrottling(diagnostic_updater::DiagnosticStatusWrapper & stat)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/gpu_monitor_lib.dir/build.make:76: CMakeFiles/gpu_monitor_lib.dir/src/gpu_monitor/tegra_gpu_monitor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:602: CMakeFiles/gpu_monitor_lib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< system_monitor [9min 1s, exited with code 2]
```

### Expected behavior

Build success

### Actual behavior

Build error

### Steps to reproduce

Build

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: main with Docker

### Possible causes

Unused variable

**Comment by kenji-miyake** [comment]
Related? #270 (But seems another problem.)
@ito-san cc @KeisukeShima Could you comment on this? :pray:

**Comment by ito-san** [comment]
> Related? #270 (But seems another problem.) @ito-san cc @KeisukeShima Could you comment on this? pray

@kenji-miyake Yes, checking thermal throttling is not implemented yet, so we are getting unused parameter error.

**Comment by Sharrrrk** [comment]
> 

I think I could add a maybe_unused tag to the variable temporarily.

**Comment by kenji-miyake** [comment]
@Sharrrrk Looks good. :+1: 
But please note that there will be other issues like #270.
