### ISSUE TITLE
Some of the reference articles are written in Japanese

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#88]
Some packages of readme or comment has reference which is written by Japanese.

If it's easily replace by English article then replace it, otherwise leave it alone.

**Comment by kenji-miyake** [comment]
@taikitanaka3 Could you please list the Japanese documents?

**Comment by kenji-miyake** [comment]
@taikitanaka3 Could you update the status?

**Comment by taikitanaka3** [comment]
@kenji-miyake 
This issue is to change Japanese documents to English as much as possible and currently most of documents are written in English so I think I can close this.

**Comment by 08beeqtufail-sudo** [comment]
Hello everyone,
While going through the documentation found at 
[Autoware universe documentation](https://autowarefoundation.github.io/autoware.universe/latest/planning/behavior_velocity_planner/intersection-design/) 
I found out that the images have all the explanation in Japanese. Can someone provide an English version or just a brief explanation of images in English . Thank you for great work.
