### ISSUE TITLE
Interface to human-machine cooperation

### ISSUE THREAD

**Issue by rej55** [autowarefoundation/autoware.universe#891]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Develop an interface to compensate decisions from Autoware.

### Purpose

Operating an autonomous driving system, it often happens that the perception results are unreliable.
This causes a unsafe planning.

However, it is difficult to get perfect perception results.
So, some ways to compensate decisions are needed.

To achieve a safety operation under the uncertain perception, approving for decisions is one of the way.

### Possible approaches

Develop an interface class to cooperation.

There are many situations to need decisions with perception results.
So, it is difficult to develop interfaces individually.

In this task, we aim to achieve the purpose by developing an interface class to cooperation.
After developing, we can integrate individual scenes to request a cooperation for compensate decisions.

### Definition of done

- Develop an interface class to cooperation
- Integrate it to behavior modules

**Comment by takayuki5168** [comment]
@rej55 Are there anything to do for this issue?
