### ISSUE TITLE
Codebuild fails due to lack of resources

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware.universe#9088]
[Also](https://github.com/autowarefoundation/autoware.universe/commits/main/):
![image](https://github.com/user-attachments/assets/a094fbc7-5115-4c5e-873e-c4796a7d1ecc)

https://github.com/autowarefoundation/autoware.universe/actions/runs/11341739442/job/31550579344

@mitsudome-r these are still managing to fail. Let's try to find a solution in the Software WG meeting.

Probably failing because of lack of memory.
These are CodeBuild machines come pre-set for GitHub actions.
I couldn't find a way to assign swap to these machines.

Current options:
- Limit the number of parallel jobs without using taskset?
- Reduce the cpus assigned to taskset?
- Current codebuild cost is about $500 per month, maybe just find another place to simply host about 10 dedicated machines and set up github actions runners on them?
   - Example: https://eco.ovhcloud.com/en/soyoustart/sys-1/
   - Will be cheaper and would provide higher compute capabilities with more configurability. (due to being self hosted)

_Originally posted by @xmfcx in https://github.com/autowarefoundation/autoware.universe/issues/8946#issuecomment-2413949983_

**Comment by xmfcx** [comment]
Related branch by @mitsudome-r 
- https://github.com/autowarefoundation/autoware.universe/commits/increase-swap-size/

**Comment by mitsudome-r** [comment]
The only solution that worked so far was reducing the number of cpu cores used for build:
https://github.com/autowarefoundation/autoware.universe/actions/runs/11345123914

Some other options other that what Fatih mentioned could be: 
- find out a root cause why Autoware build requires so much memory
- build the packages that require a lot of memory separately (if we can find out a way to manipulate build order)

**Comment by xmfcx** [comment]
This was fixed by using less cores while building on codebuild.

We'll go back to public runners since they provide about 10GB more space on 24.04 runners.

- https://github.com/autowarefoundation/autoware.universe/pull/9709
