### ISSUE TITLE
Accel map or brake map does not exist

### ISSUE THREAD

**Issue by iumida** [autowarefoundation/autoware.universe#9137]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I want to use accel_brake_map_calibrator for calibration and ensure that my CSV file location is correct. After running ros2 launch accel_brake_map_calibrator accel_brake_map_calibrator.launch.xml rviz:=true, rviz does not display the map, and an error appears: 'Accel map or brake map does not exist.

I confirm that the map is in
/home/prius428/autoware.prius428/install/autoware_raw_vehicle_cmd_converter/share/autoware_raw_vehicle_cmd_converter/data/default/

### Expected behavior

An Accel map or brake map must exist.

### Actual behavior

[accel_brake_map_calibrator-1] [WARN] [1729581052.907277212] [accel_brake_map_calibrator]: Accel map or brake map does not exist

### Steps to reproduce

1.Start autoware
2.ros2 launch autoware_accel_brake_map_calibrator accel_brake_map_calibrator.launch.xml rviz:=true

### Versions

Ubuntu 22.04
ROS2 Humble

**Comment by maxime-clem** [comment]
These warnings can be ignored. The files will be created once calibration data starts being recorded.
Right now I tested calibration with Carla and I was able to generate the `accel_map.csv` and `brake_map.csv`.
