### ISSUE TITLE
build-and-test is failing 

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#9187]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

build-and-test action is failing in the main branch since [this PR](https://github.com/autowarefoundation/autoware.universe/pull/8747) was merged. I don't know why it passed in the CI from the PR, but the build also fails locally as well.

failing action: https://github.com/autowarefoundation/autoware.universe/actions/runs/11586899175/job/32258240074

### Expected behavior

build-and-test CI passes.

### Actual behavior

build-and-test CI failes

### Steps to reproduce

1. Build autoware locally
2. I get the following error messages:
```
/home/mitsudome-r/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_arbiter/test/test_node.cpp: In function ‘void generateMap(LaneletMapBin&)’:
/home/mitsudome-r/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_arbiter/test/test_node.cpp:53:19: error: ‘lanelet::utils::conversion’ has not been declared
   53 |   lanelet::utils::conversion::toBinMsg(vector_map_ptr, &vector_map_msg);
      |                   ^~~~~~~~~~
gmake[2]: *** [CMakeFiles/autoware_traffic_light_arbiter_test.dir/build.make:76: CMakeFiles/autoware_traffic_light_arbiter_test.dir/test/test_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/autoware_traffic_light_arbiter_test.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
--- stderr: autoware_traffic_light_arbiter
/home/mitsudome-r/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_arbiter/test/test_node.cpp: In function ‘void generateMap(LaneletMapBin&)’:
/home/mitsudome-r/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_arbiter/test/test_node.cpp:53:19: error: ‘lanelet::utils::conversion’ has not been declared
   53 |   lanelet::utils::conversion::toBinMsg(vector_map_ptr, &vector_map_msg);
      |                   ^~~~~~~~~~
gmake[2]: *** [CMakeFiles/autoware_traffic_light_arbiter_test.dir/build.make:76: CMakeFiles/autoware_traffic_light_arbiter_test.dir/test/test_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/autoware_traffic_light_arbiter_test.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< autoware_traffic_light_arbiter [25.5s, exited with code 2]
```

### Versions

- Ubuntu 22.04
- ROS 2 Humble
- Autoware.Universe commit hash: https://github.com/autowarefoundation/autoware.universe/commit/e58a158eb9d993bf4a066b910affa74f51a3f7e5

### Possible causes

Missing include file from autoware_lanelet2_extension

**Comment by go-sakayori** [comment]
No more issue to the build and test ci, so closing.
