### ISSUE TITLE
can't initialize on e2e_simulator.launch.xml

### ISSUE THREAD

**Issue by banban1029** [autowarefoundation/autoware.universe#9278]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In the v1.0 branch, when running e2e_simulator.launch.xml,  localization is not functioning by "2D Pose Estimate". It seems there is an issue with initialization of the position. 

Additionally, starting AWSIM leads to a system shutdown.

Would you like assistance in troubleshooting these issues or adjusting the settings?

[Screencast from 11-10-2024 07:39:35 PM.webm](https://github.com/user-attachments/assets/77800f8f-2b65-4a52-9e8e-db388c3a6830)

![Screenshot from 2024-11-10 20-56-59](https://github.com/user-attachments/assets/47213e9a-e253-4541-90ad-2b28af977888)

![Screenshot from 2024-11-10 20-21-30](https://github.com/user-attachments/assets/81d8170d-c7c3-4ab9-87c5-08fd8ada82c4)

### Expected behavior

Using the 2D Pose Estimate, the vehicle can be localized by manually setting its position. This method allows me to provide an initial pose estimate for the vehicle in the simulation.

### Actual behavior

Using the 2D Pose Estimate, I can't setting vehicle model.

logs
`initializecall: /api/localization/initialize
[component_container_mt-77] [INFO] [1731240815.206639723] [default_ad_api.node.localization]: server call: /api/localization/initialize
[component_container_mt-77] [INFO] [1731240815.207852696] [default_ad_api.node.localization]: client call: /localization/initialize
[component_container_mt-77] [INFO] [1731240815.208617901] [default_ad_api.node.localization]: client exit: /localization/initialize
[component_container_mt-77] [INFO] [1731240815.208617850] [default_ad_api.node.localization]: server exit: /api/localization/initialize
[pose_initializer_node-37] [INFO] [1731240815.208209402] [localization.util.pose_initializer_node]: server call: /localization/initialize
[pose_initializer_node-37] [INFO] [1731240815.208356751] [localization.util.pose_initializer_node]: server exit: /localization/initialize
[service_log_checker-3] [ERROR] [1731240815.208494200] [system.service_log_checker]: /localization/initialize: status code 1 'The vehicle is not stopped.' (/localization/util/pose_initializer_node)
[service_log_checker-3] [ERROR] [1731240815.208828465] [system.service_log_checker]: /localization/initialize: status code 1 'The vehicle is not stopped.' (/default_ad_api/node/localization)
[service_log_checker-3] [ERROR] [1731240815.208909742] [system.service_log_checker]: /api/localization/initialize: status code 1 'The vehicle is not stopped.' (/default_ad_api/node/localization)
[service_log_checker-3] [ERROR] [1731240815.209521731] [system.service_log_checker]: /api/localization/initialize: status code 1 'The vehicle is not stopped.' (/localization/util/default_ad_api/helpers/automatic_pose_initializer)
[automatic_pose_initializer-38] [INFO] [1731240816.231051447] [localization.util.default_ad_api.helpers.automatic_pose_initializer]: client exit: /api/localization/initialize
[service_log_checker-3] [ERROR] [1731240816.231278897] [system.service_log_checker]: /api/localization/initialize: status code 1 'The vehicle is not stopped.' (/localization/util/default_ad_api/helpers/automatic_pose_initializer)
[gyro_odometer-39] [WARN] [1731240816.324664913] [localization.twist_estimator.gyro_odometer]: Twist msg is not subscribed
[component_container-66] [INFO] [1731240816.850879228] [planning.mission_planning.mission_planner]: waiting odometry... Route API is not ready.
[ekf_localizer-40] [WARN] [1731240816.904554298] [localization.pose_twist_fusion_filter.ekf_localizer]: The node is not activated. Provide initial pose to pose_initializer
[component_container_mt-73] [INFO] [1731240816.923455630] [planning.scenario_planning.parking.costmap_generator]: waiting for initial pose...
[ndt_scan_matcher-36] [ERROR] [1731240817.038243790] [localization.pose_estimator.ndt_scan_matcher]: Cannot find the reference position for map update. Please check if the EKF odometry is provided to NDT.
[scenario_selector-68] [INFO] [1731240817.132798727] [planning.scenario_planning.scenario_selector]: Waiting for current pose.
[system_error_monitor-22] [ERROR] [1731240817.132985509] [system.system_error_monitor]: vehicle_state_report msg is timeout...
[component_container_mt-71] [INFO] [1731240817.133226236] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner]: waiting for scenario_topic
[component_container_mt-72] [INFO] [1731240817.136136099] [planning.scenario_planning.lane_driving.motion_planning.surround_obstacle_checker]: waiting for dynamic object info...
[component_container-76] [INFO] [1731240817.137069250] [control.trajectory_follower.lane_departure_checker_node]: waiting for current_twist msg...

`

### Steps to reproduce

1. `ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=$HOME/maps/nishishinjuku_autoware_map/`
2. AWSIM起動
3. Using the 2D Pose Estimate

### Versions

- ubuntu22.04
- Autoware Tag v1.0
- AWSIM.Labs v1.3.1

**Comment by maxime-clem** [comment]
> In the v1.0 branch

Because `v1.0` is quite old and uses some outdated message types, I do not think it is compatible with recent versions of AWSIM.
Are you able to try the `main` branch ?

>  localization is not functioning by "2D Pose Estimate".

If everything works correctly then localization should happen automatically.

> Additionally, starting AWSIM leads to a system shutdown.

You are probably running out of video memory.
