### ISSUE TITLE
Inappropriate method in parking lot search function

### ISSUE THREAD

**Issue by NorahXiong** [autowarefoundation/autoware.universe#941]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

If the ego car coordinate is closer to a lanelet out of a parking lot(e.g. lanelet 34976 below) than to a lanelet in a parking lot(e.g. lanelet 35016 below), the scenario will be wrongly set to the lane-driving mode because no linked parking lots can be retrieved.
![image](https://user-images.githubusercontent.com/103234047/169473397-fb4abb45-03bb-4176-895b-3a2f378de9fa.png)

### Expected behavior

Parking scenario activated and trajectory generated by freespace planner.
![image](https://user-images.githubusercontent.com/103234047/169469119-ee500206-3eb0-45de-8eba-948b64f45c7a.png)

### Actual behavior

Lane-driving scenario activated and trajectory to the goal position not correctly generated.

### Steps to reproduce

1. Start autoware planning simulator using default
2. Set pose estimate in parking lot but not in lane, near lanelet 34976, far from lanelet 35016
3. Set goal pose in a parking spot

### Versions

- OS: Ubuntun 20.04
- ROS2: Galactic
- Autoware: Autoware.universe:main

### Possible causes

In scenario_selector_node, if the nearest lanelet of ego car is within a parking lot then ego car will be supposed to be in the parking lot. If ego car is in lane when the system starts, everything goes right. But if the system starts inside a parking lot, unexpected result may appear. So maybe the parameter used when querying the linked parking lot should be changed from nearest lanelet to ego car position.

Related code:
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp#L40
https://github.com/autowarefoundation/autoware.universe/blob/main/map/lanelet2_extension/lib/query.cpp#L438

**Comment by Sharrrrk** [comment]
Releated Issues:
https://github.com/autowarefoundation/autoware.universe/issues/941
https://github.com/autowarefoundation/autoware.universe/issues/947
