### ISSUE TITLE
Use `TrackedObjectKinematics` instead of `DetectedObjectKinematics` for `TrackedObject & object`

### ISSUE THREAD

**Issue by felixf4xu** [autowarefoundation/autoware.universe#9549]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In autoware, there are 2 kinds of ObjectKinematics definition, one is `TrackedObjectKinematics` and the other is `DetectedObjectKinematics`, they are equal to each other in integer value, but they should have difference namespaces.__

### Expected behavior

1)
 
```
void MapBasedPredictionNode::updateObjectData(TrackedObject & object)
{
  std::unique_ptr<ScopedTimeTrack> st_ptr;
  if (time_keeper_) st_ptr = std::make_unique<ScopedTimeTrack>(__func__, *time_keeper_);


  if (
    object.kinematics.orientation_availability ==
    autoware_perception_msgs::msg::DetectedObjectKinematics::AVAILABLE) {
    return;
  }
```
`DetectedObjectKinematics` is a wrong type, it should be `TrackedObjectKinematics` because of code type `TrackedObject & object`

2)

for same reason,
code
```
 switch (object.kinematics.orientation_availability) {
    case autoware_perception_msgs::msg::DetectedObjectKinematics::SIGN_UNKNOWN: {
```
should also use `TrackedObjectKinematics`

### Actual behavior

`DetectedObjectKinematics` is used for `TrackedObject` type.

### Steps to reproduce

check source code, code review.

### Versions

autoware, latest main branch

**Comment by amadeuszsz** [comment]
@felixf4xu good catch & thank you for your report! Addressed in https://github.com/autowarefoundation/autoware.universe/pull/9553
