### ISSUE TITLE
Can't stop before blocking obstacle in parking

### ISSUE THREAD

**Issue by alanmengg** [autowarefoundation/autoware.universe#980]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When  simulating in parking lot , if an obstacle blocks the trajectory and there is no available trajectory to reach the goal, the car can't stop before the obstacle and passes through it.
![Screenshot from 2022-05-27 10-58-18](https://user-images.githubusercontent.com/104343391/170623778-40682a48-7eb5-4ec2-ab66-b371e771cbf5.png)

### Expected behavior

Vehicle should stop if there is no available path. 

### Actual behavior

Vehicle can't stop and passes through the obstacle.

### Steps to reproduce

1. Run the planning simulator with parking lot, set a goal and engage.
2. Put a obstacle to block the ego vehicle.

### Versions

ubuntu 20.04
galactic
universe:main

### Possible causes

the published stop trajectory doesn't actually work because it's  current pose, and control module can't stop the car with 0 distance.

**Comment by xmfcx** [comment]
@alanmengg could you please share the resources and commands to reproduce this issue? Like maps used.

**Comment by alanmengg** [comment]
> here is the lanelet map I used for the simulation
[lishui_parking.zip](https://github.com/autowarefoundation/autoware.universe/files/8811260/lishui_parking.zip)

**Comment by alanmengg** [comment]
> 
here is the lanelet map I used for the simulation
[lishui_parking.zip](https://github.com/autowarefoundation/autoware.universe/files/8811270/lishui_parking.zip)

**Comment by mitsudome-r** [comment]
@TakaHoribe It would be nice if you can assign someone from TIER IV's planning team to take a look at this.

**Comment by shmpwk** [comment]
Does this PR solve the issue?
https://github.com/autowarefoundation/autoware.universe/pull/985

**Comment by raminterpl** [comment]
@alanmengg : Hi, can you pls share me map used for this parking scenario

**Comment by alanmengg** [comment]
> @alanmengg : Hi, can you pls share me map used for this parking scenario

here is the map
[map.zip](https://github.com/autowarefoundation/autoware.universe/files/9313732/map.zip)
p

**Comment by raminterpl** [comment]
@alanmengg : I confirm above mentioned issue. Ego vehicle is not stopping before blocking obstacle in parking
![Screenshot from 2022-08-23 16-18-31](https://user-images.githubusercontent.com/87844531/186139782-8826d898-a41d-45cb-89dd-9fd7bee4e06d.png)
.

**Comment by raminterpl** [comment]
@alanmengg : I confirm the same behavior . Ego vehicle is not stopping if there is an obstacle in trajectory path in Parkin
![Screenshot from 2022-08-23 16-24-05](https://user-images.githubusercontent.com/87844531/186141142-d3e2220a-86d7-4f65-b9a5-a34dde6a94d0.png)
g

**Comment by shmpwk** [comment]
@alanmengg 
Looks like this issue is not completed yet?

**Comment by mitsudome-r** [comment]
@alanmengg friendly ping.
